### ISSUE TITLE
Allow deployment on servlet 2.4/2.5 container

### ISSUE THREAD

**Issue by dlecan** [play2war/play2-war-plugin#1]
Allow deployment on servlet 2.4/2.5 container
Need synchronous communication with Akka invokers

**Comment by takezoe** [comment]
+1
We really need support for Servlet 2.4 / 2.5.

**Comment by dlecan** [comment]
@takezoe which servlet container is important for you ?

**Comment by takezoe** [comment]
We are still using Tomcat 6.0.x for some applications.
Of course, we really want to upgrade (or replace to other app server) them but we can't do it by some non-technical reasons...

**Comment by takezoe** [comment]
I'm trying to modify play2-war-plugin for Servlet 2.5 support at the forked repository:
https://github.com/takezoe/play2-war-plugin

It adopts wait and notify for synchronized execution and put web.xml which defines servlet and listener into the generated war file. I think this is a simplest way but I haven't understood Play2 and play2-war-plugin completely. So I can't believe this is a correct way to support Servlet 2.4 / 2.5.

**Comment by dlecan** [comment]
Good work @takezoe , this is the simplest way to be compatible with Servlet 2.x

Others possibilities :
- bypass Akka when invoking "play server", in order to have a synchronous call. Possible, but needs to do modification in Play code itself
- configure Akka with Dispatchers to use current thread to do its job (thx to CallingThreadDispatcher). No synchronization is required in that case

I will plan support Servlet 2.x in the next release thanks to your code, but many work has to be done :
- produce seperate artifacts for Servlet 2.x and 3.0
- allow configuration for the plugin to generate or not the web.xml

Thanks

**Comment by dlecan** [comment]
Done for v0.7
