### ISSUE TITLE
Log output of non Play war not shown in JBoss after PlayWar deployment

### ISSUE THREAD

**Issue by peshkira** [play2war/play2-war-plugin#101]
Hi!

I am using your plugin (v0.8) to create a war, which I want to deploy on a JBoss 7.1.1, where also another non-PlayFramewrok application is running.

First I deploy the other application and everything works fine. All its logs get printed to the console as well as get appended to the standard server.log of JBoss.

As soon as I deploy the Play App ROOT.war I get the following output in the console:

```
10:22:15,500 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-5) JBAS015876: Starting deployment of "ROOT.war"
10:22:24,607 INFO  [org.jboss.as.pojo] (MSC service thread 1-7) JBAS017000: Found legacy bean/pojo namespace: urn:jboss:bean-deployer:2.0 - might be missing some xml features (potential exceptions).
10:22:24,742 INFO  [org.jboss.as.connector.deployers.jdbc] (MSC service thread 1-1) JBAS010403: Deploying JDBC-compliant driver class org.h2.Driver (version 1.3)
10:22:24,755 INFO  [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/]] (MSC service thread 1-5) PlayServletWrapper > contextInitialized
```

and the following appended to another log file for my Play app:

```
2012-10-24 10:22:25,301 - [DEBUG] [play]: Plugin [play.api.db.BoneCPPlugin] is disabled
2012-10-24 10:22:25,322 - [DEBUG] [play]: Plugin [play.api.db.evolutions.EvolutionsPlugin] is disabled
2012-10-24 10:22:25,479 - [INFO] [application]: Starting my play web app
...
```

The problem is that the logs of the **other** application stop showing up in the console and in the server.log and I am left only with the Play app logs in a separate log file.

Here is my `conf/logger.xml`

```
<configuration>
  <conversionRule conversionWord="coloredLevel" converterClass="play.api.Logger$ColoredLevel" />
  <appender name="FILE" class="ch.qos.logback.core.FileAppender">
     <file>../standalone/log/c3po-web.log</file>
     <encoder>
       <pattern>%date - [%level] [%logger]: %message%n%xException</pattern>
     </encoder>
   </appender>

  <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
    <layout class="ch.qos.logback.classic.PatternLayout">
        <pattern>%date - [%level] [%logger]: %message%n%xException</pattern>
    </layout>
  </appender>

  <logger name="play" level="DEBUG" />
  <logger name="application" level="DEBUG" />
  <logger name="com.petpet" level="DEBUG" />

  <root level="INFO">
    <!-- <appender-ref ref="STDOUT" /> --> 
    <appender-ref ref="FILE" />
  </root>

</configuration>
```

**Comment by dlecan** [comment]
Logback configuration in Play application probably reconfigures the logs for the whole system.

You can try to add a `MY_PLAY_APP_ROOT/war/WEB-INF/jboss-deployment-structure.xml` with the following content:

``` xml
<jboss-deployment-structure>
    <deployment>
        <exclusions>
            <module name="org.slf4j" />
            <module name="org.slf4j.impl" />
            <module name="ch.qos.logback" />
        </exclusions>
    </deployment>
</jboss-deployment-structure>
```

Then package and redeploy. This may work.

**Comment by peshkira** [comment]
Unfortunately, that didn't do it. I have double checked, that the file is inside the war.
Do you have any other suggestions?

Thanks for your time and help

**Comment by dlecan** [comment]
What is the logging system of your other application ?

**Comment by peshkira** [comment]
The other application uses slf4j with the bindings for log4j

**Comment by dlecan** [comment]
Where is located `log4.xml` ? (or `log4.properties`)
Can you deploy the same `jboss-deployment-structure.xml` in this application ?

**Comment by peshkira** [comment]
log4j.xml is in `OTHER_APP.war/WEB-INF/classes/log4j.xml`
I deployed the same deployment-structure file to the non-play app, but the effect is the same.

As soon as the ROOT war is deployed I get the log:

```
[org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/]] (MSC service thread 1-5) PlayServletWrapper > contextInitialized
```

and then nothing else. Thanks for your help!

**Comment by dlecan** [comment]
Cohabitation between JBoss logging and Play logger is very bad and will generate new bugs again and again.

So I would like to disable internal Play logger: all Play logging statements would be redirected to server application logging framework. Internal `logger.xml` would be useless and Play logging configuration might be done through app server logging configuration.

This feature would be enabled  by adding a new dependency in the project.

What do you think of this ?

**Comment by dlecan** [comment]
Hi guys,

Here is a new dependency to include in your project to disable Play Logger:

``` scala
val appDependencies = Seq(
  // ... Actual dependencies
  "com.github.play2war.ext" %% "redirect-playlogger" % "1.0.1" // add this after your others dependencies
)
```

How does it work ?
Play logger configuration is disabled, that is to say project's `logger.xml` file will be ignored.
So logs have to be configured by your app server (JBoss for eg.).

Known issue : all Play logs will be output twice.
To fix this, I have to release new versions of Play2War (0.8.2 and 0.9-RC1-1), but I will do this only if you are interested by this new feature.

It is already available for Play 2.0.x and Play 2.1.x and compatible with all Play2war versions.

**Comment by dlecan** [comment]
New version `1.0.1` of the dependency:
`"com.github.play2war.ext" %% "redirect-playlogger" % "1.0.1"`

**Comment by dlecan** [comment]
Probably fixed by the new extension.

Please reopen if this issue isn't fixed.
