### ISSUE TITLE
Could Play2Servlet25.WAIT_TIMEOUT be configurable?

### ISSUE THREAD

**Issue by takezoe** [play2war/play2-war-plugin#103]
In the current implementation of Play2Servlet25 waits 10 sec for play execution.

``` scala
val WAIT_TIMEOUT = 10 * 1000
```

However sometimes it's too short. I would like to change it to an suitable value for application.

**Comment by dlecan** [comment]
Yes, I will add a new configuration key, as for Servlet 3.0 async timeout value.

**Comment by dlecan** [comment]
Play2War 0.8.1 has been release, with a fix for this issue.
See [Additional Play configuration keys](/dlecan/play2-war-plugin/wiki/AdditionalPlay2ConfigurationKeys) for configuration.
