### ISSUE TITLE
Play 2.1 and subcontext deployment

### ISSUE THREAD

**Issue by tobiasschittkowski** [play2war/play2-war-plugin#105]
Hello,

as Play 2.1 RC1 is out (https://github.com/playframework/Play20/commit/ba571ef1c99ec94c94d9eab9986a4c5c6dfa3b3e), could you give an estimation as when your war plugin will support this version and will have the announced feature of non-root context deployment?

Thank you!
Tobias

**Comment by dlecan** [comment]
Hi @tobiasschittkowski 

I'm currently evaluating the work to be done to be compatible with Play 2.1.xx
You will find all informations in issue #106.

**Comment by dlecan** [comment]
Play2War 0.9-RC1 has been released, with a solution for this issue.

**Comment by tobiasschittkowski** [comment]
...forgot to say THANK YOU for all the fantastic work you have done -> it works!

**Comment by dlecan** [comment]
Thank you :)
