### ISSUE TITLE
Upgrade to Play 2.1.xx

### ISSUE THREAD

**Issue by dlecan** [play2war/play2-war-plugin#106]
Play2War needs to be compatible with Play 2.1.xx

This is the main issue which sums up all the work to do to be compatible with.
- subcontext: **done**
- API breaks: **done**
- sbt upgrade: **done**
- scala upgrade: **done**
- Play dependencies: **done**
- CI upgrade (SBT): **done**
  - create new project infrastructure (main + tests project for each play 2.1.x runtimes): **done**
- SBT plugin upgrade: **done**
- create new `develop` branch for 0.8.x series: **done**

**Comment by dlecan** [comment]
Thanks to #111, only tests of _subcontext_ feature remains.

**Comment by dlecan** [comment]
See #116 for subcontext

**Comment by dlecan** [comment]
All jobs done !

**Comment by dlecan** [comment]
Play2War 0.9-RC1 has been released, with a solution for this issue.

**Comment by erkinun** [comment]
thanks for the update, i deployed play 2.1 app to tomcat, and it showed, but when i want to access the application, it tried to open its name for a get action and failed, what is the procedure for deploying at sub context?

**Comment by dlecan** [comment]
Thank you for testing this new feature :)

> it tried to open its name for a get action and failed, what is the procedure for deploying at sub context? 

I have to do some documentation about this, but there is nothing specific to Play2war to do.

Your Play application must be configured to be accessed by sub context (see [this yellow-highlighted line of code](https://github.com/dlecan/play2-war-plugin/blob/79da55c32c04b67a9f344737606edd9ce6ba6dbc/sample/common/conf/application.conf#L48)).
Don't forget the trailing slash `/` !

Example: `application.context=/myapp/`

Deploy your war (`myapp.war`) in Tomcat `webapps` folder and go to `http://myhost/myapp/`.

Does it work ?

**Comment by erkinun** [comment]
yes man, it works : ) documentation of play 2.0 is kind of confusing, so a little bit hard to learn : )
