### ISSUE TITLE
Obtainment of JkEnvVar values

### ISSUE THREAD

**Issue by porchy13** [play2war/play2-war-plugin#113]
Hi,

When the War archive is used on Tomcat behind Apache with mod_jk, it is possible to send environment variables with JkEnvVar to the Tomcat servlet.

Those values are stored as attribute of an HttpServletRequest and can be obtained by using the method getAttribute("<env_var_name>"). 

It would be nice if those values were forwarded to the Play Context object, into the args map.

regards,

Porchy

**Comment by dlecan** [comment]
Ok, I can transfert all request attributes into Play Context.

What is priority of this for you ?

**Comment by dlecan** [comment]
Do you need that for Play 2.0.x ?

**Comment by porchy13** [comment]
Hi, 

Sorry for having been so late for the response.

It's not a huge priority. We have the chance that Shibboleth check the headers to counter the headers modifications. 

What do you mean by Play 2.0.x? We can wait the update of your plugin for Play 2.1 if it is your question.

Thanks for your great job.

regards,

Porchy

**Comment by dlecan** [comment]
Ok, this will be done for next 0.9.x

**Comment by dlecan** [comment]
This is harder to implement than I thought initially.

Play Http.Context is initialized in a lazy mode when (Java)Action is created.
Actually, Play2War cannot attached Http.Context between this creation and user's action execution.

It needs more investigations.

**Comment by dlecan** [comment]
Current Play architecture doesn't allow such improvement.
Sorry.
