### ISSUE TITLE
Play2WarCommands getFiles skipHidden

### ISSUE THREAD

**Issue by sqs** [play2war/play2-war-plugin#114]
Elastic Beanstalk looks for config inside WAR files in a top-level directory called `.ebextensions` (note the preceding dot). If I put a `.ebextensions` file inside the `webappResources` dir (i.e., `war/`), it is excluded due to the `skipHidden=true` parameter of `Play2WarCommands.getFiles`.

Can I submit a patch that removes skipHidden so that dot-directories are included (if there is no specific purpose for skipHidden)? Or would you prefer me to submit a patch that lets the user configure whether hidden files/folders are included?

**Comment by sqs** [comment]
thanks!

**Comment by dlecan** [comment]
Play2War 0.9-RC1 has been released, with a solution for this issue.

**Comment by adelarsq** [comment]
Are there a way to configure files/folders that are not included (files that are hidden and are not)?
