### ISSUE TITLE
problem when submit form with large data

### ISSUE THREAD

**Issue by chuorn** [play2war/play2-war-plugin#123]
I used: - play 2.0.4
            - Java jdk 6
            - play2war 0.8.1
            - Tomcat 6.0
Problem I got:
   I have alot of checkbox like in attach file and have one sumbit button for delete information in database. If I try to sumbit with 500 checkboxs it is ok but If you try to submit with 2000 checkboxs and then I got the problem, it is not delete but 
it hang on it, and then it redirect to action of Form like: (I mean in browser like this: http://localhost:8080/Information/delete)

``` html
<form method="post" action="/Information/delete">
..............
</form>
```

in java code :

``` java
public static Result delete() {
    String[] codeToDelete = request().body().asMultipartFormData().asFormUrlEncoded().get("Chk");
    // loop in code to delete in database
    return redirect(routes.Information.index());
} 
```

**Comment by dlecan** [comment]
Do you have any exceptions in logs ?
When it hangs, what's the size of codeToDelete array ?

You may have reached post size limit of Tomcat's connector. Look for `maxPostSize` in http://tomcat.apache.org/tomcat-6.0-doc/config/http.html

Can you set it to `0` and try again ?

**Comment by dlecan** [comment]
Any news ?

**Comment by chuorn** [comment]
Hi, I change the way to submit,  I try to build all value from selected checkbox and assign it to hidden field.
So mean that I will sumbit only with hidden field that have all value I need. By do like my problem was fixed.
Thank you for your help, you have give me the way to deploy play with tomcat. :)

**Comment by dlecan** [comment]
Same issue as #127
