### ISSUE TITLE
Help on: module not found: com.github.play2war#play2-war-plugin;0.9-RC2

### ISSUE THREAD

**Issue by yakphi** [play2war/play2-war-plugin#126]
Hi,
trying to add your plugin to my project it can't find the dependency.
I have checked manually all the tried url and I didn't found any.

[warn]  module not found: com.github.play2war#play2-war-plugin;0.9-RC2
[warn] ==== typesafe-ivy-releases: tried
[warn]   http://repo.typesafe.com/typesafe/ivy-releases/com.github.play2war/play2-war-plugin/scala_2.9.1/sbt_0.11.3/0.9-RC2/ivys/ivy.xml
[warn] ==== local: tried
[warn]   C:\herramientas\play-2.0.4\framework..\repository/local/com.github.play2war/play2-war-plugin/scala_2.9.1/sbt_0.11.3/0.9-RC2/ivys/ivy.xml
[warn] ==== Typesafe repository: tried
[warn]   http://repo.typesafe.com/typesafe/releases/com/github/play2war/play2-war-plugin_2.9.1_0.11.3/0.9-RC2/play2-war-plugin-0.9-RC2.pom
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/com/github/play2war/play2-war-plugin_2.9.1_0.11.3/0.9-RC2/play2-war-plugin-0.9-RC2.pom
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.github.play2war#play2-war-plugin;0.9-RC2: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]      com.github.play2war:play2-war-plugin:0.9-RC2 (sbtVersion=0.11.3, scalaVersion=2.9.1)
[warn] 

By other side, I found that the newest plugin directory at 
http://repo.typesafe.com/typesafe/releases/com/github/play2war/
is empty.

Thanks in advance,
Yamil

**Comment by dlecan** [comment]
Hi,

Play2War 0.9.x is only compatible with Play 2.1 applications.

For Play 2.0.x applications, use Play2War 0.8.1.

Don't forget to add Play2War specific repository as written in
documentation.
