### ISSUE TITLE
Cannot download file size > 5MB on Tomcat 6

### ISSUE THREAD

**Issue by chuorn** [play2war/play2-war-plugin#127]
I used: - play 2.0.4
- Java jdk 6
- play2war 0.8.1
- Tomcat 6.0
  I have the problem when deploy with tomcat, I can not download file size >= 5MB. when I click download, nothing happend.
  If I use with play start or play run is ok.
  Thank you

**Comment by dlecan** [comment]
Can you try the following workarounds ?
https://groups.google.com/d/topic/play-framework/vNruSwYMbKs/discussion

**Comment by chuorn** [comment]
Hi, I try already but still have the same problem. Do you have any idea ?

**Comment by dlecan** [comment]
What so you mean by "when I click download, nothing happend." ?

**Comment by dlecan** [comment]
I have added integration tests to check if there are limits with download: 0.6Mb, 1.9Mb, 3.2Mb, 5.9Mb and 14.2Mb

Tests are sucessful either as chunked or as non chunked downloads on: 
- Tomcat 6
- OpenJDK 6
- Play 2.0.4
- Play2War 0.8.2-SNAPSHOT
  :/

Can you try this war file in your Tomcat deployed as `ROOT.war` ?
https://play-war.ci.cloudbees.com/job/Play_2_War_Run_integration_tests_-_204_Play_runtime/ws/sample/servlet25/target/a-play2war-sample-servlet25-1.0-SNAPSHOT.war

Then you can try to download:
- either `http://localhost:8080/bigContent?maxRange=900000`  => 5.9Mb file to download
- or `http://localhost:8080/chunkedBigContent?maxRange=900000` => same size but chunked download

**Comment by dlecan** [comment]
Any news on this issue ?

**Comment by dlecan** [comment]
I cannot reproduce this issue.
Please reopen it if you have more information to give.
