### ISSUE TITLE
cannot access to some page.

### ISSUE THREAD

**Issue by chuorn** [play2war/play2-war-plugin#131]
Hi, 
Sorry for post this subject, it is not related with play2war but I don't know how to contact you.
It look like I cannot access to this:
https://github.com/dlecan/play2-war-plugin/blob/develop/dlecan/play2-war-plugin/wiki/Configuration

Could you help me ?

Thank you
Chamnan

**Comment by dlecan** [comment]
Hi,

Here is the correct link:
https://github.com/dlecan/play2-war-plugin/wiki/Configuration

Where did you get your one ?

**Comment by kozyr** [comment]
The broken link came from https://github.com/dlecan/play2-war-plugin. I can't access any of the Configuration, Deployment etc. links from there.

**Comment by dlecan** [comment]
Thank you, I fixed all the links.
