### ISSUE TITLE
logging on jboss-7.1.1 stops working even when redirect-playlogger is added

### ISSUE THREAD

**Issue by jn73** [play2war/play2-war-plugin#133]
I followed the instructions to disable the play logger when deploying to jboss7 (https://github.com/dlecan/play2-war-plugin/wiki/ConfigurationLoggingJBoss7). Even when doing so my jboss server will stop logging as soon as i deploy my play war.

From my Build.scala:

``` scala
val appDependencies = Seq(
    jdbc,
    anorm,
    "org.scalatest" %% "scalatest" % "2.0.M5b" % "test",
    "com.microsoft.sqlserver" % "sqljdbc4" % "3.0",
    "com.github.play2war.ext" %% "redirect-playlogger" % "1.0.1"
  )
```

I also tried deleting the logger.xml file all together - same result.

I'm using play2-war-plugin 0.9-RC2

**Comment by dlecan** [comment]
Thank you for reporting this issue.

Can you give more informations about your test case ?

**Comment by jn73** [comment]
I reproduced it by:

precondition: logging is working in jboss server
1. create fresh play project (scala)
2. add play2-war plugin in plugins.sbt
3. add dependencies and config in Build.scala (servlet 3.0)
4. play war
5. deploy war in standalone/deployments (jboss 7.1.1)

=> no more logs

I pushed the test-project to github: https://github.com/jn73/play2-war-test

I didn't setup the jboss-server myself but i will provide configs from it if necessary.

**Comment by dlecan** [comment]
Thanks, I will try to reproduce this issue with your test case.

**Comment by jn73** [comment]
I installed jboss locally and deployed nothing but a EJB that logs on a timer (log4j). Deploying the same war will not impact the logging in this installation.

I will keep testing on our other server - but for now I don't know how to reproduce it on a "clean" jboss installation.

**Comment by dlecan** [comment]
Ok, so I wait for more informations.

**Comment by jn73** [comment]
Well this is driving me crazy.. It seems like this problem occurs when i deploy the war to a jboss that is located under our /apps. If I copy the jboss installation from /apps to /var/tmp it works!? Same host...

I also downloaded a fresh jboss-7.1.1. Did nothing but unzip it (one installation under /var/tmp and another to /apps), copied my war to each installation. Works under /var/tmp - fails under /apps.

Here are the logs:

working installation:

```
16:55:45,364 INFO  [org.jboss.as.server.deployment.scanner] (MSC service thread 1-4) JBAS015012: Started FileSystemDeploymentService for directory /var/tmp/janne/jboss-as-7.1.1.Final/standalone/deployments
16:55:45,487 INFO  [org.jboss.as.connector.subsystems.datasources] (MSC service thread 1-3) JBAS010400: Bound data source [java:jboss/datasources/ExampleDS]
16:55:45,508 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-3) JBAS015876: Starting deployment of "uttagonline-1.0-SNAPSHOT.war"
16:55:48,121 INFO  [org.jboss.as.pojo] (MSC service thread 1-1) JBAS017000: Found legacy bean/pojo namespace: urn:jboss:bean-deployer:2.0 - might be missing some xml features (potential exceptions).
16:55:48,404 INFO  [org.jboss.as.connector.deployers.jdbc] (MSC service thread 1-3) JBAS010403: Deploying JDBC-compliant driver class org.h2.Driver (version 1.3)
16:55:48,428 INFO  [org.jboss.as.connector.deployers.jdbc] (MSC service thread 1-3) JBAS010403: Deploying JDBC-compliant driver class com.microsoft.sqlserver.jdbc.SQLServerDriver (version 4.0)
16:55:48,547 INFO  [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/uttagonline-1.0-SNAPSHOT]] (MSC service thread 1-3) PlayServletWrapper > contextInitialized
16:55:48,809 INFO  [stdout] (MSC service thread 1-3) Play logs now directly handled by this application server
16:55:50,131 INFO  [org.jboss.web] (MSC service thread 1-3) JBAS018210: Registering web context: /uttagonline-1.0-SNAPSHOT
16:55:50,144 INFO  [org.jboss.as] (MSC service thread 1-1) JBAS015951: Admin console listening on http://127.0.0.1:9990
16:55:50,144 INFO  [org.jboss.as] (MSC service thread 1-1) JBAS015874: JBoss AS 7.1.1.Final "Brontes" started in 6960ms - Started 178 of 256 services (77 services are passive or on-demand)
16:55:50,191 INFO  [org.jboss.as.server] (DeploymentScanner-threads - 2) JBAS018559: Deployed "uttagonline-1.0-SNAPSHOT.war"
```

failing:

```
16:56:47,508 INFO  [org.jboss.as.server.deployment.scanner] (MSC service thread 1-2) JBAS015012: Started FileSystemDeploymentService for directory /apps/program/janne/jboss-as-7.1.1.Final/standalone/deployments
16:56:47,513 INFO  [org.jboss.as.remoting] (MSC service thread 1-4) JBAS017100: Listening on /127.0.0.1:4447
16:56:47,605 INFO  [org.jboss.as.connector.subsystems.datasources] (MSC service thread 1-2) JBAS010400: Bound data source [java:jboss/datasources/ExampleDS]
16:56:47,635 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-3) JBAS015876: Starting deployment of "uttagonline-1.0-SNAPSHOT.war"
16:56:51,296 INFO  [org.jboss.as.pojo] (MSC service thread 1-4) JBAS017000: Found legacy bean/pojo namespace: urn:jboss:bean-deployer:2.0 - might be missing some xml features (potential exceptions).
16:56:51,499 INFO  [org.jboss.as.connector.deployers.jdbc] (MSC service thread 1-1) JBAS010403: Deploying JDBC-compliant driver class org.h2.Driver (version 1.3)
16:56:51,509 INFO  [org.jboss.as.connector.deployers.jdbc] (MSC service thread 1-1) JBAS010403: Deploying JDBC-compliant driver class com.microsoft.sqlserver.jdbc.SQLServerDriver (version 4.0)
16:56:51,604 INFO  [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/uttagonline-1.0-SNAPSHOT]] (MSC service thread 1-3) PlayServletWrapper > contextInitialized
```

[logging to server.log stops here]
[press ctrl-c and shut-down logging continues]

```
^C16:57:27,462 INFO  [org.jboss.as.logging] JBAS011503: Restored bootstrap log handlers
16:57:27,484 INFO  [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/uttagonline-1.0-SNAPSHOT]] PlayServletWrapper > contextDestroyed
16:57:27,485 INFO  [stdout] 2013-02-27 16:57:27,485 - [INFO] - from play in MSC service thread 1-4 
16:57:27,485 INFO  [stdout] Stopping play server...
16:57:27,486 INFO  [stdout] 
16:57:27,492 INFO  [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/uttagonline-1.0-SNAPSHOT]] Play server stopped
16:57:27,494 INFO  [com.arjuna.ats.jbossatx] ARJUNA032018: Destroying TransactionManagerService
16:57:27,495 INFO  [com.arjuna.ats.jbossatx] ARJUNA032014: Stopping transaction recovery manager
16:57:27,523 INFO  [org.jboss.as.server.deployment] JBAS015877: Stopped deployment uttagonline-1.0-SNAPSHOT.war in 86ms
16:57:27,528 INFO  [org.jboss.as] JBAS015950: JBoss AS 7.1.1.Final "Brontes" stopped in 58ms
```

Can it be a timing thing? The server is a virtual one, and the filesystem is LVM(ish). The volumes are on the same VG but i don't know how they map to physical discs or if it's any significant difference in access times.

```
$ df
Filsystem             1K-block    Använt Tillgängl Anv% Monterat på
/dev/mapper/vgroot-lvroot
                      10079084   8749424    817660  92% /
tmpfs                  1962576         0   1962576   0% /dev/shm
/dev/mapper/vgroot-lvapps
                      40316280  18899220  19369060  50% /apps
```

**Comment by dlecan** [comment]
I don't understand how JBoss installation folder can change anything.
A hidden exception may occur when JBoss is deployed on `/apps`

You could start JBoss in debug mode, attach your Java debugguer on it and hook an Exception break point to see what happens between `/apps` and `/var/tmp`.

**Comment by dlecan** [comment]
Any news ?

**Comment by jn73** [comment]
Hi, sorry i run out of time on this one.. Deployed it as a standalone app (for now). I just debugged the server during deployment of the war however. Didn't see any uncaught exceptions. Lots of caught exceptions (BundleException and a bunch of CEStreamExhausted exceptions until deployment is aborted (because of debugging).

Too much noice when catching java.lang.Exception with subclasses.. Did not see any difference between the installations though - going through the same exceptions and deployment aborts.

**Comment by jn73** [comment]
Perhaps you should just close this one? I won't have time to troubleshoot more and well.. given the wierdness of running the appserver from different locations it will be difficult to reproduce..

We ended up deploying to a tomcat server instead.

**Comment by dlecan** [comment]
Configuring Play log on servlet engines is a real mess, I will try to improve that directly in Play core with the Play team.
Sorry, I can't help more.
