### ISSUE TITLE
Tomcat 6 + Play 2.1

### ISSUE THREAD

**Issue by bjoernjacobs** [play2war/play2-war-plugin#135]
Hallo, I have problems with the constellation Play 2.1 and Tomcat 6

I followed the instructions and generated a war file from my play project - so far so good.
In my application.conf I added the line

```
application.context=/MyProject/
```

since it will be executed parallel to other web services on the same tomcat.

In file Build.scala I configured it to run on Servlet 2.5 (Tomcat 6)

```
    val main = play.Project(appName, appVersion, appDependencies).settings(
        Play2WarKeys.servletVersion := "2.5"
    ).settings(Play2WarPlugin.play2WarSettings: _*)
```

The directory structure within the war looks like this:

```
    META-INF
    META-INF/MANIFEST.MF
    WEB-INF
    WEB-INF/lib
```

within the lib directory there are a lot of jars including my project's jar.

When I deploy the war file on my tomcat server and take a look in tomcat's log file "catalina.out" only the following two lines occur, nothing else:

```
    Mar 6, 2013 4:34:45 PM org.apache.catalina.startup.HostConfig deployWAR
    INFO: Deploying web application archive MyProject.war
```

When opening the url localhost:8080/MyProject/ I receive the following error:

```
    HTTP Status 404 - /MyProject/
    type Status report
    message /MyProject/
    description The requested resource (/MyProject/) is not available.
    Apache Tomcat/6.0.32
```

Do you have some advice what to do here?
Thanks!
Björn

**Comment by dlecan** [comment]
Thank you for this precise bug report. What is the version of Play2War ?

> The directory structure within the war looks like this

`WEB-INF/web.xml` file seems to be missing. Do you see it in `PROJECT_HOME/war/WEB-INF` folder ?
It is automatically generated by the plugin.

**Comment by bjoernjacobs** [comment]
Hallo,

thank you for your response. It turned out that play still was using the old configuration where I set the servlet version to 3.0. I had to perform a _clean_ before compiling and afterwards it was recognized correctly.

Sorry for this false alarm. :) Now everything is working as espected.
