### ISSUE TITLE
Flash scope cookie is not removed in tomcat

### ISSUE THREAD

**Issue by psartini** [play2war/play2-war-plugin#139]
Environment: Tomcat 7, JDK 7u11

It seems the flash scope is not handled correctly when deploying to tomcat. The flash cookie is never removed and is available until the browser session is closed.

Using play2 without war everything works as expected.

**Comment by dlecan** [comment]
With Play 2.1 / Play2War 0.9-RCx ?

**Comment by psartini** [comment]
Play 2.1 / Play2War 0.9-RC2

**Comment by dlecan** [comment]
You're right, this will be fixed by #137, available in the next 0.9-RC3 release (in the next couple of weeks).
