### ISSUE TITLE
Error Action Not Found After deploy to WebSphere

### ISSUE THREAD

**Issue by tru3d3v** [play2war/play2-war-plugin#142]
Dear dlecan,

When i deploying to Websphere i got the error bellow

![error_after_deploy_towebsphere](https://f.cloud.github.com/assets/2869216/298959/486f28f8-956c-11e2-84dd-a37954bd6068.png)

**Comment by dlecan** [comment]
Which versions ?
- Websphere
- Play2War
- Play

Did you configure `application.context` key configuration in `conf/application.conf` ?
Eg.: `application.context=/myplay/`

See https://github.com/dlecan/play2-war-plugin/wiki/Deployment#subcontext-deployment

**Comment by tru3d3v** [comment]
Wow, its works...sorry i am forget the applcation.context value :D 

![1](https://f.cloud.github.com/assets/2869216/299055/a7120f30-956f-11e2-893c-4d7f5e63f1f1.png)
![2](https://f.cloud.github.com/assets/2869216/299056/ac89e938-956f-11e2-8cf9-cc1f9de1c2bb.png)
![3](https://f.cloud.github.com/assets/2869216/299057/afc1b41e-956f-11e2-9ed6-bae2c8276d57.png)
![4](https://f.cloud.github.com/assets/2869216/299059/b4e2a3cc-956f-11e2-953a-53e11c5e1987.png)
![5](https://f.cloud.github.com/assets/2869216/299062/c48bf6ca-956f-11e2-9923-bfd7d3a3af58.png)

Thanks

**Comment by dlecan** [comment]
Do you know the version of WAS CE ?
Thank you.

**Comment by tru3d3v** [comment]
mybe :

  IBM WebSphere Application Server Community Edition (3.0.0.3)

i see in console log the server like that.

Thanks
