### ISSUE TITLE
play2-war-plugin_2.9.2_0.12-0.9-RC2 not avaliable in maven repository

### ISSUE THREAD

**Issue by proDOOMman** [play2war/play2-war-plugin#144]
http://mvnrepository.com/artifact/com.github.play2war/play2-war-plugin_2.9.2_0.12/0.9-RC2
There is no jar and no pom file.

**Comment by dlecan** [comment]
Yes you're right, Play2War SBT plugin can't be published on maven Central repository. 

Is it an issue for you ?

**Comment by proDOOMman** [comment]
Oh, sorry. I  should sleep more.
All works fine, thank you!
