### ISSUE TITLE
play2war module not found at http://repo.typesafe.com/typesafe/releases/com/github/play2war/

### ISSUE THREAD

**Issue by programmist** [play2war/play2-war-plugin#146]
I used the play2war plugin (0.9) for a Play 2.1 project last week and it worked great.  I started a new project this week and Play was unable to import it.  I set it up identically to the other project.  After trying several things I decided to look at the repo and I noticed it is no longer there - http://repo.typesafe.com/typesafe/releases/com/github/play2war/ is empty.

Any help appreciated.

**Comment by dlecan** [comment]
repo.typesafe.com is an Artifactory proxy repository for many other Maven repositories, such as Maven Central.

Play2War is available at:
- Scala Sbt repo for SBT plugin: http://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.github.play2war/play2-war-plugin/scala_2.9.2/sbt_0.12/0.9/
- Maven Central for librairies: http://search.maven.org/#search|ga|1|com.github.play2war

http://repo.typesafe.com/typesafe/releases/com/github/play2war/ is empty because no one has downloaded it throught this proxy.

What are your errors ?
You can set up your SBT build to debug level (in `YOUR_PROJECT/project/plugin.sbt`, switch `logLevel := Level.Warn` to `logLevel := Level.Debug`), it will give you much more details.

**Comment by programmist** [comment]
I'm getting the following error:

> [error] (*:update) sbt.ResolveException: unresolved dependency: com.github.play2war#play2-war-plugin;0.9: not found

Also the following warnings:

> [error] (*:update) sbt.ResolveException: unresolved dependency: com.github.play2war#play2-war-plugin;0.9: not found
> [warn] some of the dependencies were not recompiled properly, so classloader is not avaialable
> [info] Updating {file:/home/tony/Desktop/brightwing.com/}brightwing-web...
> [warn]  module not found: com.github.play2war#play2-war-plugin;0.9  
> [warn] ==== local: tried
> [warn]   /opt/play-2.1.0/repository/local/com.github.play2war/play2-war-plugin/0.9/ivys/ivy.xml
> [warn] ==== Typesafe Releases Repository: tried
> [warn]   http://repo.typesafe.com/typesafe/releases/com/github/play2war/play2-war-plugin/0.9/play2-war-plugin-0.9.pom
> [warn] ==== Typesafe Snapshots Repository: tried
> [warn]   http://repo.typesafe.com/typesafe/snapshots/com/github/play2war/play2-war-plugin/0.9/play2-war-plugin-0.9.pom
> [warn] ==== public: tried
> [warn]   http://repo1.maven.org/maven2/com/github/play2war/play2-war-plugin/0.9/play2-war-plugin-0.9.pom
> [warn]  ::::::::::::::::::::::::::::::::::::::::::::::  
> [warn]     ::          UNRESOLVED DEPENDENCIES         ::
> [warn]     ::::::::::::::::::::::::::::::::::::::::::::::
> [warn]     :: com.github.play2war#play2-war-plugin;0.9: not found
> [warn]     ::::::::::::::::::::::::::::::::::::::::::::::

**Comment by dlecan** [comment]
Play2War plugin is located here:
http://repo.scala-sbt.org/scalasbt/simple/sbt-plugin-releases/com.github.play2war/play2-war-plugin/

But `http://repo.scala-sbt.org/scalasbt/simple/sbt-plugin-releases` should be a default repository (or its alias `http://scalasbt.artifactoryonline.com/scalasbt/sbt-plugin-releases`).

I will check into Play 2.1 configuration if they are configured by default.

If you need a quick fix, add this configuration in `YOUR_PROJECT/project/plugins.sbt`:

```
resolvers += Resolver.url("sbt-plugin-releases", url("http://repo.scala-sbt.org/scalasbt/sbt-plugin-releases"))(Resolver.ivyStylePatterns)
```

or

```
resolvers += Resolver.url("sbt-plugin-releases", url("http://scalasbt.artifactoryonline.com/scalasbt/sbt-plugin-releases"))(Resolver.ivyStylePatterns)
```

**Comment by dlecan** [comment]
I can confirm that Scala SBT repo is provided by default with SBT:
https://github.com/sbt/sbt/blob/0.12.0/ivy/IvyInterface.scala#L196

Something must be wrong this your setup.
Please reopen if you still have this issue with new information.

**Comment by programmist** [comment]
I haven't worked on that project for about two weeks, but this morning I decided to try again to see if I could resolve the issue.  When I ran "play war" it worked on the first try.  I haven't changed anything, so I have no explanation for why it suddenly works.  I won't look a gift horse in the mouth.

**Comment by dlecan** [comment]
Great to read that good news :)
