### ISSUE TITLE
Dead lock in Play2Servlet25RequestHandler

### ISSUE THREAD

**Issue by takezoe** [play2war/play2-war-plugin#147]
`Play2Servlet25RequestHandler` blocks until response is done by `onFinishService()` and `onHttpResponseComplete()`. But if the request processing is fast and response is small, sometimes `onHttpResponseComplete()` is called before `onFinishService()`. So it causes dead lock.

`onFinishService()` should not wait if `onHttpResponseComplete()` is called before it.

**Comment by takezoe** [comment]
We are using old version of play2-war-plugin because still using Play 2.0.1. I solved dead lock using AtomicBoolean as the lock object like this: https://github.com/takezoe/play2-war-plugin/commit/e95c0a3f124165b1a3785598b4c476e6c68bb04e
Of course, there may be better solution...

**Comment by dlecan** [comment]
Thanks for your help.
You definitely should upgrade to Tomcat7, Tomcat6 begins to be quite old now ...
