### ISSUE TITLE
Explain how to use 'targetName' key property

### ISSUE THREAD

**Issue by jn73** [play2war/play2-war-plugin#148]
I'm trying to exclude version number from the generated war by using the targetName configuration that was mentioned in the changelog for 0.9.

I haven't found any documentation, but my guess was that a configuration like this would do the trick:

```
  val main = play.Project(appName, appVersion, appDependencies).settings(
    lessEntryPoints <<= baseDirectory(customLessEntryPoints),
    requireJs += "main.js",
    requireJsShim += "main.js",
    Play2WarKeys.servletVersion := "2.5",
    Play2WarKeys.targetName := Some("mywarname")
  ).settings(Play2WarPlugin.play2WarSettings: _*)
```

**Comment by dlecan** [comment]
Good question, I will ask to this author of this feature (see https://github.com/dlecan/play2-war-plugin/pull/134).
And then, improve the documentation :)

**Comment by jozic** [comment]
I've just tested that on my branch in sample project  

```
lazy val servlet25 = play.Project(
   appName + "servlet25", 
   appVersion, 
   appDependencies, 
   path = file("servlet25"), 
   settings = commonSettings ++ warProjectSettings ++ Seq(
      Play2WarKeys.servletVersion := "2.5", 
      Play2WarKeys.targetName := Some("my-fancy-target-name"))) dependsOn (common)
```

this works fine and generates a war file with name "my-fancy-target-name.war"

**Comment by dlecan** [comment]
Thank you, @jozic 
@jn73 settings declaration order is probably important.
Can you try this?

```
val main = play.Project(appName, appVersion, appDependencies).settings(
    lessEntryPoints <<= baseDirectory(customLessEntryPoints),
    requireJs += "main.js",
    requireJsShim += "main.js"
).settings(Play2WarPlugin.play2WarSettings: _*).settings(
    Play2WarKeys.servletVersion := "2.5",
    Play2WarKeys.targetName := Some("mywarname")
)
```

**Comment by jn73** [comment]
Yes, that's it! Thanks :-)

servletVersion works within the first block, targetName must be chained after play2WarSettings.

**Comment by dlecan** [comment]
Documentation is up to date.
https://github.com/dlecan/play2-war-plugin/wiki/Play2War-configuration#target-war-file-name

**Comment by jozic** [comment]
:+1:
