### ISSUE TITLE
TomEE : Servlets named [Play] deployed twice which is not permitted

### ISSUE THREAD

**Issue by programmist** [play2war/play2-war-plugin#149]
We're having trouble with the latest Tomee 1.5.2 milestone and the Play2War plugin.  During server startup we get the following error (catalina.out):

```
org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/admin]]
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:154)
    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:633)
    at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1114)
    at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1673)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:722)
Caused by: java.lang.IllegalArgumentException: The servlets named [Play] and [Play] are both mapped to the url-pattern [/] which is not permitted
    at org.apache.catalina.deploy.WebXml.addServletMapping(WebXml.java:335)
    at org.apache.catalina.deploy.WebXml.merge(WebXml.java:1691)
    at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1338)
    at org.apache.tomee.catalina.OpenEJBContextConfig.webConfig(OpenEJBContextConfig.java:273)
    at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:878)
    at org.apache.tomee.catalina.OpenEJBContextConfig.configureStart(OpenEJBContextConfig.java:83)
    at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:369)
    at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:119)
    at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5179)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
```

We are trying to understand whether the problem is in Tomee or Play.  To reproduce the error take the helloworld sample app from Play 2.1.1 and modify the files (below) to import play2war plugin.  After running `play war`, rename the war to "helloworld.war".  Start Tomee and move "helloworld.war" to the Tomee home "webapps" directory.  You should see that error in logs/catalina.out.
### plugins.sbt

``` Scala
// Comment to get more information during initialization
logLevel := Level.Warn

// The Typesafe repository
resolvers += "Typesafe repository" at "http://repo.typesafe.com/typesafe/releases/"

// Use the Play sbt plugin for Play projects
addSbtPlugin("play" % "sbt-plugin" % Option(System.getProperty("play.version")).getOrElse("2.0"))

addSbtPlugin("com.github.play2war" % "play2-war-plugin" % "0.9")
```
### Build.scala

``` Scala
import sbt._
import Keys._
import play.Project._
import com.github.play2war.plugin._

object ApplicationBuild extends Build {

    val appName         = "helloworld"
    val appVersion      = "1.0"

    val appDependencies = Seq(
      javaCore
    )

    val main = play.Project(appName, appVersion, appDependencies).settings(
       Play2WarKeys.servletVersion := "3.0"
    ).settings(Play2WarPlugin.play2WarSettings: _*)
}
```

**Comment by dlecan** [comment]
> at org.apache.catalina.deploy.WebXml.addServletMapping(WebXml.java:335)
> at org.apache.catalina.deploy.WebXml.merge(WebXml.java:1691)

Theses lines suggest you have a `YOUR_PROJECT/war/WEB-INF/web.xml` file, which declares one or more servlets.
If you need them, why not, but you can't name them "Play", as it is [the name of the annotation-driven servlet](https://github.com/dlecan/play2-war-plugin/blob/develop/project-code/core/servlet30/src/main/scala/Play2Servlet30.scala#L16) provided by Play2War.

**Comment by programmist** [comment]
Hi Damien. I used the "helloworld" sample from the Play2.1.1/samples directory and only made the modifications to add the play2war plugin.  There is no war in that project and I didn't add one.  My colleague received this response from one of the Tomee developers: http://openejb.979440.n4.nabble.com/war-file-fails-to-deploy-servlet-loaded-twice-td4662288.html.  

It seems that there was a change in Tomee that makes it less tolerant to duplicate servlet mappings.  The only mapping I've seen is in Play2Servlet, but it's finding something else.

**Comment by dlecan** [comment]
It was working with TomEE 1.5.1 and doesn't work anymore with TomEE 1.5.2 ?
You can upload your generated WAR file somewhere, I'd like to check out its content.

I will try to reproduce this issue on TomEE 1.5.2.

**Comment by programmist** [comment]
Yes, it worked with 1.5.1, but not with 1.5.2.  After several days of debugging we finally discovered that it the version of Tomcat was the root of the issue.  Tomee 1.5.1 uses Tomcat 7.0.34 which worked fine.  Tomee 1.5.2 uses Tomcat 7.0.37 whch caused a problem.  

I should note that we did try running the war in just a plain Tomcat 7.0.37 instance and it worked.  So it seems that it's a combination of Tomcat/Tomee versions.

Our solution was to copy the tomcat libs from tomcat 7.0.34 into the Tomee 1.5.2 libs directory, overwriting the existing ones.  I've uploaded the my modified helloworld project with war to http://stupidjavatricks.com/code/helloworld.tar.gz

Please let me know once you have it.

**Comment by programmist** [comment]
I also wanted to mention that I used the Reflections library (https://code.google.com/p/reflections/) to detect if there were multiple classes in the classpath using the @WebServlet annotation.  I deployed the war and the only class detected was Play2Servlet.  

``` Java
// in some controller method
Reflections reflections = new Reflections();
Set<Class<?>> servlets = reflections.getTypesAnnotatedWith(WebServlet.class);
assert servlets.size() == 1
assert servlets.get(0).equals("play.core.server.servlet30.Play2Servlet");
```

**Comment by dlecan** [comment]
Ok, thank you for all theses tests.

For Tomcat 7, Play2War integration tests are run on 7.0.32, quite old now.
I will run Play2War integration tests on Tomcat 7.0.[34, 35, 37, 39], to try to detect the same regression.

**Comment by dlecan** [comment]
Integration tests results on Tomcat:
- 7.0.32: OK
- 7.0.34: OK
- 7.0.35: OK
- 7.0.37: OK
- 7.0.39: OK

I can't find anything in [Tomcat 7 changelog](http://tomcat.apache.org/tomcat-7.0-doc/changelog.html) about a more restrictive servlet loading.

Integration tests rely on [Cargo framework](http://cargo.codehaus.org/), which is not compatible with TomEE yet. So I will have to test it manually.

Does it work on TomEE 1.5.1 final ?
Does it work on TomEE 1.5.2 final ?
Does it work on TomEE 1.5.3-SNAPSHOT ?

**Comment by dlecan** [comment]
> I can't find anything in Tomcat 7 changelog about a more restrictive servlet loading.

Finally, I was able to find it:
https://issues.apache.org/bugzilla/show_bug.cgi?id=54387

It has been included in Tomcat 7.0.35.

**Comment by programmist** [comment]
That confirms our findings, but it's strange because we tried it on bare Tomcat and it always worked, but Tomee versions higher than 1.5.1 always failed until we copied the JARs from the Tomcat (7.0.34) lib folder to the Tomee lib folder.  

I tried it on TomEE 
- 1.5.1 final:  OK
- 1.5.2 final:  ERROR
- 1.6.0.beta1:  ERROR
- 1.6.0-SNAPSHOT:  ERROR

`cp -f apache-tomcat-7.0.34/lib/*.jar   apache-tomee-plus-1.5.2/lib/`
- 1.5.2 with copied JARs:  OK

**Comment by dlecan** [comment]
All Tomcat versions and Play2War are OK.

TomEE 1.5.1 [with Tomcat 7.0.34](http://svn.apache.org/viewvc/tomee/tomee/tags/tomee-1.5.1/pom.xml?view=markup) is OK
TomcatEE 1.5.2 [with Tomcat 7.0.37](http://svn.apache.org/viewvc/tomee/tomee/tags/tomee-1.5.2/pom.xml?revision=1459131&view=markup) is KO.

According to [a discussion on TomEE ML](http://openejb.979440.n4.nabble.com/war-file-fails-to-deploy-servlet-loaded-twice-td4662288.html):

> We hacked it in 1.6.0-SNAPHOT but i don't think it was backported in 1.5.x
> since it was not a good practise and not asked.

TomEE 1.6 may work as excepted (despite Tomcat 7.0.39) and provided patch for 1.6 could be backported to 1.5.x (if asked).

Conclusion: you should ask a backport :)

**Comment by programmist** [comment]
That's strange.  I built Tomee 1.6.0-SNAPSHOT (trunk) and tried it and it did not work.  I'll try it again.

**Comment by programmist** [comment]
I tried again on a fresh checkout of 1.6.0-SNAPSHOT and it still fails to load due to the "duplicate mapping."  Here were my steps:

```
svn co http://svn.apache.org/repos/asf/tomee/tomee/trunk/
cd trunk
export  MAVEN_OPTS="-Xmx2048m -XX:MaxPermSize=2048m"
mvn clean install -DskipTests -DfailIfNoTests=false
unzip tomee/apache-tomee/target/apache-tomee-plus-1.6.0-SNAPSHOT.zip
curl http://stupidjavatricks.com/code/helloworld.tar.gz | tar xzv
cp helloworld/target/helloworld-1.0.war apache-tomee-plus-1.6.0-SNAPSHOT/webapps/helloworld.war
chmod +x apache-tomee-plus-1.6.0-SNAPSHOT/bin/*
./apache-tomee-plus-1.6.0-SNAPSHOT/bin/startup.sh
```

Wen I look at `apache-tomee-plus-1.6.0-SNAPSHOT/logs/catalina.out` I see the stacktrace.

Am I doing something wrong?

**Comment by dlecan** [comment]
> Am I doing something wrong?

Probably nothing. 1.6.0-SNAPSHOT has the same issue.
For me, that is a TomEE issue, because it works on a vanilla Tomcat 7.0.39.

**Comment by dlecan** [comment]
I tried your [sample](http://stupidjavatricks.com/code/helloworld.tar.gz) on TomEE 1.5.1 and 1.5.2: I just get 404 error for the welcome page (http://localhost:8080/), where as exactly the same war works on Tomcat, JBoss and Jetty: `CLASSES FOUND WITH WEBSERVLET ANNOTATION`.

And only one line in browser: `play.core.server.servlet30.Play2Servlet`

What to do in order to make work on TomEE 1.5.1?

**Comment by programmist** [comment]
Sorry, I only just saw this.  I specified application.context=/helloworld/, so you should be able to load it from http://localhost:8080/helloworld/

To work with TomEE, just unzip the archive, cd into the directory, and make the files under bin/ are executable (chmod +x bin/*).  Make sure the war is named helloworld.war and place it in the webapps/ directory  run bin/startup.sh (or .bat if Windows).  That should be it.  bin/shutdown.sh to stop the server.

**Comment by dlecan** [comment]
> just unzip the archive

OK

> Make sure the war is named helloworld.war

OK

> and place it in the webapps/ directory 

OK

> run bin/startup.sh (or .bat if Windows). 

OK

> http://localhost:8080/helloworld/

404 error :(
With Oracle JDK 7, either on TomEE 1.5.1 or 1.5.2.

I can see in logs that "helloworld" app is deployed, but nothing happens. The main Play2War servlet is probably not found by TomEE, which leads to 404 errors.

**Comment by programmist** [comment]
You can add 

>  application.context=/helloworld/

to application.conf and then rebuild the war (play war).

You should notice an exception in logs/catalina.out:  

> java.lang.IllegalArgumentException: The servlets named [Play] and [Play] are both mapped to the url-pattern [/] which is not permitted

You should still get a 404 because of this error. 

Edit: You are probably getting this exception now, even without the application.context setting.

**Comment by dlecan** [comment]
Still a blocking issue for you ? I can reproduce it.

**Comment by programmist** [comment]
Yes, this is still a blocking issue.  Thanks.

**Comment by dlecan** [comment]
@programmist Oh, dear, i wrote someting wrong : I **can't** reproduce it.

**Comment by programmist** [comment]
I think this can be safely closed. If I'm wrong, please feel free to reopen. Thanks.
