### ISSUE TITLE
No response on JBoss 7.0.x @Cloudbees

### ISSUE THREAD

**Issue by dlecan** [play2war/play2-war-plugin#15]
Config :
- Play 2 war plugin : 0.2-SNAPSHOT
- JBoss 7.0.x
- Servlet 3.x mode

No reponse from server.

See http://servlet30.play-war.cloudbees.net

**Comment by imeredith** [comment]
This is working now. Need to run the following command in the future with the cloudbees sdk for new deployments to different appid's.

 bees app:update play-war/<appid> disableProxyBuffering=true

-Ivan [CloudBees Engineering]

**Comment by dlecan** [comment]
Yeh ! Cloudbees hidden features :-)

Many thanks Ivan

**Comment by imeredith** [comment]
It's a hidden feature that may become standard possibly.

I'm looking at doing a deployment plugin for sbt which will set that.

Of course native support is coming soon and that will be the recommended way eventaully, but it's great to have support for war's in the mean time.
