### ISSUE TITLE
Support Caucho Resin

### ISSUE THREAD

**Issue by dlecan** [play2war/play2-war-plugin#157]
http://cargo.codehaus.org/Resin+4.x

**Comment by samspycher** [comment]
Wow, Scala, Java, and PHP all in one app!? :D

**Comment by dlecan** [comment]
@samspycher what do you mean ?

**Comment by samspycher** [comment]
[Resin integrates PHP nicely with Quercus.](http://wiki4.caucho.com/Resin_4_built-in_fast_PHP_support_called_Quercus_:_covers_Java_integration,_JSON_support_and_more)

**Comment by dlecan** [comment]
Interesting project, thanks
