### ISSUE TITLE
Session Cookie Paths are not Root Context

### ISSUE THREAD

**Issue by jplehmann** [play2war/play2-war-plugin#158]
We are having a problem of Play storing session cookies with a path which is not the root context. I don't know if this is a play2war problem, and I am happy to add additional logging etc, to try to pinpoint the problem, I just don't know what to look for. 

We're using Play 2.1.1.  Play2war plugin is 0.9. We do not experience this problem with "raw play" or even when deployed in TomEE, unless TomEE is running within a VM.

In our app we are using the authentication pattern demonstrated in Zen Tasks which stores a session value with the email of an authenticated user. We also store a timestamp value which is updated upon each authenticated request from the user (provided it's not too old).

When our app is deployed in TomEE (with play2war) within a VM, when the user hits endpoints two levels beneath the context ("/app") such as "/app/people/johnsmith", then the cookie stored has the path "/app/people", but we expect "/app". It seems as though Play is confused about the application context. We are setting application.context to "/app" in our application.conf.

As a result, sometimes cookies under "/app/people" are not cleared, and when the user returns to the "/app/people" page, the older cookie which has been left there is the one sent with the request (one with a timed-out timestamp), and this logs the user out.

Not sure if this is a framework bug or a misconfiguration on our part. Advice appreciated on how to further diagnose the problem or workaround. The only workaround I can think of is trying to create the cookies ourselves so we can set the path.

Seems potentially related to: https://github.com/playframework/Play20/pull/453

**Comment by dlecan** [comment]
> We do not experience this problem with "raw play"

Ok, that's probably a Play2war's bug.

> even when deployed in TomEE, unless TomEE is running within a VM.

I don't understand the difference. How can you run TomEE without a VM (JVM ??) ?

**Comment by jplehmann** [comment]
When running within TomEE on my workstation (OSX) in TomEE, I don't see the problem. But deployed (in a Centos 6.3 VM using OpenJDK) I do see the problem, with the same WAR. 

I don't know what difference the VM makes or if that is a red herring. Can you suggest any logging which would help track down the problem? At first we thought the difference was the Apache front-end until we tried hitting TomEE directly and saw the problem persist.

Thanks for your support Damien.

**Comment by dlecan** [comment]
Ok, to sum up, cookie handling is ...:
- On standard Play + OSX + Oracle JDK: OK
- On TomEE + Play2war + OSX + Oracle JDK: OK
- On TomEE + Play2war + CentOS + OpenJDK: KO

It will be hard for me to reproduce this issue.

> Can you suggest any logging which would help track down the problem?

Unfortunately, in Play code, logging is only used to output errors ...
You can lower the "play" logger to "trace" level, in order to see headers dump (including cookie details).

Can you provide a test case which isolates this issue ?

**Comment by dlecan** [comment]
Can you provide a test case which isolates this issue ?

**Comment by jplehmann** [comment]
Hi Damien,

I hadn't forgotten about this issue... in fact we are going to have to solve it within the next three weeks one way or the other before our product launch.  However, it may be very difficult to provide an isolated example. I will talk to the others and see what we can do.

Regarding logging, I didn't mean pre-existing logging, but I meant are there any logging messages I could add -- ie. to check for certain conditions, which might be helpful?  Perhaps our environment is not configured correctly.

John

**Comment by jplehmann** [comment]
We examined the HTTP traffic with Wireshark and discovered that in the broken scenarios, the cookie path is being wrapped with double-quotes.  And apparently this is not valid and some browsers will reject the path and then take the current request path as the cookie path.  This is the exact behavior we see in Chrome and Firefox, but Safari seems more tolerant.

We are currently investigating whose doing the quoting. It may be the Apache front-end.

"I don't think the other browsers treat " as a special character here.  What's going on is that Firefox isn't rejecting bogus Path attributes.  The new spec says to ignore path attributes that don't start with a / character.  That will cause the cookie to get the default path, which will probably fix the site if it works in other browsers." ---
https://bugzilla.mozilla.org/show_bug.cgi?id=610218

**Comment by jplehmann** [comment]
The root cause of the problem was our Tomcat server hardening. We used

```
    -Dorg.apache.catalina.STRICT_SERVLET_COMPLIANCE=true 
```

when we run the server on a vm which causes the server to quote the path names. To get around this, we are now setting: 

```
    -Dorg.apache.tomcat.util.http.ServerCookie.FWD_SLASH_IS_SEPARATOR=false 
```

as well.

A short write up of configuration parameters is at:  http://tomcat.apache.org/tomcat-7.0-doc/config/systemprops.html

Someone else is bound to run into this problem eventually, and I hope this helps them. :)

**Comment by dlecan** [comment]
Thank you for theses explanations.
