### ISSUE TITLE
Exclude some jars from war

### ISSUE THREAD

**Issue by yanns** [play2war/play2-war-plugin#159]
It should be possible to mark a jar not to be included in the war.

For the moment, it is already possible to make the jar as "provided" and it is not included in the war.

But it is not the solution for the following scenario:
- a jar is provided by tomcat in the general lib
- this jar is needed by play (start or stage)
- this jar should not be in the war, as the classloader would find the jar 2 times: one time in the war, and one time in the tomcat libs

Marking the jar as "provided" exclude it from play start or stage, where it is sill needed.

**Comment by dlecan** [comment]
Ok, I understand the use case.

This could be done by using a new Key setting, which describes a `Seq[(groupId: String, artifactId: String)]` of dependencies to exclude from the WAR.

Would it be enough to solve this request ?

**Comment by yanns** [comment]
Yes, it would be enough.
Thanks!

2013/5/15 Damien Lecan notifications@github.com

**Comment by dlecan** [comment]
Do you need a transitive mecanism ? (much harder !)

**Comment by yanns** [comment]
Transitive would be perfect yes :)
But I understand it is much harder.

A non-transitive solution would be ok for us.
I'd exclude the dependency from the transitive ones and add it explicitly.

2013/5/15 Damien Lecan notifications@github.com

**Comment by dlecan** [comment]
Documentation: https://github.com/dlecan/play2-war-plugin/wiki/Play2War-configuration#artifacts-to-filter-from-war

**Comment by yanns** [comment]
Thanks!

2013/5/30 Damien Lecan notifications@github.com
