### ISSUE TITLE
[Tomcat6] Blank page under cygwin

### ISSUE THREAD

**Issue by harid** [play2war/play2-war-plugin#160]
I am trying to get the HelloWorld sample app shipped with Play 2.1 to build as a WAR file.

When I deploy the WAR file in Tomcat and navigate to localhost:8080/hw/, I get a blank page.

Some info:

```
.../java/helloworld>catalina.sh version
Using CATALINA_BASE:   C:\apache-tomcat-6.0.26
Using CATALINA_HOME:   C:\apache-tomcat-6.0.26
Using CATALINA_TMPDIR: C:\apache-tomcat-6.0.26\temp
Using JRE_HOME:        C:\Program Files\Java\jre6
Using CLASSPATH:       C:\apache-tomcat-6.0.26\bin\bootstrap.jar
Server version: Apache Tomcat/6.0.26
Server built:   March 9 2010 1805
Server number:  6.0.26.0
OS Name:        Windows 7
OS Version:     6.1
Architecture:   x86
JVM Version:    1.6.0_37-b06
JVM Vendor:     Sun Microsystems Inc.
```

I set application.context=/hw/ in application.conf

``` scala
Build.scala:
import sbt._
import Keys._
import play.Project._
import com.github.play2war.plugin._

object ApplicationBuild extends Build {

    val appName         = "hw"
    val appVersion      = "1.0"

    val appDependencies = Seq(
      javaCore
    )

    val main = play.Project(appName, appVersion, appDependencies).settings(Play2
WarPlugin.play2WarSettings:_*)
.settings(
      // Add your own project settings here
        Play2WarKeys.servletVersion := "2.5"
    )

}
```

**Comment by harid** [comment]
Hi,

Can someone comment on what could be the issue here please?

Thanks,
-hari

**Comment by dlecan** [comment]
What is the version of Play2War ?
Any exceptions in logs ? (this needs to configure a `logger.xml` file as described in documentation).

**Comment by harid** [comment]
This is play2war 0.9:

``` scala
// Use the Play sbt plugin for Play projects
addSbtPlugin("play" % "sbt-plugin" % Option(System.getProperty("play.version")).
getOrElse("2.0"))

addSbtPlugin("com.github.play2war" % "play2-war-plugin" % "0.9")
```

---

I do have a logger.xml as in the documentation:

``` xml
<configuration>

  <conversionRule conversionWord="coloredLevel" converterClass="play.api.Logger$
ColoredLevel" />

  <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
    <encoder>
      <pattern>%date - [%level] - from %logger in %thread %n%message%n%xExceptio
n%n</pattern>
    </encoder>
  </appender>

  <logger name="play" level="INFO" />
  <logger name="application" level="INFO" />

  <!-- Off these ones as they are annoying, and anyway we manage configuration o
urself -->
  <logger name="com.avaje.ebean.config.PropertyMapLoader" level="OFF" />
  <logger name="com.avaje.ebeaninternal.server.core.XmlConfigLoader" level="OFF"
 />
  <logger name="com.avaje.ebeaninternal.server.lib.BackgroundThread" level="OFF"
 />

  <root level="INFO">
    <appender-ref ref="STDOUT" />
  </root>

</configuration>
```

---

I don't see any errors in tomcat logs. This is localhost.<date>.log

```
May 20, 2013 1:56:59 PM org.apache.catalina.core.ApplicationContext log
INFO: PlayServletWrapper > contextInitialized
May 20, 2013 1:57:07 PM org.apache.catalina.core.ApplicationContext log
INFO: PlayServletWrapper > contextInitialized
May 20, 2013 1:57:09 PM org.apache.catalina.core.ApplicationContext log
INFO: ContextListener: contextInitialized()
May 20, 2013 1:57:09 PM org.apache.catalina.core.ApplicationContext log
INFO: SessionListener: contextInitialized()
May 20, 2013 2:22:12 PM org.apache.catalina.core.ApplicationContext log
INFO: PlayServletWrapper > destroy
May 20, 2013 2:22:13 PM org.apache.catalina.core.ApplicationContext log
INFO: Play server stopped
May 20, 2013 2:22:13 PM org.apache.catalina.core.ApplicationContext log
INFO: PlayServletWrapper > contextDestroyed
May 20, 2013 2:22:17 PM org.apache.catalina.core.ApplicationContext log
INFO: PlayServletWrapper > contextInitialized
May 20, 2013 2:37:11 PM org.apache.catalina.core.ApplicationContext log
INFO: PlayServletWrapper > destroy
May 20, 2013 2:37:12 PM org.apache.catalina.core.ApplicationContext log
INFO: Play server stopped
May 20, 2013 2:37:12 PM org.apache.catalina.core.ApplicationContext log
INFO: PlayServletWrapper > contextDestroyed
May 20, 2013 2:37:14 PM org.apache.catalina.core.ApplicationContext log
INFO: PlayServletWrapper > contextInitialized
~
```

---

I do see some errors like the below in catalina.<date>.log while (re)deploying hw.war:

```
SEVERE: A web application created a ThreadLocal with key of type [null] (value [
akka.actor.ActorCell$$anon$1@fac25c]) and a value of type [scala.collection.immu
table.Nil$] (value [List()]) but failed to remove it when the web application wa
s stopped. To prevent a memory leak, the ThreadLocal has been forcibly removed.
May 20, 2013 2:37:13 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deploying web application archive hw.war
```

---

In the tomcat console(tomcat running in foreground), I see:

```
SEVERE: A web application created a ThreadLocal with key of type [null] (value [
akka.actor.ActorCell$$anon$1@fac25c]) and a value of type [scala.collection.immu
table.Nil$] (value [List()]) but failed to remove it when the web application wa
s stopped. To prevent a memory leak, the ThreadLocal has been forcibly removed.
May 20, 2013 2:37:13 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deploying web application archive hw.war
[info] play - Application started (Prod)
```

---

The application.log is empty.

I did a rawcap and did notice an empty response going back:

```
GET /hw/ HTTP/1.1
Host: 192.168.1.15:8080
User-Agent: Mozilla/5.0 (Windows NT 6.1; rv:20.0) Gecko/20100101 Firefox/20.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Connection: keep-alive
Cache-Control: max-age=0
```

```
HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
Content-Length: 0
Date: Tue, 21 May 2013 03:22:16 GMT
```

---

Not sure what is going on. Appreciate some insight.

Thanks,
-hari

**Comment by dlecan** [comment]
> `addSbtPlugin("play" % "sbt-plugin" % Option(System.getProperty("play.version")).getOrElse("2.0"))`

Did you configure "play.version" system property ?
Otherwise, your application will be packaged with Play 2.0.

If you want ot use Play 2.1.1, you should configure like this:

``` scala
addSbtPlugin("play" % "sbt-plugin" % "2.1.1")
```

**Comment by harid** [comment]
I made that change as you have it above to use 2.1.1. It is unfortunate the variable is called "play.version" and is not defined by the Play framework. In any case, after that change, I still got the same blank page.

I did a "play clean-all" and things seem a little better in that I get some response atleast but the response is "Action not found"

When I navigate to http://localhost:8080/hw-1.0/, which is where tomcat is listening and the war is deployed, I get
"Action not found". Same for "http://localhost:8080/hw-1.0/hello/"

This is the generated web.xml:

``` xml
<?xml version="1.0" ?>
<web-app xmlns="http://java.sun.com/xml/ns/javaee"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-app_2_5.xsd"
        version="2.5">

  <display-name>Play! hw</display-name>

  <listener>
      <listener-class>play.core.server.servlet25.Play2Servlet</listener-class>
  </listener>

  <servlet>
    <servlet-name>play</servlet-name>
    <servlet-class>play.core.server.servlet25.Play2Servlet</servlet-class>
  </servlet>

  <servlet-mapping>
    <servlet-name>play</servlet-name>
    <url-pattern>/</url-pattern>
  </servlet-mapping>

</web-app>
```

---

Shouldn't there be a HelloWorld mapping in here? Or maybe the default Play servlet uses the routes file to route requests?

When I startup Play with "play run" in the same application directory, the app comes up at "http://localhost:9000", no issues(ofcourse this is running on Play's netty server but just proves the app installation itself is not messed up.)

Please advise. Not sure why I am getting the "action not found" message. I am evaluating Play to recommend for use in our company but the ability to run as a WAR is a key requirement.

As before there are no exceptions or errros in the tomcat or ~/.../application.log

Thanks,
-hari

**Comment by dlecan** [comment]
> When I navigate to http://localhost:8080/hw-1.0/, 
> which is where tomcat is listening and the war is deployed, I get
> "Action not found". Same for "http://localhost:8080/hw-1.0/hello/"

Great, Action not found is a Play response :)

`application.context` in `application.conf` should match `http://localhost:8080/hw-1.0` servlet context.

Is it better ?

**Comment by harid** [comment]
If I have "application.context" defined in application.conf, I get a blank page.

If I don't have "application.context" defined in application.conf, I get the play error("action not found")

Go figure! What is wrong here?

**Comment by dlecan** [comment]
Can you share your generated war ?

**Comment by harid** [comment]
Hi Damien,

Please downloaded my generated war from here:
https://dl.dropboxusercontent.com/u/14341561/hw.war

Appreciate your help. I am still getting blank page.

Thanks,
-hari

**Comment by dlecan** [comment]
Your war works perfectly, either on Tomcat 6.0.37 or 7.0.29 (The 'helloworld' application), on Windows XP, Oracle JDK (not JRE).

I just dropped the war into `webapps` then opened `http://localhost:8080/hw/`.

Something may be wrong with your app server.
In your first post, we have written ``...catalina.sh ...` (not `.bat`), but you are running Windows !

**Comment by harid** [comment]
I am running Cygwin on Windows. 

-hari

**Comment by dlecan** [comment]
Can you run Tomcat with `startup.bat` ?

**Comment by harid** [comment]
You are right, it does work perfectly when tomcat is stated using
startup.bat in a CMD window. I guess the real issue is then running under
cygwin. There are plenty of other wars we have that work flawlessly under
cygwin/tomcat.

-hari

**Comment by dlecan** [comment]
Ok, I understand.
I will try to reproduce this issue.

**Comment by dlecan** [comment]
I cannot reproduce this issue: updated Cygwin, Tomcat 6.0.29, [Play2War sample](https://play-war.ci.cloudbees.com/job/Play_2_War_Run_integration_tests_-_211_Play_runtime/ws/sample/servlet25/target/a-play2war-sample-servlet25-1.0-SNAPSHOT.war), under `/p2wsample/` application context.

```
$ ./catalina.sh version
Using CATALINA_BASE:   D:\Dev\Outils\tomcat-6.0.26
Using CATALINA_HOME:   D:\Dev\Outils\tomcat-6.0.26
Using CATALINA_TMPDIR: D:\Dev\Outils\tomcat-6.0.26\temp
Using JRE_HOME:        C:\Program Files\Java\jdk1.7.0_09
Using CLASSPATH:       D:\Dev\Outils\tomcat-6.0.26\bin\bootstrap.jar
Server version: Apache Tomcat/6.0.26
Server built:   March 9 2010 1805
Server number:  6.0.26.0
OS Name:        Windows XP
OS Version:     5.1
Architecture:   x86
JVM Version:    1.7.0_09-b05
JVM Vendor:     Oracle Corporation

```

It works as expected. Can you try with the same WAR file ?

**Comment by dlecan** [comment]
Feel free to reopen this issue if necessary.
