### ISSUE TITLE
Help on creating a WAR file for Play 2.1.1 application offline

### ISSUE THREAD

**Issue by SudhaNadchal** [play2war/play2-war-plugin#165]
Hi, 

I'm trying to deploy my Play 2.1.1 project on Tomcat 7 using WAR file. I followed the same steps specified under https://github.com/dlecan/play2-war-plugin except that I did nothing with the "play2-war-plugin-develop.zip" file. I could successfully deploy my application on tomcat and it is up and running. But I learnt that play application tries to download the plugins from online repositories :Maven, Typesafe and cloudbeen using the resolvers. So I have a concern If I have to create a WAR file when I'm working offline and have no access to download these files, is there a way to handle?.. I couldn't follow how to integrate the "play2-war-plugin-develop.zip"  with my Play 2.1.1 setup; incase it povides a solution to create a WAR file offline.
Could you please help me out.

**Comment by dlecan** [comment]
This "question" is not related to Play2War.
Let me answer it in the Play Google group: https://groups.google.com/forum/?fromgroups#!topic/play-framework/0wQlTUKIU-w
