### ISSUE TITLE
Use custom configuration files at runtime

### ISSUE THREAD

**Issue by myliu** [play2war/play2-war-plugin#168]
First of all, thanks for providing play2-war-plugin to the Play community!

Currently, I am able to build a war using the plugin, and deploy the application through Tomcat7.  When we deploy the Play application to different environment, we need to use different configuration files.  If we were running play as standalone server in production environment, we would do something like

```
start -Dconfig.resource=prod.conf
```

Reference:
http://www.playframework.com/documentation/2.1.1/ProductionConfiguration

It seems that play2-war-plugin only allows me to configure the runtime environment using application.conf.  

My question is that is it possible to use different configuration file at runtime?

**Comment by dlecan** [comment]
> My question is that is it possible to use different configuration file at runtime?

Yes !

> `start -Dconfig.resource=prod.conf`

`-Dconfig.resource=prod.conf` is a JVM configuration parameter :) So you can reuse it for your Tomcat environment.
You can [set `CATALINA-OPTS` or `JAVA-OPTS` with this configuration](www.wellho.net/mouth/2163_CATALINA-OPTS-v-JAVA-OPTS-What-is-the-difference-.html).

**Comment by benlwong** [comment]
First, thanks for providing this plugin.

Just some feedback.  In certain environment, it might not be possible to change JVM configuration parameter.  It would be nice to have play2war to copy and replace the application.conf with the appropriate one (or some other clever way).

For example, when we run:

```
play war env=prod
```

It will build the war and replace application.conf with prod.conf.

**Comment by dlecan** [comment]
@benlwong It would be better to do that with SBT.
For example, you could extend [default resources with new ones](http://stackoverflow.com/questions/7718850/sbt-task-to-copy-directory) on some conditions.
This should be transparent for Play2War (and compatible with Play2 build itself).

**Comment by SamJoan** [comment]
Hey, 

I agree with @benlwong, since -Dconfiguration.resource how Play Framework oficially recommends you to go around for deploying for several environments:

http://www.playframework.com/documentation/2.0.2/ProductionConfiguration

While I possibly can alter the opts, it's dodgy as to have to do it =)

It would be great to specify the configuration file to include. I.e. only add "prod.conf", renaming that to application.conf, which I gather is the default that play reads. 

How it is now is extremely uncomfortable.

_edit_ perhaps the SBT option is better, and just requires some docs, I'll have a look and contribute if I can

**Comment by dlecan** [comment]
@droope 

> just requires some docs, I'll have a look and contribute if I can

Any contribution is welcome !

**Comment by mebibou** [comment]
@droope I'm not familiar with SBT and would like to copy another configuration file while generating the WAR, did you manage to make it work? any help is appreciated :-)

**Comment by SamJoan** [comment]
no, not at all, abandoned the war plugin and went with `play dist` with different javaopts for each environment. 

you can't really do that twice with the same dist, so you have to copy the folder, into two folders.

quite ugly :P

**Comment by valdar** [comment]
@dlecan I'm interested in contributing for this feature and adding an osgi mainfest automatic generator.
Can you pleas pointing me in the right direction? 
May be some project development documentation; how to build and run test..
Thank you,
Andrea.

**Comment by yanns** [comment]
@valdar you can check the first steps on the Wiki: https://github.com/dlecan/play2-war-plugin/wiki/How-to-help

**Comment by valdar** [comment]
@yanns Exactly what I was looking for. I don't know why I hadn't found that page by myself. Thank you!
