### ISSUE TITLE
GAE support

### ISSUE THREAD

**Issue by raulraja** [play2war/play2-war-plugin#172]
Not sure if this a plugin or Play related issue but it seems like the generated exploded WAR's with Servlet 2.5 fail to run on GAE due to use of restricted classes...

2013-07-16 14:25:35.886 [s~play2-test/1.368832958670789026].<stderr>: Failed to instantiate [ch.qos.logback.classic.LoggerContext]
W 2013-07-16 14:25:35.969 [s~play2-test/1.368832958670789026].<stderr>: Reported exception:
C 2013-07-16 14:25:38.775 Uncaught exception from servlet java.lang.NoClassDefFoundError: java.util.logging.LogManager is a restricted class.

Is there any way to use this plugin to run a Play2x app on GAE?

Thanks!

**Comment by dlecan** [comment]
> Is there any way to use this plugin to run a Play2x app on GAE?

Unfortunately, Akka, which the most important part of Play 2.x, can't run on Google App Engine.

More details in this old topic:
https://groups.google.com/forum/#!topic/play-framework/MtWcaaBN14E
