### ISSUE TITLE
Play2WarKeys.filteredArtifacts does not work

### ISSUE THREAD

**Issue by ibusse** [play2war/play2-war-plugin#173]
```
Play2WarKeys.filteredArtifacts := Seq(("junit", "junit"))
```

Results in a war that does not contain  junit.junit-4.11.jar  but that now contains a  junit-4.11.jar  ,  so the organization is missing but the jar is still added to the war.

**Comment by dlecan** [comment]
Thank you for reporting your issue.

Can you provide a simple test case ?

**Comment by dlecan** [comment]
`Play2WarKeys.filteredArtifacts` doesn't seem to work a all !
It needs more tests.
