### ISSUE TITLE
Where does application.conf end up?

### ISSUE THREAD

**Issue by jtal** [play2war/play2-war-plugin#174]
Hello, I am new to play and just started trying to use play2-war plugin.

I'm wondering where application.conf ends up? It doesnt seem everything is inside the war.

Is there any way for me to change config without rebuilding the war?

**Comment by dlecan** [comment]
> I'm wondering where application.conf ends up?

`application.conf` file is packaged in `your_project_name_version.jar` located in `your_project_name_version.war!/WEB-INF/lib`.

> Is there any way for me to change config without rebuilding the war ?

Play2War supports all standard Play 2.x configuration overloading:
http://www.playframework.com/documentation/2.1.2/Configuration (See _Specifying an alternative configuration file_).

With Play2War 1.x, you can also package your project exploded in `YOUR_WAR!/WEB-INF/classes`. If your WAR is deployed exploded, you will be able to modify your `application.conf` easily.
