### ISSUE TITLE
application.conf contents visible

### ISSUE THREAD

**Issue by jtal** [play2war/play2-war-plugin#176]
I have database user/pass in my application.conf.

If, upon startup, I have incorrect db user or pass, there is, of course, an error.

Unfortunately, in the error it prints some lines from application.conf including the connection info, user, pass.

How do people deal with this?

Is it possible to move the config out of the war altogether?

Is it possible for someone to request and get a copy of my application.conf from the war that play2-war builds?

Thank you

**Comment by timscarborough** [comment]
I'm not certain about editing the .conf file that's in the war file, but it's possible to include another .conf file in the application.conf file that is part of your play app. I use that method in multiple deployments. I have an external .conf file in resources folder (I'm running my wars in Jetty), but I believe it just needs to be in the classpath.

**Comment by dlecan** [comment]
> Unfortunately, in the error it prints some lines from application.conf including the connection info, user, pass.

You should ask Play2 developers.

> Is it possible to move the config out of the war altogether?

Play2War supports all standard Play 2.x configuration overloading:
http://www.playframework.com/documentation/2.1.2/Configuration (See _Specifying an alternative configuration file_).

> Is it possible for someone to request and get a copy of my application.conf from the war that play2-war builds?

This is a Play2 feature: only resources located in `public` folder can be downloaded.
