### ISSUE TITLE
P2W 0.8.1 + Play 2.0.6 hangs all requests 

### ISSUE THREAD

**Issue by edonato** [play2war/play2-war-plugin#177]
I know play 2.0.6 is a very recent release but it seems it's not working with P2W 0.8.1.  When I used P2W 0.8.1 + Play 2.0.4 + Tomcat 7.0.28 everything worked fine, however when I upgraded to Play 2.0.6, every HTTP request, even the simplest ones started to hang indefinitely.

I set log level to trace and the last record logged is:

```
2013-08-06 21:21:01,430 - [TRACE] - from play in play-akka.actor.promises-dispatcher-5 Invoking action with request: GET /
```

Can this be analyzed?

Thanks
Esteban

**Comment by dlecan** [comment]
Confirmed, something is wrong since Play 2.0.5.

**Comment by edonato** [comment]
great!!  Thanks for the super fast patch.  Do you know when 0.8.2 will be ready to be use?  Just to plan my upgrade to 2.0.6 and protect against the session injection vulnerability.

Thanks
Esteban

**Comment by dlecan** [comment]
Fix validated, all integration tests are ok: 
https://play-war.ci.cloudbees.com/job/Play_2_War_Run_integration_tests_-_Play_20x/5/testReport/

I will release v0.8.2 in the next hours (it will be announced here).

**Comment by edonato** [comment]
awesome!  Looking forward to hearing the announcement.  Thanks so much

**Comment by dlecan** [comment]
Play2War v0.8.2 has been published.

**Comment by edonato** [comment]
Thank you.  I will download it right away and let you know if I find any issue.
