### ISSUE TITLE
Streaming download from WS client does not work

### ISSUE THREAD

**Issue by yanns** [play2war/play2-war-plugin#178]
When I deploy the following application as WAR on tomcat 7:
https://github.com/yanns/streamapp

the following streaming URI does not work: /stream/stream3.

The controller for it:

``` scala
 def streamFromWS = Action { request =>

    val resultPromise = Promise[Result]

    val consumer = { rs: ResponseHeaders =>
      val (wsConsumer, stream) = joined[Array[Byte]]
      val contentLength = rs.headers.get("Content-Length").map(_.head).get
      val contentType = rs.headers.get("Content-Type").map(_.head).getOrElse("binary/octet-stream")
      resultPromise.success(
        SimpleResult(
          header = ResponseHeader(
            status = OK,
            headers = Map(
              CONTENT_LENGTH -> contentLength,
              CONTENT_DISPOSITION -> s"""attachment; filename="play-2.1.3.zip"""",
              CONTENT_TYPE -> contentType
            )),
          body = stream
        ))
      wsConsumer
    }

    WS.url("http://downloads.typesafe.com/play/2.1.3/play-2.1.3.zip").get(consumer).map(_.run)

    Async(resultPromise.future)
  }
```

Started with netty, the streaming works.

**Comment by dlecan** [comment]
Interesting use case.
Your Play instance acts as a kind of reverse proxy, doesn't it ?

> the following streaming URI does not work

Tomcat hangs or do you have an error message ?

**Comment by yanns** [comment]
> Your Play instance acts as a kind of reverse proxy, doesn't it ?

yes

> Tomcat hangs or do you have an error message ?

it hangs

**Comment by dlecan** [comment]
> > Tomcat hangs or do you have an error message ?
> 
> it hangs

Only /stream3, not /stream or /stream2 ?

**Comment by yanns** [comment]
2013/8/22 Damien Lercan notifications@github.com

>  Tomcat hangs or do you have an error message ?
> 
> it hangs
> 
> Only /stream3, not /stream or /stream2 ?
> 
> Yes, only /stream3
> /stream and /stream2 work. I wrote them to try to find the cause of the
> problem.
> But I'm stuck now.
> If you have other ideas to check, let me now, and I can update the
> application.

**Comment by dlecan** [comment]
I will try your test case and reproduce your issue.

**Comment by dlecan** [comment]
Ok, I can reproduce your issue with your test case. Tomcat hangs after ~20Mbs of download.
But I'm worried because I do not have any clue to understand what doesn't work!
No thread dead lock, nothing I can find in JVM to understand what's wrong.

It just stops downloading... Hey, interesting idea. Download could be stopped by something with an hidden exception and the HTTP communication would stay open.
It seems to hang, but in fact that could be a failure (stop download) + a bug (exception not catched, and so HTTP connection not closed).

It needs more investigations.

**Comment by dlecan** [comment]
I tryed with your test case, upgraded to Play 2.2.
Bad news, `/stream3` hangs with Netty too (Ubuntu + OpenJDK 1.7.0_51 64 bits). So I didn't try with Tomcat.

Can you try too ?

**Comment by dlecan** [comment]
@yanns can you try with a pure Play 2.2.x projet ? (see my pull request)

**Comment by yanns** [comment]
@dlecan thanks for your pull request!

Your experience is very confusing, because the /stream3 is working on my machine, and I have the same configuration as you (Ubuntu + OpenJDK 1.7.0_51 64 bits).

I tried it with tomcat, and it is working as well.
It is at the same time good news (it is now working with netty and tomcat) and bad news (why do you experience something different?)

If you can, you could double check on your machine.
Otherwise, as far as I'm concerned, you can now close this issue.

**Comment by yanns** [comment]
closing this issue, it works now
