### ISSUE TITLE
Logging File Specified in logger.xml Ignored

### ISSUE THREAD

**Issue by benlwong** [play2war/play2-war-plugin#179]
I followed the instructions to add a logger.xml file in the conf directory.  I provided the following condition:

```
  <if condition='isDefined("CATALINA_HOME")'>
      <then>
         <property name="LOG_FILE" value="${CATALINA_HOME}/logs/portal.log"/>
      </then>
      <else>
         <property name="LOG_FILE" value="logs/portal.log"/>
      </else>
   </if>
```

When I am running it as a standalone Play app (via IntelliJ IDEA), it is writing it to the proper directory (logs/portal.log).  But when I deployed it as a war file to the TOMCAT server using the plugin, the portal.log file is nowhere to be found. It is still logging to the    $USER_HOME/logs/ directory.  I am using Play 2.1.1.

**Comment by dlecan** [comment]
Does it work with Play2 itself ? (with another environment variable)

**Comment by benlwong** [comment]
Not sure exactly what you are asking, but if you meant does it work when I simply do the following (from the command line):

```
play run
```

The answer is yes.  Here is the output that shows that the logger.xml file is being picked up:

```
09:41:00,564 |-INFO in ch.qos.logback.core.joran.action.ConversionRuleAction - registering conversion word coloredLevel with class [play.api.Logger$ColoredLevel]
09:41:00,805 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
09:41:00,806 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FILE]
09:41:00,824 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - No compression will be used
09:41:00,825 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - Will use the pattern portal.%d{yyyy-MM-dd}.log for the active file
09:41:00,829 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - The date pattern is 'yyyy-MM-dd' from file name pattern 'portal.%d{yyyy-MM-dd}.log'.
09:41:00,829 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Roll-over at midnight.
09:41:00,833 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Setting initial period to Mon Aug 26 09:41:00 CDT 2013
09:41:00,834 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
09:41:00,835 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - Active log file name: logs/portal.log
09:41:00,835 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - File property is set to [logs/portal.log]
09:41:00,835 |-INFO in ch.qos.logbac
```

But when I run it with the war file in a Tomcat server, it doesn't look like the logger.xml file is being used at all.  I even tried the war file on a new Tomcat installation (7.0.42) and got the same results.

If it is using logger.xml, then it should at least log to logs/portal.log somewhere.  But I couldn't find any such file, and it continues to log to $USER_HOME/logs/application.log (not portal.log).

**Comment by dlecan** [comment]
What's the name of your project ?

**Comment by benlwong** [comment]
The name of the project is portal.  However, it was play2sample for a long time until I changed it a few days ago.  I made sure all references to play2sample was changed.  The target name is also portal.

```
.settings(Play2WarKeys.targetName := Some("portal")
```

**Comment by dlecan** [comment]
Tomcat loads resources (jars) in alphabetical order. So I suspect that `logger.xml` in play_.jar file is found before your one in portal_.jar.

For testing purpose, can you rename your project with a name _before_ "play" ? (petal, mum, a_portal, ...)

**Comment by benlwong** [comment]
Yep, that's the problem.  I renamed the project to "badboy" and its logger.xml is loading.  So what's the best way to resolve this issue short of changing the name of the war/jar file?

**Comment by dlecan** [comment]
You can try to package your application in WEB-INF/classes in your WAR thanks to this configuration key: https://github.com/dlecan/play2-war-plugin/wiki/Play2War-configuration#exploded-mode-for-main-projects-artifact

**Comment by dlecan** [comment]
Any news ?

**Comment by benlwong** [comment]
Sorry, been distracted with other stuff.  But I am definitely going to 
test it and hopefully report back by tomorrow.

Thanks for all your help,
Ben

**Comment by benlwong** [comment]
Yeah, I can confirm with the exploded settings, Tomcat is picking up my logging.xml ahead of the Play version.  Everything appears to work as expected.  Thanks so much for all your help!
