### ISSUE TITLE
Running sample application in play2-war-plugin

### ISSUE THREAD

**Issue by andreaturli** [play2war/play2-war-plugin#18]
Cannot run play war in the sample application created to test this project.

Here the stacktrace:

sample andrea$ play war
[info] Loading project definition from /Users/andrea/workspaces/andrea/play2-war-plugin/sample/project
[warn]  module not found: com.github.play2war#play2-war-plugin;0.2-SNAPSHOT
[warn] ==== typesafe-ivy-releases: tried
[warn]   http://repo.typesafe.com/typesafe/ivy-releases/com.github.play2war/play2-war-plugin/scala_2.9.1/sbt_0.11.2/0.2-SNAPSHOT/ivys/ivy.xml
[warn] ==== local: tried
[warn]   /Users/andrea/workspaces/andrea/play-2.0/framework/../repository/local/com.github.play2war/play2-war-plugin/scala_2.9.1/sbt_0.11.2/0.2-SNAPSHOT/ivys/ivy.xml
[warn] ==== Typesafe repository: tried
[warn]   http://repo.typesafe.com/typesafe/releases/com/github/play2war/play2-war-plugin_2.9.1_0.11.2/0.2-SNAPSHOT/play2-war-plugin-0.2-SNAPSHOT.pom
[warn] ==== Local Repository: tried
[warn]   /Users/andrea/.ivy2/local/com.github.play2war/play2-war-plugin/scala_2.9.1/sbt_0.11.2/0.2-SNAPSHOT/ivys/ivy.xml
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/com/github/play2war/play2-war-plugin_2.9.1_0.11.2/0.2-SNAPSHOT/play2-war-plugin-0.2-SNAPSHOT.pom
[warn] ==== Scala-Tools Maven2 Repository: tried
[warn]   http://scala-tools.org/repo-releases/com/github/play2war/play2-war-plugin_2.9.1_0.11.2/0.2-SNAPSHOT/play2-war-plugin-0.2-SNAPSHOT.pom
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.github.play2war#play2-war-plugin;0.2-SNAPSHOT: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]      com.github.play2war:play2-war-plugin:0.2-SNAPSHOT (sbtVersion=0.11.2, scalaVersion=2.9.1)
[warn] 
[error] {file:/Users/andrea/workspaces/andrea/play2-war-plugin/sample/project/}default-43653f/*:update: sbt.ResolveException: unresolved dependency: com.github.play2war#play2-war-plugin;0.2-SNAPSHOT: not found

Any idea?

**Comment by dlecan** [comment]
How did you configure Play2war repositories? In project/Build.scala AND in
project/build.sbt.
Le 14 avr. 2012 17:11, "Andrea Turli" <
reply@reply.github.com>
a écrit :

**Comment by andreaturli** [comment]
I'm using this project files
https://github.com/dlecan/play2-war-plugin/tree/develop/sample/project

Is there any other files/repo I've to configure on my machine?

Thanks

**Comment by dlecan** [comment]
I added mssing external repo. Thanks for reporting this.

**Comment by andreaturli** [comment]
Now it's ok. Thanks
