### ISSUE TITLE
Filtered Artifacts Setting Doesn't Correctly Filter

### ISSUE THREAD

**Issue by keithblaha** [play2war/play2-war-plugin#180]
Hi, I'm using Play 2.1.1 and Play2War 1.0 but am having some trouble filtering an artifact from the generated war. I have these settings added to my project:

``` scala
Play2WarPlugin.play2WarSettings ++
addArtifact(
  (moduleName apply { n => Artifact(n, "war", "war", None, List(Runtime), None) }),
  (deliver map { d => d })
).settings ++
Seq(
  Play2WarKeys.servletVersion := "3.0",
  Play2WarKeys.war <<= Play2WarKeys.war dependsOn(packageBin in Compile, deliver),
  Play2WarKeys.war <<= publishWarTask // this is just a task that renames the war file
)
```

However, when I explode the generated war I see these two jars in it:

```
com.typesafe.akka.akka-actor_2.10-2.1.0.jar
com.typesafe.akka.akka-actor-2.0.1.jar
```

The problem is that there's a name conflict coming from akka-actor-2.0.1 which is overwriting the ConfigFactory class from com.typesafe.config and crashing tomcat when the Play conf file cannot be correctly read. Deleting the akka-actor-2.0.1 jar from the exploded war made the app run correctly, so I set about trying to filter it out:

``` scala
Play2WarKeys.filteredArtifacts += ("com.typesafe.akka", "akka-actor")
```

I anticipated that this would remove both artifacts, however when I generated the war I now saw:

```
com.typesafe.akka.akka-actor_2.10-2.1.0.jar
akka-actor.jar
```

Where `akka-actor.jar` is the exact same jar as `com.typesafe.akka.akka-actor-2.0.1.jar` from above... so I tried something like this:

``` scala
Play2WarKeys.filteredArtifacts ++=
  Seq(
    ("com.typesafe.akka", "akka-actor"),
    ("akka-actor", ""),
    ("", "akka-actor"),
    ("akka", "actor")
  )
```

But no combination seems to filter out `akka-actor.jar` from the war. Is there a way to filter this bad jar out?

**Comment by keithblaha** [comment]
So I just noticed this: https://github.com/dlecan/play2-war-plugin/issues/173

Is there a planned release with this fix?

**Comment by dlecan** [comment]
> Is there a planned release with this fix?

Play2War 1.0.1, as planned in #173.
Until now, this is the only issue planned for this milestone.
Do you need a quick release ?

**Comment by keithblaha** [comment]
A quicker release would be much appreciated, right now it's a manual
process to fix the war

**Comment by dlecan** [comment]
I will release Play2War 1.0.1 this week-end.
