### ISSUE TITLE
logback+Tomcat7+play2.1.3 using play2war plugin using 1.0 version

### ISSUE THREAD

**Issue by SagarPhanse** [play2war/play2-war-plugin#182]
Hi, 
I am using play2war plaugin on my play 2.1.3 application and deploying it to Tomcat7.
I have my logging configuration in logger.xml as below

``` xml
    <appender name="FILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <file>../logs/my_play_app.log</file> 
        <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
            <!-- daily rollover -->
            <fileNamePattern>logFile.%d{yyyy-MM-dd}.log</fileNamePattern>
            <!-- keep 1 days' worth of history -->
            <maxHistory>7</maxHistory>
        </rollingPolicy>
        <encoder>
            <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} %X{id1} %X{id2} %X{id3} %X{id4}- %msg%n</pattern>
        </encoder>
    </appender>



    <root level="INFO" additivity="false">
        <appender-ref ref="FILE"/>

    </root>

    <logger name="application" level="INFO" additivity="false">
        <appender-ref ref="FILE"/>
       </logger>

    <logger name="play" level="INFO" additivity="false">
        <appender-ref ref="FILE"/>
    </logger>
```

in application.conf, I have commented three lines, 

```
#logger.root
#logger.application
#logger.play
```

And that is it, 

```
When server starts the war explodes, and says..
INFO: Deploying web application archive C:\user\local\workspace\installed\apache-tomcat-7.0.29\webapps\myplayapp.war
Sep 11, 2013 4:01:02 PM org.apache.catalina.core.ApplicationContext log
INFO: PlayServletWrapper > contextInitialized
"Play logs now directly handled by this application server"
```

And then there is nothing generated, how do I make it create those logs?

Functionality is working fine, it is just that it is not producing any logs.

Can you please shed some light on this, I am really struggling to survive without logs being written.

Also when I run it using the local out-of-the-box play development environment, logs are produced fine. It is only when I make a war and deploy it to tomcat, the logs are disappearing.

-Regards
Sagar

**Comment by dlecan** [comment]
> Play logs now directly handled by this application server

This log statement indicates that you have enabled `"com.github.play2war.ext" %% "redirect-playlogger" % "1.0.1"` dependency.

It means that internal Play logger is disabled.
So all you application logs are handled by the log framework of your application server (Tomcat).

**Comment by SagarPhanse** [comment]
So what happens to my custom logback appenders in play's logger.xml? are they all ignored?
Will it induce the Tomcat's logging mechanism handle my logs?

**Comment by dlecan** [comment]
> Will it induce the Tomcat's logging mechanism handle my logs?

If you enable "redirect-playlogger" dependency, yes.
If you want to control logging with Play logger, remove this dependency.

**Comment by dlecan** [comment]
Any news ?

**Comment by SagarPhanse** [comment]
Hi, when I removed the dependency to the redirect-playlogger, I received an error at the Tomcat Server Start Up
as below,

```
INFO: PlayServletWrapper > contextInitialized
java.lang.ClassCircularityError: java/util/logging/LogRecord

    at org.slf4j.bridge.SLF4JBridgeHandler.getSLF4JLogger(SLF4JBridgeHandler.java:200)
    at org.slf4j.bridge.SLF4JBridgeHandler.publish(SLF4JBridgeHandler.java:289)
    at java.util.logging.Logger.log(Logger.java:522)
    at java.util.logging.Logger.doLog(Logger.java:543)
    at java.util.logging.Logger.logp(Logger.java:659)
    at org.apache.juli.logging.DirectJDKLog.log(DirectJDKLog.java:183)
    at org.apache.juli.logging.DirectJDKLog.debug(DirectJDKLog.java:106)
    at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:368)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:153)

    at org.apache.catalina.startup.Catalina.start(Catalina.java:675)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:322)
    at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:451)
```

Can you please check?

**Comment by dlecan** [comment]
> java.lang.ClassCircularityError: java/util/logging/LogRecord

So you need "redirect-playlogger" extension and logs have to be configured through application server logging system.

**Comment by dlecan** [comment]
Any news on this ?
