### ISSUE TITLE
Be compatible with Play 2.2

### ISSUE THREAD

**Issue by dlecan** [play2war/play2-war-plugin#188]
Play 2.2 is available.

Plugin and Servlets are totally broken by new Play APIs.
- [x] Upgrade SBT plugin
- [x] Use new Play 2.2 APIs
- [x] Multi-projects builds are broken
- [x] Flash cookies are not removed (9512e8a)
- [x] Chunked downloads on Jetty 8 / 9 don't work as excepted (97edd6f)

**Comment by jensjaeger** [comment]
Hi Dlecan,
any idea when 1.2 will be released? 
Thanks
Jens

**Comment by dlecan** [comment]
No. There is a lot of work to do, I need to analyze this precisely.

**Comment by jensjaeger** [comment]
Hey Damien,

thanks for your quick reply. Do you have any kind of forecast= Worst case, best case maybe. Just any information would help.

Just had a look into the code. But I was not sure where to start. I will try again tomorrow and give you some feedback if I got any further.

Thanks
Jens

**Comment by dlecan** [comment]
Most of the work is done in [`feature-#188-be-compatible-with-Play-2.2`](https://github.com/dlecan/play2-war-plugin/tree/feature-%23188-be-compatible-with-Play-2.2) branch.

SBT build has been upgraded, now it's time to convert Servlet classes to new Play APIs.

**Comment by dlecan** [comment]
Good news guys, we are not far from releasing a beta version of Play2War supporting Play 2.2 runtimes.
Still some bugs, but we need community feedbacks.

**Comment by marcosinigaglia** [comment]
Nice

**Comment by abhinav-maheshwari** [comment]
Thats great dlecan. Is it not possible to build at all to build war using Scala 2.10 / sbt 0.13 right now ? Would be awesome if you can also indicate when will the beta be released, I will act as beta tester.

**Comment by abhinav-maheshwari** [comment]
Rohit, my team mate and I have found out a clunky workaround that allows you to build a war file using play 2.2.x. Check it out here - http://play2war.blogspot.com

**Comment by kevinmeredith** [comment]
Hi @dlecan - could you please let me know when the official update (play2war supporting Play 2.2.x) will be released?

**Comment by dlecan** [comment]
?? Where is my comment ?
A beta version of Play2War for Play 2.2 is out for 9 days !
https://github.com/dlecan/play2-war-plugin/releases/tag/1.2-beta1

Really sorry

**Comment by kevinmeredith** [comment]
Thanks, @dlecan , for this library & your quick reply. 

After updating my build config to point to this local plugin, are the instructions the same as configuring play2war for Play 2.1.x?

**Comment by dlecan** [comment]
@kman007us same instructions, same configuration, except Play2war version

**Comment by kevinmeredith** [comment]
Pardon my SBT ignorance, but, do I need to simply switch my play_app/project/plugins.sbt from:

`addSbtPlugin("com.github.play2war" % "play2-war-plugin" % "1.0")`

to 

`addSbtPlugin("com.github.play2war" % "play2-war-plugin" % "1.2-beta1")` ?

That's the name of the unzipped folder, "play2-war-plugin-1.2-beta1"

**Comment by yanns** [comment]
Yes.

You can check the sample in github:
https://github.com/dlecan/play2-war-plugin/blob/00f3204b8796d943e311c6e1f6822d9eae9cbe39/sample/project/plugins.sbt#L17

**Comment by dlecan** [comment]
Play2War 1.2-beta2 will be released in the next days. Thanks to @yanns, all known issues are fixed!

**Comment by viniciusmichelutti** [comment]
Guys, sorry for the ignorance, but how can i configure it in 2.2.1? Do I still needs to create a Build.scala file?

**Comment by yanns** [comment]
you can use the Build.scala as usual.

If you are using the new build.sbt file, here is an example:

``` scala
import com.github.play2war.plugin._

name := "testwar"

version := "1.0-SNAPSHOT"

play.Project.playScalaSettings

Play2WarPlugin.play2WarSettings

Play2WarKeys.servletVersion := "3.0"
```

I hope it helps.

We should extend the documentation for this new configuration.

**Comment by jensjaeger** [comment]
Is the Play2War 1.2-beta2 already released?

Thanks 
Jens

**Comment by dlecan** [comment]
> Is the Play2War 1.2-beta2 already released?

Yes it is.
But you may encounter some warnings when downloading the SBT plugin because its deployment has failed partially.
Just ignore them, this will be fixed for next release.

**Comment by dlecan** [comment]
Upgrade to Play 2.2 is done in 1.2-beta2
