### ISSUE TITLE
Unmanaged dependencies are not included in the WAR

### ISSUE THREAD

**Issue by He-Pin** [play2war/play2-war-plugin#189]
Hi,thanks for your great work
If I have an dependency jar in /lib then when I run play war
the jar file is not include in the built war.
which means that there is no jar which i put in the /lib in the 
/WEB-INF/lib

**Comment by He-Pin** [comment]
fixd via
Embed custom WAR configuration files in WIKI
but i think your may provide an better way

**Comment by dlecan** [comment]
That's a regression introduced by fix for #173.

**Comment by He-Pin** [comment]
thanks
I just add the file duplicated just as your wiki says

**Comment by dlecan** [comment]
Don't close this issue, it's not fixed :)

**Comment by dlecan** [comment]
Which version of Play2War are you using ?

**Comment by He-Pin** [comment]
version 1.1

**Comment by dlecan** [comment]
Ok, I will release Play2War v1.1.1 which fixes this issue.

**Comment by He-Pin** [comment]
I will test it now

**Comment by He-Pin** [comment]
:: com.github.play2war#play2-war-plugin;1.1.1: not found
@dlecan

**Comment by dlecan** [comment]
@hepin1989 no released yet

**Comment by dlecan** [comment]
Play2War 1.1.1 has been released !

**Comment by He-Pin** [comment]
thanks I will take it a try

何品
