### ISSUE TITLE
What does it take to get a War from Play 2.1.1 for deployment into Glassfish 4?

### ISSUE THREAD

**Issue by Yoztastic** [play2war/play2-war-plugin#192]
After using this plugin I am unable to run the Play app in Glassfish 4.

See: http://stackoverflow.com/questions/19096352/

**Comment by dlecan** [comment]
Probably the same issue as #181.
Can you check your log files ?

**Comment by Yoztastic** [comment]
Sorry I thought I had replied. The log file contained nothing at all. It is
not negotiating the route hence the 404.

There is some significant step that I am not doing but I cant find any
documentation.

One thing maybe

I have a routes file under conf in the play application which does its job
fine in stand alone mode.

But there is nothing in the config file for router.

Could this be related do you look at this config. I don't see any
information what-so-ever in the war file generated that would tell
glassfish where to direct any routes

# Router

# ~~~~~

# Define the Router object to use for this application.

# This router will be looked up first when the application is starting up,

# so make sure this is the entry point.

# Furthermore, it's assumed your route file is named properly.

# So for an application router like `my.application.Router`,

# you may need to define a router file `conf/my.application.routes`.

# Default to Routes in the root package (and conf/routes)

# application.router=my.application.Routes

**Comment by cgrohowski** [comment]
Was this issue ever resolved?  I am having the same issue with a vendor-written application (so I don't have visibility into the source at the moment) with their deployment to glassfish v3.  Same file not found error, and it's looking for a class contained in one of the play jar files in the lib/ folder as if it was exploded into WEB-INF/classes.  Is there any fix for this?  This only happens in our Linux environment, it works fine locally on Windows / Mac GFv3 installations.

Thanks!

**Comment by Yoztastic** [comment]
No. We have placed another question relating to our attempts to get this
working with Glassfish.
https://github.com/dlecan/play2-war-plugin/issues/214
