### ISSUE TITLE
play2war doesn't call ShutdownManager.shutdown()

### ISSUE THREAD

**Issue by finklang** [play2war/play2-war-plugin#195]
We're seeing exceptions like those described in https://groups.google.com/forum/#!topic/ebean/ix5sOX68MsY
where due to timing issue ebean isn't getting shut down correctly - it looks like the solution is to add ShutdownManager.shutdown() to Servlet.destroy(), and from code inspection it doesn't look like play2war's servlet calls this.  

I'm not sure if just throwing the method call in there is the right solution or if there is a more elegant place to put the call.

Currently we're on play 2.1.5.

**Comment by dlecan** [comment]
Thank you for reporting this issue.
Do you think Play itself should call `ShutdownManager.shutdown()` ?

**Comment by finklang** [comment]
It could, but this problem only shows up when running inside a container (like tomcat), so maybe it best belongs here.

**Comment by yanns** [comment]
@finklang Do you know why this problem only occurs inside a container and not with Play standalone?

**Comment by finklang** [comment]
Perhaps play stop exits the VM but with a container the VM is still around so threads still stay around?

**Comment by yanns** [comment]
I did not find any documentation about this ShutdownManager.shutdown.
Is there any?

When we found out that this method should always be called, then we could add this in the default ebean play plugin.

**Comment by dlecan** [comment]
This is definitely a Play's issue, which needs to be fixed in Play itself.

@finklang Can you report a fix yourself in Play's EBean plugin or do you need help for this ?

**Comment by dlecan** [comment]
If you have more information, do not hesitate to reopen this issue.
