### ISSUE TITLE
Using SecurityContextHolderAwareRequestFilter in Play

### ISSUE THREAD

**Issue by wroblisko** [play2war/play2-war-plugin#206]
Hi! First of all I want to say you've done a great job with Play2War plugin :)! 
My problem is similar to problem mentioned by ckarle in https://github.com/dlecan/play2-war-plugin/issues/166.

I have exisiting main application deployed on Jboss 7 which uses Spring Security. We are developing another smaller app using play, which is deployed on production together with main app using Play2War plugin. 

However, for user authentication is responsible the main app. In our Play app, we just want to know, which user is logged in. We would like to have SecurityContext, which was created by Spring's SecurityContextHolderAwareRequestFilter, in our thread or just know user login name.

Due to the fact, that in Play2War for servlet 3.0, asynchronous request handling is used, we have no SecurityContext in our Play thread.

I see 2 possible solutions:
1) use Play2War for servlet 2.5, which handles request synchronously,
2) in Play2War plugin for servlet 3.0 save "somewhere" in request the information about logged-in user, to be able to read it in another thread.

First solution didn't work, and actually I don't know why, here is the stacktrace:

<pre>
java.lang.NullPointerException
play.core.server.servlet.Play2GenericServletRequestHandler$$anon$1.<init>(RequestHandler.scala:113)
play.core.server.servlet.Play2GenericServletRequestHandler.apply(RequestHandler.scala:112)
play.core.server.servlet.Play2WarServer$.handleRequest(Play2Server.scala:63)
play.core.server.servlet.GenericPlay2Servlet.service(Play2CommonServlet.scala:36)
com.mycompany.MyPlay2ServletSync.service(MyPlay2ServletSync.java:21)
javax.servlet.http.HttpServlet.service(HttpServlet.java:847)
com.mycompany.MyPlay2ServletSync.service(MyPlay2ServletSync.java:27)
</pre>

We are using Play 2.1.3, and play2war plugin 1.0.
Maybe you know why it is impossible to run Play2War for servlets 2.5 on Jboss 7 ?

2) solution - I tried to pass this information somehow, but still I dont know what method to overrride in Play2Servlet and where to put this information and how to read it:)

Thanks for any suggestions and clues!

**Comment by valdar** [comment]
Hi,
for the solution 1) have you try to use  Play2War plugin version 1.0.1?
May be that fix the NullPointerException problem.

Andrea.

**Comment by yanns** [comment]
in an asynchronous environment, you cannot use something like ThreadLocal variables to keep track of the logged-in user. I do not know how spring security context is build, but if it is using a ThreadLocal (what a lot of security framework do), it cannot be used with servlet 3.0.

You should try to write your own play filter (by re-using some parts of Spring's SecurityContextHolderAwareRequestFilter). In that way, you are totally independent from the servlet container.

**Comment by wroblisko** [comment]
@valdar Thanks for pointing it. I've tried 1.0.1 and NullPointerException has gone, but now the response comes totaly empty. Only think I see now is:

<pre>
ERROR [play] (http--0.0.0.0-8443-1) Play server as not been initialized. Due to a previous error ?
</pre>

Do I have to do something to start it working ? Am I missing something ?

@yanns Yes, your first part is exacly what I have written. Writing my own SecurityContextHolderAwareRequestFilter is useless until I have the same Session in both threads.

**Comment by yanns** [comment]
@wroblisko I do not understand your problem with "same session in both threads"

Did you write a servlet filter, or a play filter?

I meant the last one:
http://www.playframework.com/documentation/2.2.x/ScalaHttpFilters

As an alternative, you can write an play action wrapper:
http://www.playframework.com/documentation/2.2.x/JavaActionsComposition

**Comment by wroblisko** [comment]
@yanns Thanks for replying! I will do my best to clarify my problem!

Due to the fact that I'm still unable to use play2war for servlet 2.5, I'm still using play2war for servlet 3.0. This, as you have written, causes that Spring security mechanism which uses ThreadLocals doesn't work.

I would like to use play2war for sevlet 2.5 which would allow me to use ThreadLocal set by Spring. I have still problem with using this servlet in Jboss 7, as written above.

Using play2war for servlet 3.0, Play controllers are executed in different thread, than SpringFilter was. How should I write ScalaHttpFilter or Play Action, to be able to obtain JBoss HttpSession or SecurityContext from different thread ?

If You can't understand me or I'm missing something, please say so :) Thanks!

**Comment by valdar** [comment]
@wroblisko Have you configured Jboss 7 correctly because out of the box I think that it supports only servlet 3
(maybe deploing this jar: https://repository.jboss.org/nexus/content/repositories/releases/org/jboss/spec/javax/servlet/jboss-servlet-api_2.5_spec/1.0.0.Final/jboss-servlet-api_2.5_spec-1.0.0.Final.jar ?) and did you follow the instructions at https://github.com/dlecan/play2-war-plugin/wiki/Deployment#jboss-70x and https://github.com/dlecan/play2-war-plugin/wiki/ConfigurationSpecialEBeanJBoss7 (if the play project use ebean) ?

**Comment by wroblisko** [comment]
@valdar Thanks for replying!

Yes, Jboss is configured properly. In fact, that Play application have already been running on this Jboss, but we came to a moment when we needed SecurityContext or any other information about logged-in user.

About servlet 2.5, as far as I know, servlets 3.0 are fully compatible with servlet 2.5, so we don't need to add any new jar's to Jboss 7 to be able to use servlets 2.5.

As you have suggested, I've tried newer version of play2war plugin (1.0.1) with servlet 2.5 and it didn't throw NullPointerException, as version 1.0. Debugging application, I saw that the Play servlet was called properly, but no controllers are called afterwards, and response comes empty to the browser.. I've got problem attaching scala sources to see what is going on "deeper" in the play servlet..

Log message:

<pre>
ERROR [play] (http--0.0.0.0-8443-1) Play server as not been initialized. Due to a previous error ?
</pre>

indicates that I'm still missing something.. I see that this error message is logged by Play2WarServer, and this log is not present in play2war plugin in version 1.0. I wondering what was the difference between these versions.

Thanks for replying!

**Comment by dlecan** [comment]
@wroblisko Do you still have an issue ?

**Comment by wroblisko** [comment]
@dlecan We have made a workaround (for my primary problem) by passing certain information (about logged in user) in "smarter" Request object. Thus I didn't try to solve problem with uninitialized Play server..

**Comment by dlecan** [comment]
> ```
> ERROR [play] (http--0.0.0.0-8443-1) Play server as not been initialized. Due to a previous error ?
> ```

This message is raised for the same reason as the previous `NullPointerException`: your Play server is not started, but the servlet container itselft has started!
If an exception is thrown during Play server initialization, the servlet container start should fail too. So I don't understand.

Can you try with a later version of Play2War ? Can you report a separate issue for this?
Thank you.
