### ISSUE TITLE
Exploded WAR packaging not including "<project>/lib" folder

### ISSUE THREAD

**Issue by ghost** [play2war/play2-war-plugin#208]
Any solution other than adding the libs to the webapp in production? I noticed this after receiving a Scala "ThreadLocal" error when deploying to TOMCAT 7.

Using:
Play 2.1.1
play2-war-plugin 1.0.1
Oracle OJDBC jar

**Comment by dlecan** [comment]
See #189, it's a know bug of P2W v1.0.x, fixed in v1.1.1.
Unfortunately, this version is only compatible with Play 2.1.4+

Can you upgrade to Play 2.1.4+ ? (not Play 2.2.x)

**Comment by dlecan** [comment]
Will be included in 1.0.2 for Play 2.1.0 to 2.1.3

**Comment by dlecan** [comment]
Play2War v1.0.2 with a fix for this issue is out!
