### ISSUE TITLE
external setting for database

### ISSUE THREAD

**Issue by ghost** [play2war/play2-war-plugin#209]
Is there any way to set different value for db.default.url without rebuilding WAR?

The situation is that I have full control of my project, and I have to let other to test its pre-compiled WAR with Tomcat7. However, he only has Tomcat7 and I don't know his database configuration. I want just let him change its value by himself.

I know that I can put a web.xml into WAR but I don't know neither can web.xml override application.conf value nor proper web.xml key of that configuration.

**Comment by valdar** [comment]
You can use the JVM configuration parameter -Dconfig.file=/opt/conf/prod.conf to specify a different application.conf file (with different values of db.default.url).
You can set CATALINA-OPTS or JAVA-OPTS with this configuration parameter.

**Comment by ghost** [comment]
Thank you for your quick response!

Following your nice instruction, I found the information here:
http://www.playframework.com/documentation/2.2.x/Configuration
(However, this doc doesn't say I can put parameter at JAVA_OPTS or CATALINA_OPTS.)

In my case, this should work nicely, but it affects to all of servlets on same Tomcat, doesn't it?
