### ISSUE TITLE
Should be able to set cookie

### ISSUE THREAD

**Issue by antoineleclair** [play2war/play2-war-plugin#21]
I saw a `// TODO` around that place in the code. I just wanted to signify my interest in this feature since it's a show stopper for us.

I'm new to Scala/sbt and I was not able to set `play2-war-plugin` for local development. I would have tried to add the feature otherwise. If you have instructions for building and using the plugin without using the build repository, I might help.

**Comment by dlecan** [comment]
You're right, cookies are not handled. It's on the roadmap for next release, v0.3 (see issue #9).
See issue #22 for development on play2-war-plugin.

**Comment by antoineleclair** [comment]
Thanks!

**Comment by dlecan** [comment]
See https://github.com/dlecan/play2-war-plugin/wiki/How-to-help for instructions about how to develop with Play2War plugin.
