### ISSUE TITLE
Add a test to check if unmanaged dependencies are handled by the SBT plugin

### ISSUE THREAD

**Issue by dlecan** [play2war/play2-war-plugin#213]
An idea:
- Compile an empty custom class (eg.: ClassToCheckUnManagedDependencies)
- Put it in a jar file
- Put it in `common/lib`
- Load this class (or not) in the main controller of the sample
- or (better), add a simple rest service which responses ok/ko if the class is found in the classpath, then call this service from the integration tests

**Comment by yanns** [comment]
yes, it was my idea too.

Instead of having a custom class in a jar, we can put a text file and load it with Classloader.getResourceAsStream
