### ISSUE TITLE
Custom MANIFEST.MF in war/ subdirectory prevents build from completing

### ISSUE THREAD

**Issue by mdebusschere** [play2war/play2-war-plugin#216]
Using Play 2.2.0 and play2-war-plugin 1.2-beta2, building on Windows 7 & Java 7.

When adding custom file war/META-INF/MANIFEST.MF the following error is seen.

Build fails due to conflict
[trace] Stack trace suppressed: run last *:war for the full output.
error java.util.zip.ZipException: duplicate entry: META-INF/MANIFEST.MF

Notes: providing a custom web.xml files works with servlet 3.0.
When using lowercase filename manifest.mf, the WAR and ends up with
TWO manifest.mf files different case.

Reference https://github.com/dlecan/play2-war-plugin/pull/71

**Comment by dlecan** [comment]
Probably fixed by #215, but fix needs to be reported for 1.2.x series.

**Comment by dlecan** [comment]
Reported in commit 7510a3a

**Comment by dlecan** [comment]
Play2War v1.2-beta4 with a fix for this issue is out!

**Comment by dlecan** [comment]
Play2War 1.2 final has been released with a fix for this issue
Enjoy !
