### ISSUE TITLE
Play 2.2 - Duplicate jar in war

### ISSUE THREAD

**Issue by maxsilva** [play2war/play2-war-plugin#219]
Hi,

Play war is create two app jar in war /lib: a default.<'app_name'>.jar and <'app_name'>.jar.

For example:

app.war
  -- lib/default.app-1.0.jar
  -- lib/app-1.0.jar

Please, why this occurs?

I have used play2-war alpha2 version.

Thanks

**Comment by dlecan** [comment]
Duplicated by #205
