### ISSUE TITLE
How to get alpha4 binary version ?

### ISSUE THREAD

**Issue by maxsilva** [play2war/play2-war-plugin#220]
Please,

Is there a plugin alpha4 binary version (jars) in any repository?

Thanks

**Comment by dlecan** [comment]
1.2-beta4 is available in Maven Central and Sbt Plugin repository.

**Comment by maxsilva** [comment]
I don´t understand. Seems that is all ok but play doesn´t get download plugin:

Please, would you help?

```
[warn] ==== Sbt plugins repository: tried
[warn]   http://dl.bintray.com/sbt/sbt-plugin-releases/com.github.play2war/play2-war-plugin/scala_2.10/sbt_0.13/1.2-beta4/ivys/ivy.xml
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.github.play2war#play2-war-plugin;1.2-beta4: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]          com.github.play2war:play2-war-plugin:1.2-beta4 (sbtVersion=0.13, scalaVersion=2.10)
[warn]
sbt.ResolveException: unresolved dependency: com.github.play2war#play2-war-plugin;1.2-beta4: not found
```

**Comment by dlecan** [comment]
The link http://dl.bintray.com/sbt/sbt-plugin-releases/com.github.play2war/play2-war-plugin/scala_2.10/sbt_0.13/1.2-beta4/ivys/ivy.xml works perfectly for me.
May be you can try to enable debug logging in SBT (put `logLevel := Level.Debug` in `conf/plugins.conf` instead of `logLevel := Level.Warn`)

**Comment by maxsilva** [comment]
Ok, thank you. Maybe the corporation proxy is blocking that domain/url.

**Comment by dlecan** [comment]
If you have more information, do not hesitate to reopen this issue.
