### ISSUE TITLE
Play 2.2.1 - play2-war-plugin - 1.2-beta4 (not found)

### ISSUE THREAD

**Issue by feni8888** [play2war/play2-war-plugin#225]
```
[warn] Host repo.typesafe.com not found. url=http://repo.typesafe.com/typesafe/i
vy-releases/com.github.play2war/play2-war-plugin/scala_2.10/sbt_0.13/1.2-beta4/i
vys/ivy.xml
[warn] Host repo.scala-sbt.org not found. url=http://repo.scala-sbt.org/scalasbt
/sbt-plugin-releases/com.github.play2war/play2-war-plugin/scala_2.10/sbt_0.13/1.
2-beta4/ivys/ivy.xml
[warn] Host repo1.maven.org not found. url=http://repo1.maven.org/maven2/com/git
hub/play2war/play2-war-plugin_2.10_0.13/1.2-beta4/play2-war-plugin-1.2-beta4.pom

[warn]  module not found: com.github.play2war#play2-war-plugin;1.2-beta4
[warn] ==== typesafe-ivy-releases: tried
[warn]   http://repo.typesafe.com/typesafe/ivy-releases/com.github.play2war/play
2-war-plugin/scala_2.10/sbt_0.13/1.2-beta4/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   http://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.github.play2
war/play2-war-plugin/scala_2.10/sbt_0.13/1.2-beta4/ivys/ivy.xml
[warn] ==== local: tried
[warn]   C:\Working\apps\play-2.2.1\repository\local\com.github.play2war\play2-w
ar-plugin\scala_2.10\sbt_0.13\1.2-beta4\ivys\ivy.xml
[warn] ==== Maven2 Local: tried
[warn]   file:/C:/Users/nbkpwd1/.m2/repository/com/github/play2war/play2-war-plu
gin_2.10_0.13/1.2-beta4/play2-war-plugin-1.2-beta4.pom
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/com/github/play2war/play2-war-plugin_2.10
_0.13/1.2-beta4/play2-war-plugin-1.2-beta4.pom
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.github.play2war#play2-war-plugin;1.2-beta4: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
```

**Comment by feni8888** [comment]
added this in plugins.sbt, still same error:

resolvers += Resolver.url("sbt-plugin-releases",url("http://repo.scala-sbt.org/scalasbt/sbt-plugin-releases"))(Resolver.ivyStylePatterns)

**Comment by dlecan** [comment]
What about [http://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.github.play2war/play2-war-plugin/scala_2.10/sbt_0.13/1.2-beta4/ivys/ivy.xml](http://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.github.play2war/play2-war-plugin/scala_2.10/sbt_0.13/1.2-beta4/ivys/ivy.xml) in your browser ?

**Comment by feni8888** [comment]
I can open the link in my browser.

**Comment by feni8888** [comment]
do i need to modify my resolver in plugins.sbt?

this is the content of plugins.sbt

```
// Comment to get more information during initialization
logLevel := Level.Warn

// The Typesafe repository
resolvers += "Typesafe repository" at "http://repo.typesafe.com/typesafe/releases/"

// Use the Play sbt plugin for Play projects
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.2.1")

//resolvers += Resolver.url("Play2war plugins release",url("http://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/"))(Resolver.ivyStylePatterns)

resolvers += "Play2war plugins release" at "http://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/"

addSbtPlugin("com.github.play2war" % "play2-war-plugin" % "1.2-beta4")

```

**Comment by dlecan** [comment]
> do i need to modify my resolver in plugins.sbt?

Are you behind a proxy ?

**Comment by feni8888** [comment]
yes, but i don't see any error on proxy with logLevel := Level.Debug.
Also i can get to http://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.github.play2war/play2-war-plugin/scala_2.10/sbt_0.13/1.2-beta4/ivys/ivy.xml on my browser

**Comment by yanns** [comment]
Have you configured sbt to use your proxy:
http://stackoverflow.com/questions/13803459/how-to-use-sbt-from-behind-a-proxy
"Dhttp.proxyHost=yourserver -Dhttp.proxyPort=8080"?

**Comment by feni8888** [comment]
yes, still the same after configuring proxy.

**Comment by feni8888** [comment]
do you have sample war file and default web.xml I can look at? I'm contemplating using ant build as I'm running out of time.

**Comment by feni8888** [comment]
tried a diff proxy server and it's working now :) closing this.. thanks guys!

**Comment by feni8888** [comment]
in linux server, it is now generating with the same error, even with this defined in profile:

export HTTP_PROXY=http://hostname:portnumber of the proxy server

**Comment by feni8888** [comment]
also tried
export JAVA_OPTS=-Dhttp://proxyHost=hostname -Dhttp.proxyPort=8080

did not work :(

**Comment by feni8888** [comment]
redo the whole project in my local before redeploying everything to linux.. working now..
