### ISSUE TITLE
Localization is not working

### ISSUE THREAD

**Issue by eloo** [play2war/play2-war-plugin#226]
Hello,
i deployed my Java Play 2.2 application with your plugin. Now i run it on Tomcat7(Servlet 3.0), but there seems to be a bug with the localization files.
It seems that the framework doesnt find mit Messages.en-US and Messages.de-DE files.
So the @Message commands in my views arent working.
Any suggestions?

Thanks for your great work!

**Comment by dlecan** [comment]
Can you provide a test case ?

**Comment by eloo** [comment]
In this zip you can find a view where i call @Messages and my messages.en-US file
As you can see i already tested some changes like using "_" instead of ".".
But the result is everytime the same.. is see the key of the message instead of the value.
http://www.xup.in/dl,14051094/Messages.zip/

If you need more just let me know.. 
Maybe I can build you a war and provide source and war in the next few days to you

**Comment by tkawachi** [comment]
I also run into the same problem.

**Comment by tkawachi** [comment]
It was my mistake in my case. Adding `(implicit lang: Lang)` to template arguments lists fixed the problem, as mentioned http://www.playframework.com/documentation/2.2.x/ScalaI18N.

**Comment by ritu-p** [comment]
Hi ,
I have created the war file but when I deploy it in tomcat server Instead of the message key value the message key gets displayed.Same Issue as Eloo has faced. I am not able to resolve this issue.Any help would be appreciated

**Comment by ritu-p** [comment]
Hi this issue is resolved for me.
My resouce file were "Messages.en" and it was not reolving to the string values when deployed through war file.
When i renamed them to "messages.en" it has started working.

**Comment by eloo** [comment]
thanks ritu-p for this hint
but in my case I think the problem was the "de-DE" extension.
So I changed my files to "de" and "en" and in the application.conf the languages to "de, en" and now it works :)
Thanks

**Comment by dlecan** [comment]
So not an issue ?

**Comment by eloo** [comment]
I think it's still an issue because the "de_DE" naming is not supported
but as as workaround we can use the "de" naming

**Comment by dlecan** [comment]
According to [Play v2.2.3 code](https://github.com/playframework/playframework/blob/2.2.3/framework/src/play/src/main/scala/play/api/i18n/Messages.scala#L66), here are the allowed language patterns:
- `([a-zA-Z]{2})`: `en`, `FR`...
- `([a-zA-Z]{2})-([a-zA-Z]{2}|[0-9]{3})`: `en-US`, `de-de` ... Using `_` is not supported.

According to [Play v2.2.3 code](https://github.com/playframework/playframework/blob/2.2.3/framework/src/play/src/main/scala/play/api/i18n/Messages.scala#L295), `messages.*` file name is case sensitive and lower-cased.
So a file named `Messages.en-US` is wrong, it must be named `messages.en-US` or `messages.en-us`.

So, if you have the following files:
- `messages.en-US`
- `messages.de`

And the following configuration in `conf/application.conf`:
`application.langs="en-US,de"`

it should work.

**Comment by eloo** [comment]
yes, now it works.
so issue could be closed
thanks!
