### ISSUE TITLE
how to configure play2war with just build.sbt for Play 2.2.1

### ISSUE THREAD

**Issue by poornerd** [play2war/play2-war-plugin#231]
I just created a new Play 2.2.1 project.  It has a build.sbt - but no Build.scala.

If I add the imports from the config instructions to the build.sbt, I get an error. I tried adding it as a plugin, in the plugina.sbt like this, then the error with the include and parameter in the build.sbt go away, but "play war" doesn't do anything:
    addSbtPlugin("com.github.play2war" % "play2-war-plugin" % "1.2-beta4")

sfs-macbook-pro-15:computer-database-jpa bp$ play war
[warn] The global sbt directory is now versioned and is located at /Users/bp/.sbt/0.13.
[warn]   You are seeing this warning because there is global configuration in /Users/bp/.sbt but not in /Users/bp/.sbt/0.13.
[warn]   The global sbt directory may be changed via the sbt.global.base system property.
[info] Loading project definition from /Users/bp/play2/computer-database-jpa/project
[info] Set current project to computer-database-jpa (in build file:/Users/bp/play2/computer-database-jpa/)
[error] Not a valid command: war (similar: start)
[error] Not a valid project ID: war
[error] Expected ':' (if selecting a configuration)
[error] Not a valid key: war (similar: watch, run, apiUrl)
[error] war
[error]    ^

Can someone post an example?  I can update the documentation and do a pull request if I can figure it out.

**Comment by poornerd** [comment]
Ok, that was almost...  this works:
1. Add this to your plugins.sbt:
   addSbtPlugin("com.github.play2war" % "play2-war-plugin" % "1.2-beta4")
2. Add this to the top of your build.sbt:
   import com.github.play2war.plugin._
3. Add this at the end of your build.sbt: (yes with the line between them, and the servlet Version you need).
   Play2WarPlugin.play2WarSettings
   
   Play2WarKeys.servletVersion := "2.5"
4. Run "play war" and when it is done, look in the target directory

**Comment by yanns** [comment]
I extended the documentation to support build.sbt as well:
https://github.com/dlecan/play2-war-plugin/wiki/Configuration

Please check if it is easier to understand.
Feedback welcome!

**Comment by poornerd** [comment]
Thanks @yanns
