### ISSUE TITLE
play 2.2.2

### ISSUE THREAD

**Issue by sebastianwe7** [play2war/play2-war-plugin#232]
Hi,

is there any plans to support play 2.2.2 ?

thanks

**Comment by yanns** [comment]
The version 1.2-beta4 works with 2.2.2.
Or do you have any problems with it?

2014-03-13 18:06 GMT+01:00 Sebastian notifications@github.com:

**Comment by sebastianwe7** [comment]
following the instructions, I cannot find the Build.scala. After google for a while, it looks like the Build.scala was a file used by older versions of the play framework... 

As a work around I copied a Build.scala from another project (as explained http://play2war.blogspot.in/) which made it works... but the war generated is not showing the right page... and as I'm very new to the play framework, I don't know if creating that build file I'm messing around with the new 2.2.2 play building system.

**Comment by poornerd** [comment]
1. Add this to your plugins.sbt:
   addSbtPlugin("com.github.play2war" % "play2-war-plugin" % "1.2-beta4")
2. Add this to the top of your build.sbt:
   import com.github.play2war.plugin._
3. Add this at the end of your build.sbt: (yes with the line between them, and the servlet Version you need).
   Play2WarPlugin.play2WarSettings
   
   Play2WarKeys.servletVersion := "2.5"
4. Run "play war" and when it is done, look in the target directory

**Comment by yanns** [comment]
I extended the documentation to support build.sbt as well:
https://github.com/dlecan/play2-war-plugin/wiki/Configuration

Please check if it is easier to understand.
Feedback welcome!

2014-03-13 20:44 GMT+01:00 Brian Porter notifications@github.com:

**Comment by sebastianwe7** [comment]
thanks for that poornerd and yanns. 

Following your new sbt instructions I was able to create a new application from scratch, create a war and deploy it in tomcat 7 (just copying it).. without any errors... in under 2 minutes ... fantastic !

the only part missing is to be able to see the same page that I see running "play run "(localhost:9000/ shows the default template while localhost:8080/my-app/ shows a different message saying that your application is ready).

I've followed the instructions from https://github.com/dlecan/play2-war-plugin/wiki/Deployment (Subcontext deployment)

any ideas ?

**Comment by yanns** [comment]
you will see the same page with play if you'd start play in production mode
(play start instead of play run)

2014-03-14 10:41 GMT+01:00 Sebastian notifications@github.com:

**Comment by sebastianwe7** [comment]
cool... great... thanks you for that !
