### ISSUE TITLE
[1.2beta4] Play2WarKeys.explodedJar doesn't work

### ISSUE THREAD

**Issue by benlwong** [play2war/play2-war-plugin#233]
As far as I can tell, the Play2WarKeys.explordedJar option doesn't work in 1.2beta4 when it is set to true.  I looked into the war file and it is still build as a jar.

Let me know if you need further info.

Thanks,
Ben

**Comment by benlwong** [comment]
Same issue as #224.  I didn't see that issue until now.  This is kind of critical as I relied on it being exploded due to this issue I raised earlier in #179.

**Comment by dlecan** [comment]
Duplicates #224
