### ISSUE TITLE
Question: 2 WARs, same tomcat, different  config ?

### ISSUE THREAD

**Issue by sebastianwe7** [play2war/play2-war-plugin#234]
Sorry for abusing  this bug system for asking a question, but I could not find a mailing list ...

we need to deploy multiple play apps  on the same tomcat, and each one needs to use different configuration  (different DBs, etc...). If we use the -Dconfig.resource (or config.file) as suggested by http://www.playframework.com/documentation/2.2.x/Configuration will work BUT, all the apps will share the same file... (that would be ok with standalone play , as there would be only one app per JVM)

is there anyway to specify a per app config file ?

Thanks

**Comment by valdar** [comment]
Hello,
by defualt it is used the conf/application.conf;
as a workaround you can try to ave the config file named that way for all aplications,
I mena: evry aplication has to use conf/application.conf as his config file.

I'm develpoing a features that will permit to specify an alternative config file name during creation of the war; then the package process will package that config file as conf/application.conf.

**Comment by sebastianwe7** [comment]
thanks for that valdar. Is there any way that I can subscribe to that feature that you are developing ?

**Comment by valdar** [comment]
Unfortunatly , it isn't.
When it is finished I'll fill a pull request. 
But I don't know if it will be acepted, it is also based on an old version of the plugin (the one that I have used since the first day with play2-war-plugin).

**Comment by yanns** [comment]
On Mar 20, 2014 7:36 PM, "Andrea Tarocchi" notifications@github.com wrote:

> Unfortunatly , it isn't.
> When it is finished I'll fill a pull request.
> But I don't know if it will be acepted, it is also based on an old
> version of the plugin (the one that I have used since the first day with
> play2-war-plugin).

Do not hesitate to make a pull request, we will adapt it if necessary (or
help you to do that).

Every contribution is welcome!

**Comment by sebastianwe7** [comment]
that's great. I'm closing it as it is not a bug. Thanks !

**Comment by sebastianwe7** [comment]
just to complete this thread, I've add this line to the end of applocation.conf, as explained in https://github.com/marconilanna/play-bootstrap/blob/master/conf/application.conf#L71

include "local.conf"

now, I can put that file in any tomcat classpath and it works !!! so  we won't need that plugin.

**Comment by valdar** [comment]
On Thu, Mar 20, 2014 at 7:40 PM, Yann Simon notifications@github.comwrote:

> Do not hesitate to make a pull request, we will adapt it if necessary (or
> help you to do that).
> 
> Every contribution is welcome!
> Thank you,
> the code it is done but I need some advice to point me in the right
> direction on how to do test
> for an sbt input task...

Do I need to create a fake play project and invoking the task some how?

**Comment by yanns** [comment]
2014-03-21 11:13 GMT+01:00 Andrea Tarocchi notifications@github.com:

> Thank you,
> the code it is done but I need some advice to point me in the right
> direction on how to do test
> for an sbt input task...
> 
> Do I need to create a fake play project and invoking the task some how?

There are 2 possibilities:
- you can use a fake play project as you mentioned. The play-war-plugin has
  for example sample for this:
  https://github.com/dlecan/play2-war-plugin/tree/develop/sample
- you can use the scripted test plugin. For that, I think you still need a
  fake play project. For info: http://eed3si9n.com/testing-sbt-plugins

**Comment by valdar** [comment]
I have an error when I run the scripted test plugin with "sbt scripted":
class not found: jline\Terminal

I'm runngin it under linux with sbt 0.12.2, scala 2.10.1 and play 2.1.3.

Do you have a clue on this?
I'm planning to port the work to the development branch and see if whit
different sbt and scala version it works some how...

On Fri, Mar 21, 2014 at 11:28 AM, Yann Simon notifications@github.comwrote:

> 2014-03-21 11:13 GMT+01:00 Andrea Tarocchi notifications@github.com:
> 
> > Thank you,
> > the code it is done but I need some advice to point me in the right
> > direction on how to do test
> > for an sbt input task...
> > 
> > Do I need to create a fake play project and invoking the task some how?
> 
> There are 2 possibilities:
> - you can use a fake play project as you mentioned. The play-war-plugin has
>   for example sample for this:
>   https://github.com/dlecan/play2-war-plugin/tree/develop/sample
> - you can use the scripted test plugin. For that, I think you still need a
>   fake play project. For info: http://eed3si9n.com/testing-sbt-plugins
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/dlecan/play2-war-plugin/issues/234#issuecomment-38263919
> .

## 

"In a world without walls and fences who needs Windows and Gates?"

**Comment by cridmann** [comment]
Hey guys,

Do we have any proposed solution here?  I think having a way to provide a different -Dconfig.file for multiple apps in the same container is a really good feature to have.

As you get more and more play apps in your ecosystem, you will inevitably structure your project as a multi-module sbt project like shown here: http://eng.kifi.com/multi-project-deployment-in-play-framework/

However, setups like this will only work (without significant sbt task hackery) by being able to tell individual play apps where to look for the config file, like so:

(run in Compile) := (run in Compile).partialInput(" -Dconfig.file="blah").evaluated

Doing that will not affect the play2war runtime, and thus we are stuck.

Do you guys have an idea of the amount of work it would take to provide this feature?

Thanks!

**Comment by yanns** [comment]
@cridmann a multi-module play application should be package in one war.
Therefore you should not need different configurations.
Or am I missing something?

In general, you should deploy only one play application (war).

**Comment by cridmann** [comment]
@yanns - true it will package in one WAR - though that particular example had multiple play apps that deploy independently within the same multi-module project.

However, that digresses from the main point, which is: is there a way to specify multiple -Dconfig.file 's to different play apps running in the same container?

Do you guys recommend running multiple play apps in the same container?  If not, what dangers do you possibly foresee (besides the config issues mentioned here)?

**Comment by yanns** [comment]
I'd recommend to run only one play application per container.
Play with netty is designed to be "alone" in the VM.
You'll run into subtle problems if you try to run multiple play apps in one container IMO.

**Comment by dlecan** [comment]
> You'll run into subtle problems if you try to run multiple play apps in one container IMO.

Such as #108. It can't be fixed without Play modifications.

**Comment by cridmann** [comment]
Okay thanks for the insight and pointers!  I'll take this info back to our team.
