### ISSUE TITLE
Play 2.3 support

### ISSUE THREAD

**Issue by tkawachi** [play2war/play2-war-plugin#247]
Is there already Play 2.3 support?

**Comment by yanns** [comment]
No, I'll soon work on it

**Comment by yanns** [comment]
For info, the work in progress: https://github.com/yanns/play2-war-plugin/tree/play-2.3
It does not work yet.

**Comment by dlecan** [comment]
Play2War 1.3-beta1 compatible with Play 2.3 (Scala 2.10 & 2.11) has been released !

**Comment by yanns** [comment]
Yeah!
