### ISSUE TITLE
Calling an internal REST API (within the same context) using WS Play API or http client fails

### ISSUE THREAD

**Issue by cg4053** [play2war/play2-war-plugin#253]
I have an application that has 2 entry points:
1. Issue a request from an external client, through Tomcat, that is fulfilled through a single controller.
2. Issue a request from an external client, through Tomcat, that is fulfilled by issuing another internal REST API call within the same application context. The internal REST API call is accomplished using either Play's WS APIs or Apache HTTP sync or async http client calls. The result of the internal API call is then transformed and sent back to the external client as a response to the external request.

All the above scenarios work when running under a standalone Play server.  However, when running under the Play servlet (2.5), the second request fails with a bad request (400) response code, and a "Connection: close" http header is returned.  

Is there a way to get this scenario to work under the Play servlet?

Kind regards,
cg

**Comment by yanns** [comment]
Hi @cg4053,

we have a test case that looks like your use case: https://github.com/play2war/play2-war-plugin/commit/bb6882aa82c45c7f04bb8aa65b6be98f289a037c

The WS client is used to make an internal call.

Can you check it?
If it is the same, we have to find out why this test works and your use case not.

**Comment by cg4053** [comment]
Thanks for getting back to me Simon.

I looked through the use case and the difference between the 2 is that I set up HTTP headers and parameters on the request as well.
The HTTP headers set are:

```
Accept: */*[\r][\n]
Accept-Language: en-US,en;q=0.8
Authorization: Basic c2Vhbjph
Cache-Control: no-cache
Connection: keep-alive
Cookie: PLAY_SESSION="1ab12e44bcaf69f446c869e793cb1dc5ab930e4f-userId=1"
Host: localhost:9000
Origin: chrome-extension://fdmmgilgnpjigdojojpjoooidkmcomcm
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.153 Safari/537.36
Content-Length: 0
Content-Type: application/xml
```

The servlet was deployed under Tomcat 6.

The plugin version we're using is: 1.1.1

**Comment by yanns** [comment]
ok, the test is only checked for the plugin version 1.2.x.
I should add it for the 1.1.1 version.

**Comment by dlecan** [comment]
@cg4053 Do you plan to upgrade to Play 2.2.x or 2.3.x ?
Is it a blocking issue for you until your upgrade ?

**Comment by cg4053** [comment]
We decided to use Play in standalone mode at this time, but at least we now know we can move to a newer version should we have to support other application servers again.

Thank you for your prompt responses - much appreciated!
