### ISSUE TITLE
1.3-beta2-SNAPSHOT error using Play 2.3

### ISSUE THREAD

**Issue by reyjexter** [play2war/play2-war-plugin#254]
Tried the latest release today and got this error:

sbt.ResolveException: unresolved dependency: com.github.play2war#play2-war-core-servlet30_2.11;1.3-beta2-SNAPSHOT: not found

I'm building with sbt 0.13.2 but for some reason it only generates _2.10 files/folders not 2.11.

Thank You
Rey

**Comment by dlecan** [comment]
Play2War 1.3-beta1 has been released today, why do you want to try SNAPSHOT artifacts ?

**Comment by reyjexter** [comment]
I thought it was the latest to try because of this commit:

https://github.com/play2war/play2-war-plugin/commit/14adde66d0b482dd246760c78bcf261953476a81

Will try 1.3-beta1 later today. By the way, do I always need to build this and publish this on my local repo or this will be uploaded to maven or play repo later?

Thanks
Rey

**Comment by dlecan** [comment]
This is a **release**, with official binaries published on Maven Central:
http://search.maven.org/#search|ga|1|g%3A%22com.github.play2war%22

Just use it :)
