### ISSUE TITLE
Couldn't create war file for play 2.2.3 application

### ISSUE THREAD

**Issue by devikm89** [play2war/play2-war-plugin#257]
I created an application in play 2.2.3. I tried to create a war using play2war plugin. But its not worked. The issue is when I imported the war file to my eclipse , the src folder is empty. I am pretty new to play framework. pls help me

**Comment by matm** [comment]
Would you mind giving some details about your `build.sbt` and `project/plugins.sbt` at least?

**Comment by dlecan** [comment]
@devikm89 more details ?

**Comment by dlecan** [comment]
@devikm89 feel free to reopen this issue if you have more details to give us.
