### ISSUE TITLE
application.conf includes referencing absolute paths not working

### ISSUE THREAD

**Issue by elamtzvibirnbaum** [play2war/play2-war-plugin#260]
Hello,

In order to support multiple environments, we have designed our Play application to have an application.conf that at the end uses: include "/my/absolute/path/myconfig.conf" that overrides the values set in the application.conf with those appropriate for the environment. In this way we do not have to put any environment-specific information in files that are included in a build.

When running Play standalone, this works as expected. When bundling this as a war on Tomcat 8, this does not work. The workarounds are:
- set the configuration file path in a -Dconfig.resource to the Tomcat startup script.
- set /my/absolute/path in the Tomcat classpath and change the application.config to do include "myconfig.conf".

Both of these workarounds are not ideal as it requires modification of app server specific deployments so I am filing this issue.

We are using Play 2.3.3 and Tomcat 8.0.11.

Thanks!

**Comment by dlecan** [comment]
> on Tomcat 8, this does not work.

Can you give details ? Stacktrace, file not found ...
Can you debug your config file ? https://github.com/typesafehub/config#debugging-your-configuration

**Comment by elamtzvibirnbaum** [comment]
Sorry for the delay. There is no error message, no stacktrace, it simply does not load the included config file. I debugged the config file and its, interesting, it looks like the leading / is stripped out. 

So I have an application.conf where at the bottom it looks like this:

include "/MY/DIR/application.conf"

Here is a fragment of the output with sensitive data replaced:

Loading config from URL jar:file:/usr/local/apache-tomcat-8.0.11/webapps/MY_WEBAPP/WEB-INF/lib/MY-WEBAPP.jar!/application.conf from class loader WebappClassLoader
  context: /MY_WEBAPP
  delegate: false
----------> Parent Classloader:
java.net.URLClassLoader@7e48da19

Loading config from class loader WebappClassLoader
  context: /MY_WEBAPP
  delegate: false
----------> Parent Classloader:
java.net.URLClassLoader@7e48da19
 but there were no resources called MY/PATH/application.conf

So you can see that it seems to do almost everything but since it strips out the leading / it thinks that the directory is relative when it in fact is an absolute path.  So do I need to use a different syntax to specify an absolute path?

**Comment by elamtzvibirnbaum** [comment]
Ok, so I've resolved the issue and indeed it is a different syntax. I instead have to use:

```
include file("/MY/DIR/application.conf")
```

And it all works now in both native Play and as a WAR. It annoys me so much because all this would need was some decent documentation on the Typesafe/Play end to list that. A reference, something that would show what's possible. 25 Google searches and nothing. I discovered this when I used single quotes and IntelliJ's warning listed possible options!

In any rate, while I have resolved my original problem issue, its up to you to decide if this is still a bug in Play2War since it does involve different behavior in native Play vs. as a WAR with regards to referencing an absolute path.

**Comment by dlecan** [comment]
You have found a workaround, thank you.

**Comment by guillerminag** [comment]
Hello elamtzvibirnbaum , I have a similar problem, I need use an configuration  file into war file instead of play internal file. How did you resolve this problem? Can you send me an email explaining your solution, please?
my email is: guillermina.galache@gmail.com
 thank very much.

**Comment by elamtzvibirnbaum** [comment]
My solution was listed above.

**Comment by guillerminag** [comment]
hi, please could you send me an example? because  I still can not make it
work.
thank very much

2015-03-20 19:39 GMT-03:00 Elam Birnbaum notifications@github.com:
