### ISSUE TITLE
Does plugin work for 2.3.4 play framework

### ISSUE THREAD

**Issue by mkramchandra** [play2war/play2-war-plugin#264]
As the title says, I tried it but unsuccessful. Does the plugin really work for 2.3.4 version. 
If it is can you please provide sample Build.scala and plugins.sbt files.

Thanks for the great plugin.

**Comment by yanns** [comment]
You nee to use the version `1.3-beta2` as mentioned on the [Homepage](https://github.com/play2war/play2-war-plugin)

project/plugins.sbt

``` scala
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.3.4")
```

Then activate the plugin in Build.scala or build.sbt, as mentioned in the [configuration doc](https://github.com/play2war/play2-war-plugin/wiki/Configuration)

If you find an error in the documentation, or if the documentation is not clear, please mention it so that we can enhance it.

**Comment by dlecan** [comment]
> Does the plugin really work for 2.3.4 version. 

We have 245 successful integration tests, running on real Application Servers (Tomcat 6/7/8, Jetty ...) with Play 2.3.4.
https://play-war.ci.cloudbees.com/job/Play_2_War_Run_integration_tests_-_Play_23x/PLAY_VERSION=2.3.4,label=m1.large/lastCompletedBuild/testReport/

>  I tried it 

Great !

>  but unsuccessful

Please, give more details if you need help :)

**Comment by mkramchandra** [comment]
Thanks for suggestions.

Here is the sample Build.scala file but it throws error like not found object: PlayPorject. Do you know the import statement for PlayProject ? Or is it not the correct way of building Build.scala ?

import sbt._
import Keys._
import PlayProject._
import com.github.play2war.plugin._

object ApplicationBuild extends Build {

val appName = "SampleApp"
val appVersion = "1.0"

val appDependencies = Seq(
// Add your project dependencies here,
javaCore,
javaJdbc,
javaEbean
)

val main = PlayProject(appName, appVersion, appDependencies)
.settings(Play2WarPlugin.play2WarSettings: _*)
.settings(
Play2WarKeys.servletVersion := "2.5"
)
// Add your own project settings here
}

Thanks for help

**Comment by mkramchandra** [comment]
I got it working using build.sbt. I followed the configuration section and it worked. 

Thanks for help
