### ISSUE TITLE
Play on Tomcat logs to both custom log file and catalina.out

### ISSUE THREAD

**Issue by elamtzvibirnbaum** [play2war/play2-war-plugin#265]
Hello,

We are deploying Play as a war deployed on Tomcat 8 with a logger.xml file in the conf directory that directs logging to appear in a separate log file. This log file is properly updated with log events as expected, however these same events also appear in Tomcat's catalina.out log file. I've tried 

Is there anything we can do to prevent this content from appearing in catalina.out?

Thank you.

**Comment by yanns** [comment]
In setenv.sh from Tomcat, I use the following property:
`export JAVA_OPTS="-Dlogback.configurationFile=/etc/tomcat/conf/logger.xml -Dlogger.file=/etc/tomcat/logger.xml`

You can try that.

**Comment by elamtzvibirnbaum** [comment]
Thanks for the comment, Yanns, however the issue isn't that it cannot find the logger file, it can find it just fine. It was that logging events seemed to be sent to the logger and catalina.out.

I'm closing this ticket as I discovered what the issue was. Logback has a very flexible configuration and the config I was using sent legging messages both to standard out as well as to the file. Playing around with the configuration file showed me a way to make logger messages go only to the file and not to standard out. I still have to play around with the configuration to get it right but its not an issue with Play2War.

**Comment by yanns** [comment]
Thx for your feedback!
