### ISSUE TITLE
Adding metadata-complete="true" breaks the app in tomcat

### ISSUE THREAD

**Issue by oyevtushok** [play2war/play2-war-plugin#271]
I'm using play2-war-plugin v1.2 for packaging Play2(v2.2.3) application which is deployed to tomcat 7.0.56. It seems to work without web.xml or with web.xml that contains the following:

``` xml
<?xml version="1.0" encoding="UTF-8"?>

<web-app xmlns="http://java.sun.com/xml/ns/javaee"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-app_3_0.xsd"
         version="3.0">

</web-app>

```

Although if I add `metadata-complete="true"` to optimize permgen usage as recommended [here](http://wiki.apache.org/tomcat/HowTo/FasterStartUp) the app stops working in tomcat(I get HTTP Status 404).

I created a repo with [example application that does not work](https://github.com/oyevtushok/play2war-test).

**Comment by dlecan** [comment]
> Setting metadata-complete="true" disables scanning your web application and its libraries for classes that use annotations to define components of a web application (Servlets etc.).

That's pretty clear, isn't it ? As Play2War relies on `@WebServlet` annotation, `metadata-complete="true"` disables Play2War.

**Comment by oyevtushok** [comment]
Not to me at least. Haven't found anything about this in documentation

**Comment by dlecan** [comment]
Documented here:
https://github.com/play2war/play2-war-plugin/wiki/Configuration#servlet-30-container-configuration
