### ISSUE TITLE
Play 2.0 war Plugin

### ISSUE THREAD

**Issue by sindhusakthi** [play2war/play2-war-plugin#272]
I am new to Play and developing application in Play 2.0 that has to run on tomcat. For generating war file i get dependency error. I don`t know what is wrong. Please help me to resolve this.

plugins.sbt file is:

// Comment to get more information during initialization
logLevel := Level.Warn

// The Typesafe repository
resolvers += "Typesafe repository" at "http://repo.typesafe.com/typesafe/releases/"

resolvers += "Play2war plugins release" at "http://repository-play-war.forge.cloudbees.com/release/"

// Use the Play sbt plugin for Play projects
addSbtPlugin("play" % "sbt-plugin" % "2.0")

addSbtPlugin("com.github.play2war" % "play2-war-plugin" % "0.8.1")

Build.scala

import sbt._
import Keys._
import PlayProject._
import com.github.play2war.plugin._

object ApplicationBuild extends Build {

```
val appName         = "XMPLAR PORTAL"
val appVersion      = "1.0-SNAPSHOT"

val appDependencies = Seq(
  // Add your project dependencies here,
  "mysql" % "mysql-connector-java" % "5.1.18",
  "com.typesafe" % "play-plugins-mailer_2.9.1" % "2.0.4",
  "org.apache.directory.studio" % "org.apache.commons.io" % "2.4",
  "org.xhtmlrenderer" % "core-renderer" % "R8",
  "net.sf.jtidy" % "jtidy" % "r938",
  "com.itextpdf" % "itextpdf"  % "5.1.0"            
)

val main = PlayProject(appName, appVersion, appDependencies, mainLang = JAVA).settings(
).settings(Play2WarPlugin.play2WarSettings: _*)
.settings(Play2WarKeys.servletVersion := "3.0")
```

}

build.properties
sbt.version=0.11.2

and stacktrace is 

> play war
> [info] Loading project definition from ..\project
> [warn]  module not found: com.github.play2war#play2-war-plugin;0.8.1
> [warn] ==== typesafe-ivy-releases: tried
> [warn]   http://repo.typesafe.com/typesafe/ivy-releases/com.github.play2war/play
> 2-war-plugin/scala_2.9.1/sbt_0.11.2/0.8.1/ivys/ivy.xml
> [warn] ==== local: tried
> [warn]   D:\Play\play-2.0\framework..\repository/local/com.github.play2war/play
> 2-war-plugin/scala_2.9.1/sbt_0.11.2/0.8.1/ivys/ivy.xml
> [warn] ==== Typesafe repository: tried
> [warn]   http://repo.typesafe.com/typesafe/releases/com/github/play2war/play2-wa
> r-plugin_2.9.1_0.11.2/0.8.1/play2-war-plugin-0.8.1.pom
> [warn] ==== public: tried
> [warn]   http://repo1.maven.org/maven2/com/github/play2war/play2-war-plugin_2.9.
> 1_0.11.2/0.8.1/play2-war-plugin-0.8.1.pom
> [warn] ==== Scala-Tools Maven2 Repository: tried
> [warn]   http://scala-tools.org/repo-releases/com/github/play2war/play2-war-plug
> in_2.9.1_0.11.2/0.8.1/play2-war-plugin-0.8.1.pom
> [warn]  ::::::::::::::::::::::::::::::::::::::::::::::
> [warn]  ::          UNRESOLVED DEPENDENCIES         ::
> [warn]  ::::::::::::::::::::::::::::::::::::::::::::::
> [warn]  :: com.github.play2war#play2-war-plugin;0.8.1: not found
> [warn]  ::::::::::::::::::::::::::::::::::::::::::::::
> [warn]
> [warn]  Note: Some unresolved dependencies have extra attributes.  Check that th
> ese dependencies exist with the requested attributes.
> [warn]          com.github.play2war:play2-war-plugin:0.8.1 (sbtVersion=0.11.2, s
> calaVersion=2.9.1)
> [warn]
> [error] {file:../project/}default-efa860/*:update: sbt.Resol
> veException: unresolved dependency: com.github.play2war#play2-war-plugin;0.8.1:
> not found
> Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?

**Comment by yanns** [comment]
I only see the 0.8.2 version on maven central: http://repo1.maven.org/maven2/com/github/play2war/play2-war_2.9.1/

@dlecan are you aware of this issue?

**Comment by dlecan** [comment]
> I am new to Play and developing application in Play 2.0 that has to run on tomcat

Can you upgrade to Play 2.0.8 and Play2War 0.8.2 ?

Play 2.0 is quite old and we won't support it.

Thank you

**Comment by sindhusakthi** [comment]
Then how to upgrade play framework from 2.0 to 2.0.8. Can you tell me what are all modifications has to done. 
I am very new to this Play so help me to find a solution.

**Comment by yanns** [comment]
in `project/plugins.sbt`, write `2.0.8` instead of `2.0`.
Then you must start play again.

**Comment by sindhusakthi** [comment]
My plugins.sbt flie is
// Comment to get more information during initialization
logLevel := Level.Warn

// The Typesafe repository
resolvers += "Typesafe repository" at "http://repo.typesafe.com/typesafe/releases/"

//resolvers += "Play2war plugins release" at "http://repository-play-war.forge.cloudbees.com/release/"

// Use the Play sbt plugin for Play projects
addSbtPlugin("play" % "sbt-plugin" % "2.0.8")

addSbtPlugin("com.github.play2war" % "play2-war-plugin" % "0.8.1")

After changing 2.0.8 i get error like

> play run
> [info] Loading project definition from ..\project
> [warn]  module not found: play#sbt-plugin;2.0.8
> [warn] ==== typesafe-ivy-releases: tried
> [warn]   http://repo.typesafe.com/typesafe/ivy-releases/play/sbt-plugin/scala_2.
> 9.1/sbt_0.11.2/2.0.8/ivys/ivy.xml
> [warn] ==== local: tried
> [warn]   D:\Play\play-2.0\framework..\repository/local/play/sbt-plugin/scala_2.
> 9.1/sbt_0.11.2/2.0.8/ivys/ivy.xml
> [warn] ==== Typesafe repository: tried
> [warn]   http://repo.typesafe.com/typesafe/releases/play/sbt-plugin_2.9.1_0.11.2
> /2.0.8/sbt-plugin-2.0.8.pom
> [warn] ==== public: tried
> [warn]   http://repo1.maven.org/maven2/play/sbt-plugin_2.9.1_0.11.2/2.0.8/sbt-pl
> ugin-2.0.8.pom
> [warn] ==== Scala-Tools Maven2 Repository: tried
> [warn]   http://scala-tools.org/repo-releases/play/sbt-plugin_2.9.1_0.11.2/2.0.8
> /sbt-plugin-2.0.8.pom
> [warn]  ::::::::::::::::::::::::::::::::::::::::::::::
> [warn]  ::          UNRESOLVED DEPENDENCIES         ::
> [warn]  ::::::::::::::::::::::::::::::::::::::::::::::
> [warn]  :: play#sbt-plugin;2.0.8: not found
> [warn]  ::::::::::::::::::::::::::::::::::::::::::::::
> [warn]
> [warn]  Note: Some unresolved dependencies have extra attributes.  Check that th
> ese dependencies exist with the requested attributes.
> [warn]          play:sbt-plugin:2.0.8 (sbtVersion=0.11.2, scalaVersion=2.9.1)
> [warn]
> [error] {file:/../project/}default-efa860/*:update: sbt.Resol
> veException: unresolved dependency: play#sbt-plugin;2.0.8: not found
> Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?

I think the repository url is wrong in my application. Can you tell what is the repository url?
