### ISSUE TITLE
Logging on JBoss Wildfly

### ISSUE THREAD

**Issue by davidt99** [play2war/play2-war-plugin#273]
Hi,
I managed to deploy my war on JBoss, but I can't see any logs.
Is there anything else other then write my log the "JBoss" way?
Is the play-redirect extension will work on JBoss wildfly?
Thanks!

**Comment by dlecan** [comment]
Play2war may works on Wildfly, we didn't test it.
Tell us (reopen this issue) if it works with the plat-redirect extension.
