### ISSUE TITLE
Create WAR file for play 2.2.4 to deploy on JBOSS 5.1.0 GA

### ISSUE THREAD

**Issue by 0ffTopic** [play2war/play2-war-plugin#275]
Hi there

I'm having issues deploying a war file into JBOSS 5.1.0 GA.

I followed all the steps on the documentation to create the .war and created/edited all the necessary files. The war file is created but when I try to put it on the server, it gives me a bunch of errors on the console:

http://sharesend.com/h6f3x46j

The war file is: http://sharesend.com/epahyyn1

What am I doing wrong?

**Comment by dlecan** [comment]
Your WAR file deploys fine on Tomcat 7, it is ok.
I don't understand your log file, I can't find any `root.war` reference.

**Comment by 0ffTopic** [comment]
Sorry.
The war in the log is desafiooe.war

The is root.war because of a deploy try who tells me to rename the created war to root. No success either.

**Comment by dlecan** [comment]
Your problem is not related to Play2War:

```
org.jboss.deployers.spi.DeploymentException: Error determining structure: DesafioOE.war
  ...
Caused by: java.util.zip.ZipException: error in opening zip file
  ...
```

Something is wrong with your JBoss installation and/or your server.

Indications: http://stackoverflow.com/questions/646322/jboss5-cannot-deploy-due-to-java-util-zip-zipexception-error-in-opening-zip-fi

**Comment by 0ffTopic** [comment]
Thank you for your feedback.
I'll try to resolve the issue from there.
