### ISSUE TITLE
Memory leak when stoping the play2 application 

### ISSUE THREAD

**Issue by sdpatil** [play2war/play2-war-plugin#277]
I am using Play Framework 2.2, play2-war-plugin 1.2 and Tomcat 7.0.53. When i stop my application it generates memory leak. After couple of re-deploys of application without restarting tomcat, my server runs out of PermGen space and throws java.lang.OutOfMemoryError: PermGen space

This is how my plugins.sbt looks like
// Comment to get more information during initialization
logLevel := Level.Warn

// The Typesafe repository
resolvers += "Typesafe repository" at "http://repo.typesafe.com/typesafe/releases/"

// Use the Play sbt plugin for Play projects
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.2.0")

//Use the play-yeoman plugin to get yeoman support in the play console
addSbtPlugin("com.tuplejump" % "sbt-yeoman" % "0.6.4")

addSbtPlugin("com.github.play2war" % "play2-war-plugin" % "1.2")

 This is how my build.sbt looks like

import play.Project._
import com.tuplejump.sbt.yeoman.Yeoman
import com.github.play2war.plugin._

name := """SIUPortal"""

version := "1.0"

libraryDependencies ++= Seq(
  "org.webjars" %% "webjars-play" % "2.2.0", 
  "org.webjars" % "bootstrap" % "2.3.1",
  "org.elasticsearch" % "elasticsearch" % "1.3.2",
  javaJdbc,
  javaEbean,
  "org.mindrot" % "jbcrypt" % "0.3m",
  "mysql" % "mysql-connector-java" % "5.1.21"
)

playScalaSettings

play.Project.playJavaSettings ++ Yeoman.yeomanSettings

Play2WarPlugin.play2WarSettings

Play2WarKeys.servletVersion := "3.0"

Play2WarKeys.explodedJar := true

Steps to reproduce the problem
1) Deploy application on tomcat and then access it few times so that the play framework threads pools start
2) Stop application using Tomcat console and you should see Memory leak warnings like this
-  - [info] play - Stopping play server...
  -  - [debug] Global$ - Entering Global.onStop()
  -  - [debug] o.e.t.netty - [Aleta Ogord] disconnected from [[Caiera][pwLQO3e2S6arb1hLjv8www][mgcc112517.local][inet[localhost/127.0.0.1:8300]]]
  -  - [debug] o.e.t.netty - [Aleta Ogord] disconnected from [[#transport#-1][mgcc112517.local][inet[localhost/127.0.0.1:8300]]]
  -  - [debug] Global$ - Exiting Global.onStop()
    [Dec 30, 2014 11:44:16 AM] [org.apache.catalina.loader.WebappClassLoader clearReferencesThreads] [SEVERE]: The web application [/siuportal-1.0] appears to have started a thread named [play-scheduler-1] but has failed to stop it. This is very likely to create a memory leak.
    [Dec 30, 2014 11:44:16 AM] [org.apache.catalina.loader.WebappClassLoader clearReferencesThreads] [SEVERE]: The web application [/siuportal-1.0] appears to have started a thread named [play-akka.actor.default-dispatcher-6] but has failed to stop it. This is very likely to create a memory leak.
    [Dec 30, 2014 11:44:16 AM] [org.apache.catalina.loader.WebappClassLoader clearReferencesThreads] [SEVERE]: The web application [/siuportal-1.0] appears to have started a thread named [play-akka.actor.default-dispatcher-7] but has failed to stop it. This is very likely to create a memory leak.
    [Dec 30, 2014 11:44:16 AM] [org.apache.catalina.loader.WebappClassLoader clearReferencesThreads] [SEVERE]: The web application [/siuportal-1.0] appears to have started a thread named [play-internal-execution-context-1] but has failed to stop it. This is very likely to create a memory leak.
    [Dec 30, 2014 11:44:16 AM] [org.apache.catalina.loader.WebappClassLoader clearReferencesThreads] [SEVERE]: The web application [/siuportal-1.0] appears to have started a thread named [Timer-0] but has failed to stop it. This is very likely to create a memory leak.
    [Dec 30, 2014 11:44:16 AM] [org.apache.catalina.loader.WebappClassLoader clearReferencesThreads] [SEVERE]: The web application [/siuportal-1.0] appears to have started a thread named [play-akka.actor.default-dispatcher-10] but has failed to stop it. This is very likely to create a memory leak.
    [Dec 30, 2014 11:44:16 AM] [org.apache.catalina.loader.WebappClassLoader clearReferencesThreads] [SEVERE]: The web application [/siuportal-1.0] appears to have started a thread named [play-akka.actor.default-dispatcher-11] but has failed to stop it. This is very likely to create a memory leak.
    [Dec 30, 2014 11:44:16 AM] [org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks] [SEVERE]: The web application [/siuportal-1.0] created a ThreadLocal with key of type [org.elasticsearch.common.inject.InjectorImpl$1](value [org.elasticsearch.common.inject.InjectorImpl$1@7e8b61e5]) and a value of type [java.lang.Object[]](value [[Ljava.lang.Object;@70c8424a]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
    [Dec 30, 2014 11:44:16 AM] [org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks] [SEVERE]: The web application [/siuportal-1.0] created a ThreadLocal with key of type [java.lang.ThreadLocal](value [java.lang.ThreadLocal@6b78421e]) and a value of type [scala.concurrent.forkjoin.ForkJoinPool.Submitter](value [scala.concurrent.forkjoin.ForkJoinPool$Submitter@6354a678]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
    [Dec 30, 2014 11:44:16 AM] [org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks] [SEVERE]: The web application [/siuportal-1.0] created a ThreadLocal with key of type [scala.concurrent.forkjoin.ThreadLocalRandom$1](value [scala.concurrent.forkjoin.ThreadLocalRandom$1@4a7d433a]) and a value of type [scala.concurrent.forkjoin.ThreadLocalRandom](value [scala.concurrent.forkjoin.ThreadLocalRandom@65c8bb0a]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
    [Dec 30, 2014 11:44:16 AM] [org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks] [SEVERE]: The web application [/siuportal-1.0] created a ThreadLocal with key of type [java.lang.ThreadLocal](value [java.lang.ThreadLocal@6b78421e]) and a value of type [scala.concurrent.forkjoin.ForkJoinPool.Submitter](value [scala.concurrent.forkjoin.ForkJoinPool$Submitter@65dfde2f]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
    [Dec 30, 2014 11:44:16 AM] [org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks] [SEVERE]: The web application [/siuportal-1.0] created a ThreadLocal with key of type [java.lang.ThreadLocal](value [java.lang.ThreadLocal@6b78421e]) and a value of type [scala.concurrent.forkjoin.ForkJoinPool.Submitter](value [scala.concurrent.forkjoin.ForkJoinPool$Submitter@4c7413e9]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
    [Dec 30, 2014 11:44:16 AM] [org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks] [SEVERE]: The web application [/siuportal-1.0] created a ThreadLocal with key of type [java.lang.ThreadLocal](value [java.lang.ThreadLocal@6b78421e]) and a value of type [scala.concurrent.forkjoin.ForkJoinPool.Submitter](value [scala.concurrent.forkjoin.ForkJoinPool$Submitter@58c74d35]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
    [Dec 30, 2014 11:44:16 AM] [org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks] [SEVERE]: The web application [/siuportal-1.0] created a ThreadLocal with key of type [java.lang.ThreadLocal](value [java.lang.ThreadLocal@6b78421e]) and a value of type [scala.concurrent.forkjoin.ForkJoinPool.Submitter](value [scala.concurrent.forkjoin.ForkJoinPool$Submitter@49e001c]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
    [Dec 30, 2014 11:44:16 AM] [org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks] [SEVERE]: The web application [/siuportal-1.0] created a ThreadLocal with key of type [java.lang.ThreadLocal](value [java.lang.ThreadLocal@6b78421e]) and a value of type [scala.concurrent.forkjoin.ForkJoinPool.Submitter](value [scala.concurrent.forkjoin.ForkJoinPool$Submitter@211930a2]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
    [Dec 30, 2014 11:44:16 AM] [org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks] [SEVERE]: The web application [/siuportal-1.0] created a ThreadLocal with key of type [java.lang.ThreadLocal](value [java.lang.ThreadLocal@6b78421e]) and a value of type [scala.concurrent.forkjoin.ForkJoinPool.Submitter](value [scala.concurrent.forkjoin.ForkJoinPool$Submitter@7cc7eca7]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
    [Dec 30, 2014 11:44:16 AM] [org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks] [SEVERE]: The web application [/siuportal-1.0] created a ThreadLocal with key of type [akka.actor.ActorCell$$anon$1](value [akka.actor.ActorCell$$anon$1@298207f1]) and a value of type [scala.collection.immutable.Nil$](value [List%28%29]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
    [Dec 30, 2014 11:44:16 AM] [org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks] [SEVERE]: The web application [/siuportal-1.0] created a ThreadLocal with key of type [java.lang.ThreadLocal](value [java.lang.ThreadLocal@6b78421e]) and a value of type [scala.concurrent.forkjoin.ForkJoinPool.Submitter](value [scala.concurrent.forkjoin.ForkJoinPool$Submitter@17d77481]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
    [Dec 30, 2014 11:44:16 AM] [org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks] [SEVERE]: The web application [/siuportal-1.0] created a ThreadLocal with key of type [java.lang.ThreadLocal](value [java.lang.ThreadLocal@6b78421e]) and a value of type [scala.concurrent.forkjoin.ForkJoinPool.Submitter](value [scala.concurrent.forkjoin.ForkJoinPool$Submitter@4221cd61]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
    [Dec 30, 2014 11:44:16 AM] [org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks] [SEVERE]: The web application [/siuportal-1.0] created a ThreadLocal with key of type [java.lang.ThreadLocal](value [java.lang.ThreadLocal@6b78421e]) and a value of type [scala.concurrent.forkjoin.ForkJoinPool.Submitter](value [scala.concurrent.forkjoin.ForkJoinPool$Submitter@3932bd32]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
    [Dec 30, 2014 11:44:16 AM] [org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks] [SEVERE]: The web application [/siuportal-1.0] created a ThreadLocal with key of type [scala.util.DynamicVariable$$anon$1](value [scala.util.DynamicVariable$$anon$1@32233af4]) and a value of type [scala.Some] (value [Some([1.31] failure: end of input

application/json;charset=UTF-8
                              ^)]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
[Dec 30, 2014 11:44:16 AM] [org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks] [SEVERE]: The web application [/siuportal-1.0] created a ThreadLocal with key of type [scala.util.DynamicVariable$$anon$1](value [scala.util.DynamicVariable$$anon$1@32233af4]) and a value of type [scala.Some] (value [Some([1.31] failure: end of input

application/json;charset=UTF-8
                              ^)]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
[Dec 30, 2014 11:44:16 AM] [org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks] [SEVERE]: The web application [/siuportal-1.0] created a ThreadLocal with key of type [akka.actor.ActorCell$$anon$1](value [akka.actor.ActorCell$$anon$1@298207f1]) and a value of type [scala.collection.immutable.Nil$](value [List%28%29]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
[Dec 30, 2014 11:44:16 AM] [org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks] [SEVERE]: The web application [/siuportal-1.0] created a ThreadLocal with key of type [akka.actor.ActorCell$$anon$1](value [akka.actor.ActorCell$$anon$1@298207f1]) and a value of type [scala.collection.immutable.Nil$](value [List%28%29]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
[Dec 30, 2014 11:44:16 AM] [org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks] [SEVERE]: The web application [/siuportal-1.0] created a ThreadLocal with key of type [java.lang.ThreadLocal](value [java.lang.ThreadLocal@6b78421e]) and a value of type [scala.concurrent.forkjoin.ForkJoinPool.Submitter](value [scala.concurrent.forkjoin.ForkJoinPool$Submitter@525474a5]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
[Dec 30, 2014 11:44:19 AM] [org.apache.catalina.util.LifecycleBase stop] [INFO]: The stop() method was called on component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/siuportal-1.0]] after stop() had already been called. The second call will be ignored.
[Dec 30, 2014 11:44:19 AM] [org.apache.catalina.startup.HostConfig undeploy] [INFO]: Undeploying context [/siuportal-1.0]

Now if you attach jvisualvm to Tomcat you can see 3 orphan threads that were started by my application but were not stopped when application stopped, These threads hold on to classes loaded by your applications class loader and do not let them garbage collected from PermGen.

![firstscreenshot](https://cloud.githubusercontent.com/assets/2074730/5582224/dbb18c1e-901a-11e4-8b8c-7ddbc724b7ea.png)

3) Redeploy your application and access it few times. You can see old orphan threads in addition to new thread pool started by your application
![secondscreenshot](https://cloud.githubusercontent.com/assets/2074730/5582234/01c33858-901b-11e4-81cf-5def18ccfb48.png)

4) Repeat deploy/undeploy cycle and your tomcat should run out PermGen memory

**Comment by dlecan** [comment]
Play runtime is not designed to be embedded in containers.
What does that mean ? It's classloader model is not designed to be restarted in the JVM (except in debug mode, but Play2War forces "prod" mode).

So what to do as there's nothing we can do on Play2War side ?
1/ Leave Play2War an use native and natural Play deployment model
2/ Improve Play runtime itself to handle classloader (un)loading

**Comment by itonics-tbeauvais** [comment]
This is insane that Play isn't made to run in a standard J2EE container!
