### ISSUE TITLE
Play 2.4.0-M2 incompatibility

### ISSUE THREAD

**Issue by fullwall** [play2war/play2-war-plugin#278]
PlayPositionMapper has moved namespaces in 2.4.0 from play to play.sbtplugin causing an incompatibility with play2war.

**Comment by dcdieci** [comment]
How can this be fixed? I run into the same problem

**Comment by yanns** [comment]
We will provide a new version of the plugin once Play 2.4.0 is published.
Or you can try yourself to provide a patch for this:
https://github.com/play2war/play2-war-plugin/wiki/How-to-help

I can support you if you want to migrate the plugin to play 2.4.0-M2 yourself.

**Comment by yanns** [comment]
I started the migration in a branch:
https://github.com/play2war/play2-war-plugin/tree/issue-%23278-be-compatible-with-play-2.4.x

**Comment by matmannion** [comment]
Is there any news on this being merged @yanns?

**Comment by yanns** [comment]
We are trying to publish a first beta version.

**Comment by dlecan** [comment]
P2W 1.4-beta1 was released a few weeks ago. It handles Play 2.4.x versions.
