### ISSUE TITLE
P2W 1.2 for Java 6

### ISSUE THREAD

**Issue by nimurphy** [play2war/play2-war-plugin#279]
More a Scala/SBT question, I'm respectively pretty/completely new to both. I need to build version 1.2 (Play 2.2.1) for JVM 1.6. How do I go about doing this in SBT? 

I'll continue looking throught the SBT docs in the meantime but help would be greatly appreciated!

**Comment by dlecan** [comment]
>  I need to build version 1.2 (Play 2.2.1) for JVM 1.6.

Why do you need that ? Play2war plugin is already built with "source" and "target" flags set to 1.6.

**Comment by nimurphy** [comment]
I deployed to JBoss 4 (Java 6) and got an UnsupportedClassVersionError (52.0 - Java 8) with controllers/Application. I thought this was due to P2W, as Play was configured to compile to 1.6. I realise now that Intellij is configured to compile artifacts to 1.6, not Play itself.

Sorry for the confusion. Thanks.
