### ISSUE TITLE
[Play-2.2.4, Tomcat7] Twice response header Transfer-Encoding: chunked while file/ stream download

### ISSUE THREAD

**Issue by bookwood1977** [play2war/play2-war-plugin#289]
Hello,

for the moment am forced to use 2.1.5 --> no problems 

while debugging  or running local the app... no problems...

while using 2.2.4 (same problem in using 2.2.6) problems after war-packaging and deploying to Tomcat7 
--> resulting in twice response header "transfer-encoding: chunked". 
   --> the customer system doesnt like and rejects all calls containing streams.

from config...
addSbtPlugin("com.github.play2war" % "play2-war-plugin" % "1.2")
 Play2WarKeys.servletVersion := "3.0" 

![twice_chunked_chrome](https://cloud.githubusercontent.com/assets/12203465/8428234/7f9e0b18-1f1d-11e5-9c4f-04aee8ea105b.jpg)

made an minimal prototype for demonstration --> howto submit?

**Comment by dlecan** [comment]
Thank you for reporting this.

Tomcat version?

> made an minimal prototype for demonstration --> howto submit?

Please, create a new Github repository and commit/push your test case.

Thank you

**Comment by bookwood1977** [comment]
Hello Damien,

Windows 7, Tomcat 7.0.47 (64bit), play-2.2.4

https://github.com/bookwood1977/play2warPluginBugprototype.git

Thank you,
Mathias

2015-06-30 13:46 GMT+02:00 Damien Lecan notifications@github.com:

**Comment by yanns** [comment]
Thanks @bookwood1977 for your repo.
I could reproduce this bug.
The fix is here: https://github.com/play2war/play2-war-plugin/pull/290

**Comment by bookwood1977** [comment]
Hello Yann,

thank you for finding and solving the bug.

For me that means waiting for the next package release?

regards,
Mathias

2015-07-01 9:55 GMT+02:00 Yann Simon notifications@github.com:

**Comment by yanns** [comment]
you can also deployed it locally if you need it quickly.

**Comment by bookwood1977** [comment]
I could wait till package release.

But for learning something new...

How would I deploy it myself?

2015-07-01 10:27 GMT+02:00 Yann Simon notifications@github.com:

**Comment by yanns** [comment]
https://github.com/play2war/play2-war-plugin/wiki/How-to-help#build-and-publish-plugin-and-core-runtime-in-local-repository

**Comment by dlecan** [comment]
Play2War v1.2.1 for Play 2.2.x versions has been released.
