### ISSUE TITLE
War plugin is not getting download for play 2.1.5 

### ISSUE THREAD

**Issue by kanchu1708** [play2war/play2-war-plugin#294]
Unresolved dependency play2-war-plugin-1.1.2 not found

play version:2.1.5
sbt version:0.12.2
scala:2.10.4

**Comment by dlecan** [comment]
As you see here: https://github.com/play2war/play2-war-plugin#versions-not-supported-anymore
play2war v1.1.2 doesn't exist.

Last version for Play 2.1.4+ is P2W v1.1.1.

**Comment by kanchu1708** [comment]
even 1.1.1 is also not getting download same unresolved dependency

**Comment by dlecan** [comment]
> even 1.1.1 is also not getting download same unresolved dependency

Which one ?

**Comment by kanchu1708** [comment]
with play 2.1.5 I am using 1.0.5 it is also not getting download

**Comment by dlecan** [comment]
I cannot help you if you just write "it doesn't work".
It used to work for many people before, so either something is wrong in your configuration or something else has changed somewhere (!) which leads to a failure in your project.

Did you read that ? https://github.com/play2war/play2-war-plugin#versions-not-supported-anymore

With Play v2.1.5, you **must** use Play2war v1.1.1.

With this version, can copy/past the following files:
- plugins.sbt
- Build.scala
- build.properties
- error stacktrace

**Comment by kanchu1708** [comment]
<img width="422" alt="error" src="https://cloud.githubusercontent.com/assets/14889832/10214461/2473fbe6-6836-11e5-8459-41342e530d1b.PNG">
yes I am following only this link: https://github.com/play2war/play2-war-plugin#versions-not-supported-anymore
Build.proeprties:
sbt.version=0.12.2

Build.scala:

``` scala
import sbt._
import Keys._
import play.Project._
import com.github.play2war.plugin._
object ApplicationBuild extends Build {

  val appName         = "testDemo"
  val appVersion      = "1.0-SNAPSHOT"
 val appDependencies = Seq(
    // Add your project dependencies here,
    jdbc,
    anorm,
    "com.sun.jersey" % "jersey-core" % "1.19",
     "com.google.code.gson" % "gson" % "2.3.1",
     "org.apache.httpcomponents" % "httpclient" % "4.5",
     "org.apache.httpcomponents" % "httpmime" % "4.5",
     "commons-codec" % "commons-codec" % "1.10")
val main = play.Project(appName, appVersion, appDependencies)
   .settings(Play2WarPlugin.play2WarSettings: _*)
    .settings(
        Play2WarKeys.servletVersion := "3.1"
          // ... Your own settings here
    )

}
```

Plugin.sbt

```
// Comment to get more information during initialization
logLevel := Level.Warn

// The Typesafe repository 
resolvers += "Typesafe repository" at "http://repo.typesafe.com/typesafe/releases/"

// Use the Play sbt plugin for Play projects
addSbtPlugin("play" % "sbt-plugin" % "2.1.5")

addSbtPlugin("com.github.play2war" % "play2-war-plugin" % "1.1.1")
```

these are my settings files please tell me what I am missing ,how can I make it work  
I tried with both versions :1.0.5 and with 1.1.1 also but it is not working error is coming unable to found play2war-1.1.1 not found

**Comment by dlecan** [comment]
> `Play2WarKeys.servletVersion := "3.1"`

Servlet 3.1 engines support was added in Play2War v1.2.
Can you try with ``Play2WarKeys.servletVersion := "3.0"` ?
