### ISSUE TITLE
Unable to load class: ${database.driver}

### ISSUE THREAD

**Issue by iandow** [play2war/play2-war-plugin#303]
I've generated a war file for a play app that uses a postgres database driver, but when I deploy that to tomcat, the deploy fails and tomcat gives me an "Unable to load class: ${database.driver}" error.  My app works fine from the activator. How do I get Tomcat to pickup the database driver specified in build.sbt?

**Comment by dlecan** [comment]
Can you give more information ?
Play and Play2war versions, configuration files, full stacktraces...

**Comment by iandow** [comment]
I found that `sbt dist` serves my needs.

**Comment by dlecan** [comment]
Much better than deploying in an Application Server!
