### ISSUE TITLE
Servlet filters and Play Framework filters

### ISSUE THREAD

**Issue by cecton** [play2war/play2-war-plugin#309]
Hello,

I have a small question here for play2-war-plugin's developers.

I have built a caching filter using the Play framework 2.3.x and it works fine in a sample Play web application. But I wonder if it is possible to export this filter as a Servlet filter. If I understood properly, Servlet have a [filter mechanism](http://www.oracle.com/technetwork/java/filters-137243.html), but I don't think they are the same thing at all despite the purpose look very similar.

So, my question is: are the Play filters compatible at all with Servlet?

Best

**Comment by dlecan** [comment]
> are the Play filters compatible at all with Servlet

No, Play filters work only on Play. Play doesn't use a servlet engine, so servlet are useless for a "native" Play application.

With a Play2War application, servlet filters can be used. But Play filters do the work, so why would you want to change ?

**Comment by cecton** [comment]
It's because the application already exists and is not even written in Java, I want to put a cache on top of it. One way to do it would be to add a Servlet filter so every call made to this application would use the filter first.

**Comment by dlecan** [comment]
Good luck!
