### ISSUE TITLE
Version 1.4-beta1 without fix: 289: Transfer-Encoding chunked header duplicated

### ISSUE THREAD

**Issue by KoneFuzius** [play2war/play2-war-plugin#312]
Could the version "1.4-beta1" for Play 2.4.x be deployed with the bugfix #289 "Transfer-Encoding chunked header duplicated". Thjis bugfix was commited on on Jul 9, 2015. but the"1.4-beta1" version was deployed on Jun 14, 2015. :(

A new maven repo version of  on "1.4-beta1" would be great.

Thanks

**Comment by dlecan** [comment]
Already been fixed in ba8f293, so we "just" need a release.

**Comment by KoneFuzius** [comment]
could you please create a 1.4-beta2 release?

**Comment by dlecan** [comment]
It will be a v1.4.0 release.

**Comment by KoneFuzius** [comment]
Thanks! do you already know what date?

**Comment by dlecan** [comment]
Play2War 1.4.0 is available!
