### ISSUE TITLE
Play 2.0.1: /*:war: java.util.zip.ZipException: duplicate entry: WEB-INF/lib/play.play_2.9.1-2.0.1.jar

### ISSUE THREAD

**Issue by onyxraven** [play2war/play2-war-plugin#32]
With the upgrade to Play 2.0.1, both `play dist` and `play war` throw the following:

 % play dist  
[info] Loading project definition from /Users/jhart/dev/Server/project
[info] Set current project to Server (in build file:/Users/jhart/dev/Server/)
[error] {file:/Users/jhart/dev/Server/}Server/*:dist: java.util.zip.ZipException: duplicate entry:server-1.0-SNAPSHOT/lib/play.play_2.9.1-2.0.1.jar

 % play war  
[info] Loading project definition from /Users/jhart/dev/Server/project
[info] Set current project to Server (in build file:/Users/jhart/dev/Server/)
[info] Packaging /Users/jhart/dev/Server/target/scala-2.9.1/server_2.9.1-1.0-SNAPSHOT.jar ...
[info] Done packaging.
[error] {file:/Users/jhart/dev/Server/}Server/*:war: java.util.zip.ZipException: duplicate entry: WEB-INF/lib/play.play_2.9.1-2.0.1.jar

**Comment by dlecan** [comment]
I'am not able to reproduce this issue.

Can you provide a project test case ?

**Comment by dlecan** [comment]
Anyway, Play2War plugin is not binary compable with PLay 2.0.1. I will release a 0.3.1 version compatible with Play 2.0.1 (see bug #33)

**Comment by sejensen** [comment]
We are having the exact same issue with a completely empty new play project (2.0.1) and 0.3.1 version of the plugin.

**Comment by sejensen** [comment]
I added a very simple demo app that reproduces the problem

https://github.com/sejensen/play2-warplugin-error

We have tested on ubunto, osx, and others.

What to do?

**Comment by StabbarN** [comment]
I am seeing the same issue running "play dist" with play 2.0.1 and play email plugin (https://github.com/typesafehub/play-plugins/tree/master/mailer)

[error] {file:/Users/magnusandersson/x/}x/*:dist: java.util.zip.ZipException: duplicate entry: x-1.0-SNAPSHOT/lib/play.play_2.9.1-2.0.1.jar
[error] Total time: 3 s, completed May 16, 2012 11:21:11 AM

**Comment by dlecan** [comment]
Reproduced !
Thank you for this test case.

**Comment by pashazel** [comment]
dlecan, exactly the same problem is reproduced on win7 (32), play 2.0.1, war 0.3.1, Thanks!

**Comment by saveferris** [comment]
I am seeing this same error with Play 2.0.1 -- my only plugins are:

// Use the Play sbt plugin for Play projects.
addSbtPlugin("play" % "sbt-plugin" % "2.0.1")

// This plugin lets us configure Eclipse IDE projects with the "eclipse" command.
addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse-plugin" % "2.0.0")

**Comment by dlecan** [comment]
"dist" and "war" tasks are very similar, this is why they are probably affected by the same bug.
However, I can't do anything for issues with "dist" task which is provided by Play itself.

@YeaYeah @saveferris, as several plugins produce the same bug ("sbt-eclipse", "email"), it would be great to report it to Play framework issue tracker :
https://play.lighthouseapp.com/projects/82401-play-20

Beta version of Play2 has already had a similar issue in the past (https://play.lighthouseapp.com/projects/82401/tickets/70-play-dist-is-broken-with-unmanaged-dependencies).

**Comment by StabbarN** [comment]
It's reported to play framework's issue tracker.
https://play.lighthouseapp.com/projects/82401/tickets/486-old-issue-play-dist
