### ISSUE TITLE
play2-war-plugin issue with Play 2.8.2

### ISSUE THREAD

**Issue by nikam03** [play2war/play2-war-plugin#327]
Hi,

Im new to Play framework. Im trying to migrate application from PLay 2.0 to 2.8.2

Project has Build.scala
build.properties : sbt.version=1.3.4

plugin.sbt: 
logLevel := Level.Warn

// The Typesafe repository
resolvers += "Typesafe repository" at "http://repo.typesafe.com/typesafe/releases/"

// Use the Play sbt plugin for Play projects
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.8.2")
//addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse-plugin" % "5.2.4")

resolvers += "Play2war plugins release" at "http://repository-play-war.forge.cloudbees.com/release/"

addSbtPlugin("com.github.play2war" % "play2-war-plugin" % "0.8.1")

Error: 

[warn] insecure HTTP request is deprecated 'http://repo.typesafe.com/typesafe/releases/'; switch to HTTPS or opt-in as ("Typesafe repository" at "http://repo.typesafe.com/typesafe/releases/").withAllowInsecureProtocol(true)
[warn] insecure HTTP request is deprecated 'http://repository-play-war.forge.cloudbees.com/release/'; switch to HTTPS or opt-in as ("Play2war plugins release" at "http://repository-play-war.forge.cloudbees.com/release/").withAllowInsecureProtocol(true)
[warn] insecure HTTP request is deprecated 'http://repository-play-war.forge.cloudbees.com/release/'; switch to HTTPS or opt-in as ("Play2war plugins release" at "http://repository-play-war.forge.cloudbees.com/release/").withAllowInsecureProtocol(true)
[warn] insecure HTTP request is deprecated 'http://repo.typesafe.com/typesafe/releases/'; switch to HTTPS or opt-in as ("Typesafe repository" at "http://repo.typesafe.com/typesafe/releases/").withAllowInsecureProtocol(true)
[warn] 
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]          com.github.play2war:play2-war-plugin:0.8.1 (sbtVersion=1.0, scalaVersion=2.12)
[warn] 
[warn]  Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading com.github.play2war:play2-war-plugin;sbtVersion=1.0;scalaVersion=2.12:0.8.1
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/com/github/play2war/play2-war-plugin_2.12_1.0/0.8.1/play2-war-plugin-0.8.1.pom
[error]   not found: /home/pair.station/.ivy2/local/com.github.play2war/play2-war-plugin/scala_2.12/sbt_1.0/0.8.1/ivys/ivy.xml
[error]   download error: Caught java.net.UnknownHostException: repository-play-war.forge.cloudbees.com (repository-play-war.forge.cloudbees.com) while downloading http://repository-play-war.forge.cloudbees.com/release/com/github/play2war/play2-war-plugin_2.12_1.0/0.8.1/play2-war-plugin-0.8.1.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.github.play2war/play2-war-plugin/scala_2.12/sbt_1.0/0.8.1/ivys/ivy.xml
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/com.github.play2war/play2-war-plugin/scala_2.12/sbt_1.0/0.8.1/ivys/ivy.xml
[error]   download error: Caught java.net.ConnectException: Connection refused (Connection refused) (Connection refused (Connection refused)) while downloading http://repo.typesafe.com/typesafe/releases/com/github/play2war/play2-war-plugin_2.12_1.0/0.8.1/play2-war-plugin-0.8.1.pom
[error]         at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:245)
[error]         at lmcoursier.CoursierDependencyResolution.$anonfun$update$34(CoursierDependencyResolution.scala:214)
[error]         at scala.util.Either$LeftProjection.map(Either.scala:573)
[error]         at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:214)
[error]         at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error]         at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:52)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:102)
[error]         at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:69)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:115)
[error]         at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:115)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:96)
[error]         at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
[error]         at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:129)
[error]         at sbt.Classpaths$.$anonfun$updateTask0$5(Defaults.scala:2946)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error]         at sbt.Execute.work(Execute.scala:290)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:834)
[error] (update) sbt.librarymanagement.ResolveException: Error downloading com.github.play2war:play2-war-plugin;sbtVersion=1.0;scalaVersion=2.12:0.8.1
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/com/github/play2war/play2-war-plugin_2.12_1.0/0.8.1/play2-war-plugin-0.8.1.pom
[error]   not found: /home/pair.station/.ivy2/local/com.github.play2war/play2-war-plugin/scala_2.12/sbt_1.0/0.8.1/ivys/ivy.xml
[error]   download error: Caught java.net.UnknownHostException: repository-play-war.forge.cloudbees.com (repository-play-war.forge.cloudbees.com) while downloading http://repository-play-war.forge.cloudbees.com/release/com/github/play2war/play2-war-plugin_2.12_1.0/0.8.1/play2-war-plugin-0.8.1.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.github.play2war/play2-war-plugin/scala_2.12/sbt_1.0/0.8.1/ivys/ivy.xml
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/com.github.play2war/play2-war-plugin/scala_2.12/sbt_1.0/0.8.1/ivys/ivy.xml
[error]   download error: Caught java.net.ConnectException: Connection refused (Connection refused) (Connection refused (Connection refused)) while downloading http://repo.typesafe.com/typesafe/releases/com/github/play2war/play2-war-plugin_2.12_1.0/0.8.1/play2-war-plugin-0.8.1.pom
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 2020-10-23 13:21:57,328 

1. I have tried to change version in plugin.sbt from 0.8.2 as this version is available  in repository
https://repo1.maven.org/maven2/com/github/play2war/play2-war_2.9.1/0.8.2/

2. https://github.com/play2war/play2-war-plugin/blob/develop/README.md states, 
Play 2.5.x          : Not supported yet

**Comment by valdar** [comment]
As you might have notice the project is not that active any more, see https://github.com/play2war/play2-war-plugin/issues/321
your best shot is trying to manually build the mentioned branch: https://github.com/play2war/play2-war-plugin/tree/321_play_2_6
hoping that it is a good base to support 2.8.2.

**Comment by nikam03** [comment]
Thanks @valdar for the quick reply. 
is there any other packing plugin available which support 2.8.2 ?

**Comment by valdar** [comment]
Not that I am aware of, do you need to package as war? Do you have other options?

**Comment by nikam03** [comment]
Hi @valdar ,

I have figured out way to package and ran from any location<other than target location where zip is generated> on Ubantu machine.

Just followed this https://www.playframework.com/documentation/2.8.x/Deploying

zip is packaged with all required jars including in built Netty Server and  it did worked :) 

Cheers,Thanks.
