### ISSUE TITLE
play2war plugin 0.3.1 not found

### ISSUE THREAD

**Issue by tisoft** [play2war/play2-war-plugin#34]
[warn] ==== Play2war plugins release: tried
[warn]   http://repository-play-war.forge.cloudbees.com/release/com/github/play2war/play2-war-plugin_2.9.1_0.11.2/0.3.1/play2-war-plugin-0.3.1.pom

[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.github.play2war#play2-war-plugin;0.3.1: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::

The download URL gives a 404 error.

**Comment by dlecan** [comment]
Thank you for reporting this.
I re-uploaded all artifacts. It should be ok now.
