### ISSUE TITLE
War error

### ISSUE THREAD

**Issue by tm4rini** [play2war/play2-war-plugin#35]
Hello

I'm having little problem with the application to deploy in tomcat
I initially could generate the WAR file using the command "play war" and realized deploy on tomcat 7.0.12 without error .... But when I try to access http://localhost:8080/testewar-1.0-SNAPSHOT/ generate the error HTTP Status 404 - / testewar-1.0-SNAPSHOT /

follow the link to download the WAR file
http://depositfiles.com/files/tb22mhj9i

**Comment by dlecan** [comment]
Play 2.0.x framework doesn't handle sub context, so the same app packaged in a war file doesn't too (See https://github.com/dlecan/play2-war-plugin#features).
Play 2.1 will handle sub context.

You have to deploy your WAR file as the root context. For Tomcat, just rename your war file as "ROOT.war" and drop it into webapps folder.
Start Tomcat and then open http://localhost:8080/
