### ISSUE TITLE
War demo

### ISSUE THREAD

**Issue by tm4rini** [play2war/play2-war-plugin#36]
hello

you have to send the war of the test:
http://play2war.jelastic.dogado.eu/

**Comment by dlecan** [comment]
Sources of demo are available here: https://github.com/dlecan/play2-war-plugin/tree/develop/sample
You can download directly the last build of theses sources here: https://play-war.ci.cloudbees.com/job/Play_2_War_-_on_push_-_with_integration_tests_-_on_develop_branch/ws/sample/target/a_warification-1.0-SNAPSHOT.war
