### ISSUE TITLE
Impossible to upload files

### ISSUE THREAD

**Issue by asinghal** [play2war/play2-war-plugin#37]
I have deployed a play-war generated play 2 scala application on Tomcat 7. I am facing the following issues.
1. Multipart form data does not work
   I have a HTML form defined as <form method="POST" action="/myaction" id="my_form" class="form-horizontal" enctype="multipart/form-data"> </form>

It has a couple of inputs inside. even if I do not upload a file, I still get a BadRequest - dump as follows: 
Map(HOST -> non-empty iterator, ACCEPT-ENCODING -> non-empty iterator, 
ACCEPT-LANGUAGE -> non-empty iterator, REFERER -> non-empty iterator, 
CONTENT-LENGTH -> non-empty iterator, ORIGIN -> non-empty iterator, 
ACCEPT-CHARSET -> non-empty iterator, CONNECTION -> non-empty 
iterator, CONTENT-TYPE -> empty iterator, CACHE-CONTROL -> non-empty 
iterator, ACCEPT -> non-empty iterator, COOKIE -> empty iterator, USER- 
AGENT -> non-empty iterator) Map(__utmc -> Cookie(__utmc, 
84437902,-1,/,None,false,false), __utmz -> Cookie(__utmz, 
84437902.1337318013.1.1.utmcsr,-1,/,None,false,false), PLAY_SESSION -> 
Cookie(PLAY_SESSION,11cd5ffd7e2b56910a6a118e0de60be50c963697-email 
%3Axxxxxxxxxxx,-1,/,None,false,false), __utma -> Cookie(__utma, 
84437902.1740292094.1337318013.1337510573.1337583859.6,-1,/,None,false,fals e), 
__utmb -> Cookie(__utmb, 
84437902.2.10.1337583859,-1,/,None,false,false))' [Missing boundary 
header] 
I wonder why the CONTENT-TYPE shows up as empty here and if thats the 
problem. The framework seems to be identifying that this was multipart 
request though so I assume the inputs were received correctly. 

can you please check?
1. Logger is not configured
   Play logger is not configured and logs are not captured on tomcat

**Comment by dlecan** [comment]
How does your form template look like ? And your controller ?

**Comment by dlecan** [comment]
Here is a kind of form to reproduce the issue:

``` html
<form method="POST" action="/create" enctype="multipart/form-data">
  <input type="file" name="logo" id="logo" />
  <input type="submit" value="Save Details" />
</form>
```
