### ISSUE TITLE
Standalone deployment ?

### ISSUE THREAD

**Issue by gcardoso22** [play2war/play2-war-plugin#41]
Just wondering whats does "Standalone deployment" mean in the "Server compatibility" matrix?
Does this mean that I can simply create a war file using and "play war" and place that WAR in my recently installed JBoss AS 7 in "C:\jboss-as-7.1.0.Final\standalone\deployments" ?
Or do I need to install some plugin/module/dependency into my JBoss server?

Because I can install the WAR without errors, but when I try to use the application at
   http://127.0.0.1:9082/myproject-1.0-SNAPSHOT/
I get the following error

HTTP Status 404 - /myproject-1.0-SNAPSHOT/
type Status report
message /myproject-1.0-SNAPSHOT/
description The requested resource (/myproject-1.0-SNAPSHOT/) is not available.
JBoss Web/7.0.10.Final

**Comment by dlecan** [comment]
I haven't tested on JBoss 7.1.x yet, only on JBoss 7.0.x.

Some basic configuration has to be done on JBoss 7.0.x to avoid conflicts between embedded Play librairies and JBoss ones. I have to write a documentation about this configuration (see #42).

Anyway, Play framework v2.0.x doesn't allow to deploy applications in a sub-context: they must be deployed at root context. So your application must be deployed at root context of JBoss.

How to deploy to root context ? With a [WEB-INF/jboss-web.xml](https://community.jboss.org/wiki/SetupARootContextApp), but automatic inclusion of config file is not supported by Play2War plugin yet (see #4 planned for v0.5).

**Comment by dlecan** [comment]
I improved README.
See https://github.com/dlecan/play2-war-plugin#how-to-deploy-in-your-favortie-application-server for explanations.
