### ISSUE TITLE
Images and css not loading and links not working

### ISSUE THREAD

**Issue by OpsRJ** [play2war/play2-war-plugin#43]
I tested the plugin yesterday and was very easy to deploy on tomcat7. But when the app loads, it didnt load the images and styles. I realize when i'm running itwith tomcat, i need the addr to be localhost:8080/app-name and in the source code, if i see the img addr is /assets/images/massagem.jpg

But for it to work i need the full addr. How can i fix it?

**Comment by dlecan** [comment]
Play framework applications 2.0.x must be deployed ar root context.
See https://github.com/dlecan/play2-war-plugin#how-to-deploy-in-your-favortie-application-server for explanations.
