### ISSUE TITLE
Plugin must be compatible with Play 2.0.2

### ISSUE THREAD

**Issue by dlecan** [play2war/play2-war-plugin#56]

**Comment by rore** [comment]
Any progress with 2.0.2 compatibility?

**Comment by dlecan** [comment]
Changing SBT version in a minor release of Play is a pity. I need to do a new release of Play2War with configuration modifications in order to support Play 2.0.2 + SBT 0.11.3

Is it a major issue for you ?

**Comment by rore** [comment]
Well, it prevents updating play to 2.0.2 if you use the war plugin (which
we do), and since 2.0.2 contains some important bug fixes I would be glad
to update to it.

On Wed, Jun 27, 2012 at 4:44 PM, Damien Lecan <
reply@reply.github.com

**Comment by sejensen** [comment]
I would really like to have this updated as well!

We need it to deploy on our production environment.

Thanks

**Comment by dlecan** [comment]
Play API has evolve, I will have to do a special release for it. I will have to think about how to support all multiple and incompatible Play versions ...

```
[error] /play2war/project-code/core/src/main/scala/Servlet30Wrapper.scala:49: object creation impossible, since method remoteAddress in trait RequestHeader of type => String is not defined
[error]     val requestHeader = new RequestHeader {
[error]                             ^
[error] /play2war//project-code/core/src/main/scala/Servlet30Wrapper.scala:246: object creation impossible, since method remoteAddress in trait RequestHeader of type => String is not defined
[error]                 new Request[action.BODY_CONTENT] {
[error]                     ^
[error] two errors found
```

**Comment by dlecan** [comment]
Play2War v0.6 with Play 2.0.2 support has been released.

**Comment by rore** [comment]
Awesome!
Thanks.

On Sat, Jun 30, 2012 at 7:07 PM, Damien Lecan <
reply@reply.github.com
