### ISSUE TITLE
[Tomcat 7] Production configuration ?

### ISSUE THREAD

**Issue by marcosinigaglia** [play2war/play2-war-plugin#58]
In standalone deployment is possible to set a specific configuration file with -Dconfig.resource=produtcion.conf
Is possible to do a similar thing with the plugin?

**Comment by dlecan** [comment]
`-Dconfig.resource=my_file.conf` is a JVM configuration configuration flag, so yes, you can do a similar thing with your servlet container.
But configuration is specific to your servlet container. Which one is it ?

**Comment by marcosinigaglia** [comment]
We use Tomcat 7

**Comment by dlecan** [comment]
Look at `bin/catalina.bat` and environment variables `JAVA_OPTS` or `CATALINA_OPTS`. They can be defined by a `setenv.bat` file (see http://serverfault.com/questions/79641/how-can-i-configure-tomcat-java-options-in-a-config-file).

**Comment by marcosinigaglia** [comment]
Thanks Damien
