### ISSUE TITLE
How to handle UTF-8 non-english characters in query string ?

### ISSUE THREAD

**Issue by rore** [play2war/play2-war-plugin#62]
(This is a cross-post from the play2 google group, I have a feeling it's connected to the war plugin and not play itself).

I'm having an issue with query strings parameter values which are non-english.
When running under local play server the value is decoded correctly to the proper value.
When deploying under Tomcat (using the war plugin) the value is not decoded correctly.

Example:
I have a url -

http://local/test.json?q=%D7%90%D7%A8%D7%99%D7%A7
on my local play server I get the "q" value as the word it really is.
under a Tomcat container I get "××¨××§" instead of the actual value. 

Another issue under tomcat that could be connected - when I access the uri under the request I don't get the query string (even when it contains only English...).
That is, request.uri under local play returns "test.json?q=%D7%90%D7%A8%D7%99%D7%A7".
Under Tomcat it returns only "test.json", although the query parameter values do get analyzed as the function parameters.

**Comment by dlecan** [comment]
I need the following versions:
- Play2War
- Tomcat
- JVM

What does "%D7%90%D7%A8%D7%99%D7%A7" mean ?

**Comment by rore** [comment]
play2war - 0.6
tomcat 7
OpenJDK 1.6.0_20

(EC2 machine)

On Tue, Jul 3, 2012 at 11:10 PM, Damien Lecan <
reply@reply.github.com

**Comment by rore** [comment]
sorry, didn't see the last question. it's the url encoded version of the Hebrew "אריק".

**Comment by dlecan** [comment]
Does it work with a standard servlet application deployed on Tomcat ?
I would like to be sure this issue is coming from Play2War and not from Tomcat configuration.

**Comment by rore** [comment]
OK, I did a little more digging. It is a problem with Tomcat configuration,
as the Tomcat on my server is not configured to be UTF-8 on the server
level.

The problem is that I don't control the server configuration. There is a
workaround though on an application level, that requires configuring some
filters on the web.xml on the application.

But I see that the war plugin doesn't create a web.xml file (and also I
can't control it). Can you think of a way to configure a filter chain for
the application even with the war plugin?

On Wed, Jul 4, 2012 at 10:36 AM, Damien Lecan <
reply@reply.github.com

**Comment by dlecan** [comment]
This will be possible with Play2War v0.7: embed custom files in generated war (such as web.xml)
https://github.com/dlecan/play2-war-plugin/issues?milestone=12

**Comment by rore** [comment]
Awesome!
Any idea on when 0.7 will be ready?
And another question - how should the servlet in the web.xml be defined?
I've tried manually adding web.xml to the generated war but then the
application didn't start (as I'm not sure how not to kill the current
servlet mapping).

On Wed, Jul 4, 2012 at 2:42 PM, Damien Lecan <
reply@reply.github.com

**Comment by dlecan** [comment]
> Any idea on when 0.7 will be ready?
> When it will be finished :) With summer holidays, probably at the end of august.

Embed custom file feature is already in "develop" branch, so you can try snapshot build of the plugin.

Until there, you can try adding by yourself a web.xml, configured for Servlet 3.0 container.
See http://stackoverflow.com/questions/9966655/servlet-3-0-webservlet-use-what-will-be-in-web-xml for web.xml headers.

**Comment by rore** [comment]
Cool, thanks.

On Wed, Jul 4, 2012 at 3:19 PM, Damien Lecan <
reply@reply.github.com

**Comment by sejensen** [comment]
Did you solve this? and how 

Because it seems like we have the same issue with play-war plugin and danish letters æøå in get query.

Kind regards
Steffen

**Comment by rore** [comment]
See this question in stackoverflow, it contains a code for a query-string
parser filter that handles UTF-8 that can be used in the application
context without needing to set the connector on the global tomcat
configuration.
I haven't combined this with play2-war yet, only verified this filter
works, but basically I think adding it to the war should solve this issue.

On Mon, Jul 9, 2012 at 10:19 PM, sejensen <
reply@reply.github.com

**Comment by rore** [comment]
Ah, a link could be useful.
http://stackoverflow.com/questions/2657515/detect-the-uri-encoding-automatically-in-tomcat

**Comment by sejensen** [comment]
Thank you very much.

If I have full control over the server, is there then an easier solution to this problem?

Kind regards
Steffen

**Comment by rore** [comment]
Yes, see here - http://wiki.apache.org/tomcat/FAQ/CharacterEncoding

On Mon, Jul 9, 2012 at 10:40 PM, sejensen <
reply@reply.github.com

**Comment by sejensen** [comment]
Thank you!

I will try to change that instead.
Steffen

**Comment by dlecan** [comment]
If you need to add servlet/filters in your application, you don't need to wait Play2War 0.7 and "embed custom file such as web.xml" feature.

You can add them programmatically:
http://www.softwareengineeringsolutions.com/blogs/2010/08/01/programmatic-definition-of-components-in-servlet-specification-3-0/

Put your code in `PROJECT/app` folder, servlet 3.0 library is already in your Play application classpath.

**Comment by sejensen** [comment]
Hi everyone

Adding a web.xml to JBoss 7+ (or eap 6 as we use) to the project solved det problem

Content of web.xml (remember web-app header and async-supported true)

```
<filter>
    <filter-name>encodingFilter</filter-name>
    <filter-class>org.apache.catalina.filters.SetCharacterEncodingFilter</filter-class>
    <init-param>
        <param-name>encoding</param-name>
        <param-value>utf-8</param-value>
    </init-param>
    <async-supported>true</async-supported>
</filter>

<filter-mapping>
  <filter-name>encodingFilter</filter-name>
  <url-pattern>/*</url-pattern>
</filter-mapping>
```

   And in the configuration ie. standalone.xml add system properties just after extensions, see here https://community.jboss.org/message/643825#643825

**Comment by rore** [comment]
Thanks Damien, that's a nice tip!

**Comment by rore** [comment]
I see the customizable web.xml feature has been added to the 0.7.X version.
So how do I specify a web.xml? Where should it be placed inside the project?

**Comment by rore** [comment]
Never mind, found it :-)
If anyone encounters this, you should place a directory called "war" under your project root and add the WEB-INF/web.xml under it.

**Comment by dlecan** [comment]
@rore you're right, documentation was missing. Available here: https://github.com/dlecan/play2-war-plugin/blob/develop/README.md#embed-custom-war-configuration-files

**Comment by rore** [comment]
Cool, thanks.
