### ISSUE TITLE
web.xml configuration with basic authentication ?

### ISSUE THREAD

**Issue by Byr** [play2war/play2-war-plugin#63]
Im new with the use of play2-war-plugin , i downloaded version 0.5.

I would like to create a  web.xml file for my project war.:

I know that play.server.ServletWrapper is not anymore on play version 2.0 , but i would like to know if there is another way to do something  like the following:

---

<?xml version="1.0" ?>
<web-app xmlns="http://java.sun.com/xml/ns/j2ee"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://java.sun.com/xml/ns/j2ee http://java.sun.com/xml/ns/j2ee/web-app_2_4.xsd"
        version="2.4">

  <context-param>
    <param-name>play.id</param-name>
    <param-value>%PLAY_ID%</param-value>
  </context-param>

  <listener>
      <listener-class>play.server.ServletWrapper</listener-class>
  </listener>

  <servlet>
    <servlet-name>play</servlet-name>
    <servlet-class>play.server.ServletWrapper</servlet-class>  
  </servlet>

```
<servlet-mapping>
    <servlet-name>TestServlet</servlet-name>
    <url-pattern>/test</url-pattern>
</servlet-mapping>

  <servlet-mapping>
    <servlet-name>play</servlet-name>
    <url-pattern>/</url-pattern>
  </servlet-mapping>

<security-constraint>
    <web-resource-collection>
        <web-resource-name>Wildcard means whole app requires authentication</web-resource-name>
        <url-pattern>/*</url-pattern>
        <http-method>GET</http-method>
        <http-method>POST</http-method>
    </web-resource-collection>
    <auth-constraint>
        <role-name>tomcat</role-name>
    </auth-constraint>

    <user-data-constraint>
        <!-- transport-guarantee can be CONFIDENTIAL, INTEGRAL, or NONE -->
        <transport-guarantee>NONE</transport-guarantee>
    </user-data-constraint>
</security-constraint>

<login-config>
    <auth-method>BASIC</auth-method>
</login-config>
```

</web-app>

---

Thank you.

**Comment by dlecan** [comment]
This will be possible with Play2War v0.7: embed custom files in generated war (such as web.xml)
https://github.com/dlecan/play2-war-plugin/issues?milestone=12

**Comment by dlecan** [comment]
Notice that, as of v0.6, Play2War is only compatible with Play 2.0.2+

**Comment by Byr** [comment]
Thanks for the fast response, i will be expecting v 0.7
