### ISSUE TITLE
HELP on ERROR "module not found: com.github.play2war#play2-war-plugin;0.7"

### ISSUE THREAD

**Issue by matgi** [play2war/play2-war-plugin#69]
Hello,
i'm developing a web app using play 2.0.2.
I tried to set up the play2-war-plugin following the istructions...
but unfortunatly when i run the play package command i obtain this error (it seems a compilation error infact the play compile give the same result):

D:\jdevNew\sorgenti\produzione\AdiuWEB>play package
[info] Loading project definition from D:\jdevNew\sorgenti\produzione\AdiuWEB\project\project
[info] Loading project definition from D:\jdevNew\sorgenti\produzione\AdiuWEB\project
[warn]  module not found: com.github.play2war#play2-war-plugin;0.7
[warn] ==== typesafe-ivy-releases: tried
[warn]   http://repo.typesafe.com/typesafe/ivy-releases/com.github.play2war/play2-war-plugin/scala_2.9.1/sbt_0.11.3/0.7/ivys/ivy.xml
[warn] ==== local: tried
[warn]   D:\play-2.0.2\framework..\repository/local/com.github.play2war/play2-war-plugin/scala_2.9.1/sbt_0.11.3/0.7/ivys/ivy.xml
[warn] ==== Typesafe repository: tried
[warn]   http://repo.typesafe.com/typesafe/releases/com/github/play2war/play2-war-plugin_2.9.1_0.11.3/0.7/play2-war-plugin-0.7.pom
[warn] ==== Play2war plugins release: tried
[warn]   http://repository-play-war.forge.cloudbees.com/release/com/github/play2war/play2-war-plugin_2.9.1_0.11.3/0.7/play2-war-plugin-0.7.pom
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/com/github/play2war/play2-war-plugin_2.9.1_0.11.3/0.7/play2-war-plugin-0.7.pom
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.github.play2war#play2-war-plugin;0.7: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]          com.github.play2war:play2-war-plugin:0.7 (sbtVersion=0.11.3, scalaVersion=2.9.1)
[warn]
[error] {file:/D:/jdevNew/sorgenti/produzione/AdiuWEB/project/}default-5ce1fb/*:update: sbt.ResolveException: unresolved dependency: com.github.play2war#play2-war-plugin;0.7: not found
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? q

Do you know how to fix the problem?
Thanx in advice,
Matgi.

**Comment by dlecan** [comment]
Is your Internet connection ok?
This link works great for me, but your SBT build doesn't seem to find it:

http://repository-play-war.forge.cloudbees.com/release/com/github/play2war/play2-war-plugin_2.9.1_0.11.3/0.7/play2-war-plugin-0.7.pom

Are you behind a proxy?
Le 6 août 2012 12:53, "matgi" <
reply@reply.github.com>
a écrit :

**Comment by matgi** [comment]
thanx,
unfortunatly i'm under a proxy but i've already do the set HTTP_PROXY=....
A college of mine also try the plug in outisde the proxy and he's obtain the same error we test try the plug in on the forms sample app unser samples\java.
Do you know what's going on? In case could you please send me a war package example just to see the internal structure of the war?

**Comment by dlecan** [comment]
Does the previously provided link work in your browser? 

Anyway, you can find built war samples here:

https://play-war.ci.cloudbees.com/job/Play_2_War_-_on_push_-_with_integration_tests_-_on_develop_branch/ws/sample/servlet30/target/

Or 

https://play-war.ci.cloudbees.com/job/Play_2_War_-_on_push_-_with_integration_tests_-_on_develop_branch/ws/sample/servlet25/target/

**Comment by matgi** [comment]
Yes the http://repository-play-war.forge.cloudbees.com/release/com/github/play2war/play2-war-plugin_2.9.1_0.11.3/0.7/play2-war-plugin-0.7.pom is reachable...
sincerely i don't understand where is the problem. :(
Maybe i have some strange settings in my project, but i follow the istructions step by step.
I'm developing using eclipse on windows 7 ,using play java api and the goal is to deploy on jboss.

thanx.

**Comment by dlecan** [comment]
Please copy/paste your Build.scala and plugin.sbt files in this issue. Thanks.

**Comment by matgi** [comment]
------------------------------------------------Build.scala-------------------------------------------------------

``` scala
import sbt._
import Keys._
import PlayProject._
import com.github.play2war.plugin._

object ApplicationBuild extends Build {

    val appName         = "forms"
    val appVersion      = "1.0"

    val appDependencies = Seq(
      // Add your project dependencies here,
    )

    /*
    val main = PlayProject(appName, appVersion, appDependencies, mainLang = JAVA).settings(
      // Add your own project settings here      
    )*/



    val projectSettings = Play2WarPlugin.play2WarSettings ++ Seq(
      // Your settings
       Play2WarKeys.servletVersion := "3.0"
    )

    ...

    val main = PlayProject(
       appName, appVersion, appDependencies, mainLang = JAVA
    ).settings(projectSettings: _*)



}
```

------------------------------------------------plugins.sbt-------------------------------------------------------

``` scala
// Comment to get more information during initialization
logLevel := Level.Warn

// The Typesafe repository
resolvers += "Typesafe repository" at "http://repo.typesafe.com/typesafe/releases/"

// Use the Play sbt plugin for Play projects
addSbtPlugin("play" % "sbt-plugin" % Option(System.getProperty("play.version")).getOrElse("2.0"))


resolvers += "Play2war plugins release" at "http://repository-play-war.forge.cloudbees.com/release/"

addSbtPlugin("com.github.play2war" % "play2-war-plugin" % "0.7")
```

THANX.

**Comment by dlecan** [comment]
> plugins.sbt
> 
> addSbtPlugin("play" % "sbt-plugin" %
> Option(System.getProperty("play.version")).getOrElse("2.0"))

Not correct, if you want to use Play2war 0.7, you must configure Play
runtime 2.0.2 instead of 2.0.

Correct configuration :
addSbtPlugin("play" % "sbt-plugin" % "2.0.2")

**Comment by matgi** [comment]
unfortunatly it doesn't work

 ------------------------------------------------plugins.sbt-------------------------------------------------------

``` scala
// Comment to get more information during initialization
logLevel := Level.Warn

// The Typesafe repository
resolvers += "Typesafe repository" at "http://repo.typesafe.com/typesafe/releases/"

// Use the Play sbt plugin for Play projects
addSbtPlugin("play" % "sbt-plugin" % "2.0.2")

resolvers += "Play2war plugins release" at "http://repository-play-war.forge.cloudbees.com/release/"

addSbtPlugin("com.github.play2war" % "play2-war-plugin" % "0.7")*
```

maybe there's something missing in my environment?
...sbtPlugin...
sorry but i'm newbie using that kind of stuff (actually i've developed in different environment Castle Project / Monorail etc...)

thanx in advice,
Matteo.

**Comment by dlecan** [comment]
Did you notice how to configure HTTP proxy with SBT ?
https://github.com/harrah/xsbt/wiki/Setup-Notes (section "HTTP Proxy")

**Comment by szuzul** [comment]
Hi there,
I'm having exact problem, and I'm also using proxy in my connection to internet. I already install some of the plugins through the proxy, so I'm sure that my proxy preferences are ocky in config files. I have used https://github.com/harrah/xsbt/wiki/Setup-Notes instructions to setup files, but the result is the same like Mateos log.

Is there a chance to download and build the plugin manual from the https://github.com/dlecan/play2-war-plugin, what are the procedures? 

Best regards, 

Stjepan

**Comment by szuzul** [comment]
My sbt version is 0.11.2 not .3 like in Matteo case. Here is my log: 
[info] Loading project definition from C:\workspace\HelloWorldWeb\project
[warn]  module not found: play#sbt-plugin;2.0.2
[warn] ==== typesafe-ivy-releases: tried
[warn]   http://repo.typesafe.com/typesafe/ivy-releases/play/sbt-plugin/scala_2.
9.1/sbt_0.11.2/2.0.2/ivys/ivy.xml
[warn] ==== local: tried
[warn]   C:\Java\play-2.0.1\framework..\repository/local/play/sbt-plugin/scala_
2.9.1/sbt_0.11.2/2.0.2/ivys/ivy.xml
[warn] ==== Typesafe repository: tried
[warn]   http://repo.typesafe.com/typesafe/releases/play/sbt-plugin_2.9.1_0.11.2
/2.0.2/sbt-plugin-2.0.2.pom
[warn] ==== Play2war plugins release: tried
[warn]   http://repository-play-war.forge.cloudbees.com/release/play/sbt-plugin_
2.9.1_0.11.2/2.0.2/sbt-plugin-2.0.2.pom
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/play/sbt-plugin_2.9.1_0.11.2/2.0.2/sbt-pl
ugin-2.0.2.pom
[warn] ==== Scala-Tools Maven2 Repository: tried
[warn]   http://scala-tools.org/repo-releases/play/sbt-plugin_2.9.1_0.11.2/2.0.2
/sbt-plugin-2.0.2.pom
[warn]  module not found: com.github.play2war#play2-war-plugin;0.7.2
[warn] ==== typesafe-ivy-releases: tried
[warn]   http://repo.typesafe.com/typesafe/ivy-releases/com.github.play2war/play
2-war-plugin/scala_2.9.1/sbt_0.11.2/0.7.2/ivys/ivy.xml
[warn] ==== local: tried
[warn]   C:\Java\play-2.0.1\framework..\repository/local/com.github.play2war/pl
ay2-war-plugin/scala_2.9.1/sbt_0.11.2/0.7.2/ivys/ivy.xml
[warn] ==== Typesafe repository: tried
[warn]   http://repo.typesafe.com/typesafe/releases/com/github/play2war/play2-wa
r-plugin_2.9.1_0.11.2/0.7.2/play2-war-plugin-0.7.2.pom
[warn] ==== Play2war plugins release: tried
[warn]   http://repository-play-war.forge.cloudbees.com/release/com/github/play2
war/play2-war-plugin_2.9.1_0.11.2/0.7.2/play2-war-plugin-0.7.2.pom
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/com/github/play2war/play2-war-plugin_2.9.
1_0.11.2/0.7.2/play2-war-plugin-0.7.2.pom
[warn] ==== Scala-Tools Maven2 Repository: tried
[warn]   http://scala-tools.org/repo-releases/com/github/play2war/play2-war-plug
in_2.9.1_0.11.2/0.7.2/play2-war-plugin-0.7.2.pom
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: play#sbt-plugin;2.0.2: not found
[warn]  :: com.github.play2war#play2-war-plugin;0.7.2: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that th
ese dependencies exist with the requested attributes.
[warn]          play:sbt-plugin:2.0.2 (sbtVersion=0.11.2, scalaVersion=2.9.1)
[warn]          com.github.play2war:play2-war-plugin:0.7.2 (sbtVersion=0.11.2, s
calaVersion=2.9.1)
[warn]
[error] {file:/C:/workspace/HelloWorldWeb/project/}default-efb0c2/*:update: sbt.
ResolveException: unresolved dependency: play#sbt-plugin;2.0.2: not found
[error] unresolved dependency: com.github.play2war#play2-war-plugin;0.7.2: not f
ound

**Comment by dlecan** [comment]
@szuzul Sbt version has changed since Play 2.0.2 (used to be 0.11.2, now is 0.11.3).

Each Play version has a corresponding Play2War version because of Sbt. 

So with Sbt 0.11.2, you're stick to Play 2.0.1 and Play2War 0.5.

If you need Play2War 0.7.x, please upgrade to Play 2.0.2 (and so Sbt 0.11.3).

Does it work now?

**Comment by szuzul** [comment]
Hi, thanks for the response... I'm packing the files now correct, it was the version issue, I didn't saw dependencies  for 0.7.2 version..Packing is working now but, I have problems now with Logger when I'm starting my Tomcat 7 can I post the problem here or is it for Google Play framework group ?

**Comment by dlecan** [comment]
@matgi Any news on this issue ?

**Comment by matgi** [comment]
Hello unfortunatly the command doesn't work. At the moment we have an ant script who create the war.

**Comment by dlecan** [comment]
@matgi What happens when you add custom dependencies ? Does it work ?

Such as :

``` scala
val projectSettings = Play2WarPlugin.play2WarSettings ++ Seq(
  ...
  libraryDependencies += "javax.servlet" % "javax.servlet-api" % "3.0.1"
  ...
)
```

**Comment by matgi** [comment]
No at the moment we use tha ant script beacuse it creates an ear archive with a jar (for backend using ejdb) and a war for the frontEnd (play web app)
Everythings works fine but i have the logger problem on JBOSS7. I saw you solve it. Could you please send a war archive example with the logger issue solved?
thanx.

**Comment by matgi** [comment]
maybe the problem of the plug in is related to the sbt but at moment we are in emergency... and my knowledge on sbt unfortunatly is equal to 0.
thanx.

**Comment by dlecan** [comment]
> Everythings works fine but i have the logger problem on JBOSS7.
> I saw you solve it. Could you please send a war archive example with the logger issue solved?

https://play-war.ci.cloudbees.com/job/Play_2_War_-_on_push_-_with_integration_tests_-_on_develop_branch/ws/sample/servlet30/target/a-play2war-sample-servlet30-1.0-SNAPSHOT.war

**Comment by dlecan** [comment]
> maybe the problem of the plug in is related to the sbt but at moment we are in emergency... and my knowledge on sbt unfortunatly is equal to 0.

I will close the issue, but don't hesitate to reopen it if you have more information to send.

**Comment by matgi** [comment]
thanx . just only a question we use servlet 2.5 could i use this as example with JBOSS logissue fixed

https://play-war.ci.cloudbees.com/job/Play_2_War_-_on_push_-_with_integration_tests_-_on_develop_branch/ws/sample/servlet25/target/

thanx.
Matteo.

**Comment by dlecan** [comment]
> just only a question we use servlet 2.5 could i use this as example with JBOSS logissue fixed
> https://play-war.ci.cloudbees.com/job/Play_2_War_-_on_push_-_with_integration_tests_-_on_develop_branch/ws/sample/servlet25/target/

Yes, that is the same sample, but for Servlet 2.5 container.
Warning, performances are much lower than with Servlet 3.0 sample (2 threads for each request).

If you can choose, you should use Servlet 3.0 implementation for your project.

**Comment by dlecan** [comment]
@matgi 

What happens when you add custom dependencies ? Does it work ?

Such as :

``` scala
val appDependencies = Seq(
  "javax.servlet" % "javax.servlet-api" % "3.0.1"
)
```

Then run `play compile`.

**Comment by matgi** [comment]
@dlecan 

Here is my plugin.sbt

<pre>
// Comment to get more information during initialization
logLevel := Level.Warn
// The Typesafe repository
resolvers += "Typesafe repository" at "http://repo.typesafe.com/typesafe/releases/"
// Use the Play sbt plugin for Play projects
addSbtPlugin("play" % "sbt-plugin" % "2.0.3")
resolvers += "Play2war plugins release" at "http://repository-play-war.forge.cloudbees.com/release/"
addSbtPlugin("com.github.play2war" % "play2-war-plugin" % "0.7.4")
</pre>

Here is my Build.scala:

<pre>
import sbt._
import Keys._
import PlayProject._
//play2war
import com.github.play2war.plugin._
object ApplicationBuild extends Build {
    val appName         = "AdiuWEB"
    val appVersion      = "1.0-SNAPSHOT"
    
    val appDependencies = Seq(
      // Add your project dependencies here,      
      "javax.servlet" % "javax.servlet-api" % "3.0.1"
    )
   
    //istruzioni per attivate play2war
    val projectSettings = Play2WarPlugin.play2WarSettings ++ Seq(
      // Your settings
      Play2WarKeys.servletVersion := "3.0"
    )
            
    val main = PlayProject(
       appName, appVersion, appDependencies, mainLang = JAVA
    ).settings(projectSettings: _*)
    }
</pre>

And here is the play compile result:

<pre>
[info] Loading project definition from D:\jdevNew\sorgenti\produzione\AdiuWEB\project
[warn]  module not found: com.github.play2war#play2-war-plugin;0.7.4
[warn] ==== typesafe-ivy-releases: tried
[warn]   http://repo.typesafe.com/typesafe/ivy-releases/com.github.play2war/play2-war-plugin/scala_2.9.1/sbt_0.11.3/0.7.4/ivys/ivy.xml
[warn] ==== local: tried
[warn]   D:\play-2.0.3\framework\..\repository/local/com.github.play2war/play2-war-plugin/scala_2.9.1/sbt_0.11.3/0.7.4/ivys/ivy.xml
[warn] ==== Typesafe repository: tried
[warn]   http://repo.typesafe.com/typesafe/releases/com/github/play2war/play2-war-plugin_2.9.1_0.11.3/0.7.4/play2-war-plugin-0.7.4.pom
[warn] ==== Play2war plugins release: tried
[warn]   http://repository-play-war.forge.cloudbees.com/release/com/github/play2war/play2-war-plugin_2.9.1_0.11.3/0.7.4/play2-war-plugin-0.7.4.pom
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/com/github/play2war/play2-war-plugin_2.9.1_0.11.3/0.7.4/play2-war-plugin-0.7.4.pom
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.github.play2war#play2-war-plugin;0.7.4: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]          com.github.play2war:play2-war-plugin:0.7.4 (sbtVersion=0.11.3, scalaVersion=2.9.1)
[warn]
[error] {file:/D:/jdevNew/sorgenti/produzione/AdiuWEB/project/}default-5ce1fb/*:update: sbt.ResolveException: unresolved dependency: com.github.play2war#play2-war-plugin;0.7.4: not found
</pre>

thank you very much....
Matgi

**Comment by dlecan** [comment]
@matgi In `plugin.sbt`, can you change `logLevel := Level.Warn` by `logLevel := Level.Debug` and send here back the result of `play compile > log.txt` ?

Thanks

**Comment by matgi** [comment]
@dlecan 

i've tried to do that and i saw this errors:

<pre>
...
[debug] HTTP response status: 404 url=http://repo.typesafe.com/typesafe/ivy-releases/org.codehaus.jackson/jackson-mapper-asl/
[debug] CLIENT ERROR: Not Found url=http://repo.typesafe.com/typesafe/ivy-releases/org.codehaus.jackson/jackson-mapper-asl/
[debug] problem while listing resources in http://repo.typesafe.com/typesafe/ivy-releases/org.codehaus.jackson/jackson-mapper-asl/ with typesafe-ivy-releases:
[debug]   java.io.IOException The HTTP response code for http://repo.typesafe.com/typesafe/ivy-releases/org.codehaus.jackson/jackson-mapper-asl/ did not indicate a success. See log for more detail.
[debug]     typesafe-ivy-releases: unable to list resources for org.codehaus.jackson#jackson-mapper-asl;[1.9.0,2.0.0): 
...
[debug] HTTP response status: 404 url=http://repo.typesafe.com/typesafe/ivy-releases/com.github.play2war/play2-war-plugin/scala_2.9.1/sbt_0.11.3/0.7.4/ivys/ivy.xml
[debug] CLIENT ERROR: Not Found url=http://repo.typesafe.com/typesafe/ivy-releases/com.github.play2war/play2-war-plugin/scala_2.9.1/sbt_0.11.3/0.7.4/ivys/ivy.xml
[debug]     typesafe-ivy-releases: resource not reachable for com.github.play2war#play2-war-plugin;0.7.4: res=http://repo.typesafe.com/typesafe/ivy-releases/com.github.play2war/play2-war-plugin/scala_2.9.1/sbt_0.11.3/0.7.4/ivys/ivy.xml
...
HTTP response status: 404 url=http://repo.typesafe.com/typesafe/releases/com/github/play2war/play2-war-plugin_2.9.1_0.11.3/0.7.4/play2-war-plugin-0.7.4.pom
[debug] CLIENT ERROR: Not Found url=http://repo.typesafe.com/typesafe/releases/com/github/play2war/play2-war-plugin_2.9.1_0.11.3/0.7.4/play2-war-plugin-0.7.4.pom
[debug]     Typesafe repository: resource not reachable for com/github/play2war#play2-war-plugin;0.7.4: res=http://repo.typesafe.com/typesafe/releases/com/github/play2war/play2-war-plugin_2.9.1_0.11.3/0.7.4/play2-war-plugin-0.7.4.pom
[debug]     Typesafe repository: no ivy file found for com.github.play2war#play2-war-plugin;0.7.4
[debug] Play2war plugins release: no namespace defined: using system
[debug]     no ivy file in cache for com.github.play2war#play2-war-plugin;0.7.4: tried D:\play-2.0.3\framework\..\repository\cache\scala_2.9.1\sbt_0.11.3\com.github.play2war\play2-war-plugin\ivy-0.7.4.xml
[debug]      trying http://repository-play-war.forge.cloudbees.com/release/com/github/play2war/play2-war-plugin_2.9.1_0.11.3/0.7.4/play2-war-plugin-0.7.4.pom
[debug]         tried http://repository-play-war.forge.cloudbees.com/release/com/github/play2war/play2-war-plugin_2.9.1_0.11.3/0.7.4/play2-war-plugin-0.7.4.pom
[debug] HTTP response status: 404 url=http://repository-play-war.forge.cloudbees.com/release/com/github/play2war/play2-war-plugin_2.9.1_0.11.3/0.7.4/play2-war-plugin-0.7.4.pom
[debug] CLIENT ERROR: Not Found url=http://repository-play-war.forge.cloudbees.com/release/com/github/play2war/play2-war-plugin_2.9.1_0.11.3/0.7.4/play2-war-plugin-0.7.4.pom
[debug]     Play2war plugins release: resource not reachable for com/github/play2war#play2-war-plugin;0.7.4: res=http://repository-play-war.forge.cloudbees.com/release/com/github/play2war/play2-war-plugin_2.9.1_0.11.3/0.7.4/play2-war-plugin-0.7.4.pom
[debug]     Play2war plugins release: no ivy file found for com.github.play2war#play2-war-plugin;0.7.4
[debug] public: no namespace defined: using system
[debug]     no ivy file in cache for com.github.play2war#play2-war-plugin;0.7.4: tried D:\play-2.0.3\framework\..\repository\cache\scala_2.9.1\sbt_0.11.3\com.github.play2war\play2-war-plugin\ivy-0.7.4.xml
[debug]      trying http://repo1.maven.org/maven2/com/github/play2war/play2-war-plugin_2.9.1_0.11.3/0.7.4/play2-war-plugin-0.7.4.pom
[debug]         tried http://repo1.maven.org/maven2/com/github/play2war/play2-war-plugin_2.9.1_0.11.3/0.7.4/play2-war-plugin-0.7.4.pom
[debug] HTTP response status: 404 url=http://repo1.maven.org/maven2/com/github/play2war/play2-war-plugin_2.9.1_0.11.3/0.7.4/play2-war-plugin-0.7.4.pom
[debug] CLIENT ERROR: Not Found url=http://repo1.maven.org/maven2/com/github/play2war/play2-war-plugin_2.9.1_0.11.3/0.7.4/play2-war-plugin-0.7.4.pom
[debug]     public: resource not reachable for com/github/play2war#play2-war-plugin;0.7.4: res=http://repo1.maven.org/maven2/com/github/play2war/play2-war-plugin_2.9.1_0.11.3/0.7.4/play2-war-plugin-0.7.4.pom
[debug]     public: no ivy file found for com.github.play2war#play2-war-plugin;0.7.4
[warn]  module not found: com.github.play2war#play2-war-plugin;0.7.4
...
[debug] Module descriptor is processed : org.scala-sbt#precompiled-2_9_2;0.11.3
[debug]     report for default#default-5ce1fb;0.1-SNAPSHOT test-internal produced in D:\play-2.0.3\framework\..\repository\cache\default-default-5ce1fb-test-internal.xml
[debug] Nbr of module to sort : 0
[debug]     report for default#default-5ce1fb;0.1-SNAPSHOT plugin produced in D:\play-2.0.3\framework\..\repository\cache\default-default-5ce1fb-plugin.xml
[debug] Nbr of module to sort : 0
[debug]     report for default#default-5ce1fb;0.1-SNAPSHOT sources produced in D:\play-2.0.3\framework\..\repository\cache\default-default-5ce1fb-sources.xml
[debug] Nbr of module to sort : 0
[debug]     report for default#default-5ce1fb;0.1-SNAPSHOT docs produced in D:\play-2.0.3\framework\..\repository\cache\default-default-5ce1fb-docs.xml
[debug] Nbr of module to sort : 0
[debug]     report for default#default-5ce1fb;0.1-SNAPSHOT pom produced in D:\play-2.0.3\framework\..\repository\cache\default-default-5ce1fb-pom.xml
[debug]     resolve done (6364ms resolve - 397ms download)
[warn] 
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]      com.github.play2war:play2-war-plugin:0.7.4 (sbtVersion=0.11.3, scalaVersion=2.9.1)
[warn] 
[error] {file:/D:/jdevNew/sorgenti/produzione/AdiuWEB/project/}default-5ce1fb/*:update: sbt.ResolveException: unresolved dependency: com.github.play2war#play2-war-plugin;0.7.4: not found
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 
</pre>

Via browser i'm able to reach the url so I've tried to follow "https://play.lighthouseapp.com/projects/82401/tickets/163-behind-a-poxy-proxy-how-do-i-set-http-authenticated-proxy" but nothing change.

thanx.

**Comment by dlecan** [comment]
> [debug] HTTP response status: 404 url=http://repository-play-war.forge.cloudbees.com/release/com/github/play2war/play2-war-plugin_2.9.1_0.11.3/0.7.4/play2-war-plugin-0.7.4.pom
> [debug] CLIENT ERROR: Not Found url=http://repository-play-war.forge.cloudbees.com/release/com/github/play2war/play2-war-plugin_2.9.1_0.11.3/0.7.4/play2-war-plugin-0.7.4.pom

Incredible ! When a proxy conf is wrong, you get network errors or authentication failure, not 404 errors ??

What about Maven, Curl or Wget commands ? Do they work behind your proxy ?
