### ISSUE TITLE
Deploy to jboss as 7.1.1

### ISSUE THREAD

**Issue by tm4rini** [play2war/play2-war-plugin#70]
Hello,

I am developing a web application using playframework 2.0.2, already begotten the WAR file using play2war 0.7.
Right now I'm trying to deploy to jboss AS 7.1.1, I configured to enable-welcome-root="false" the file standalone.xml
and rename the WAR file for "ROOT.war".... But when I start jboss AS the following output is displayed and does not continue with the process.

C:\jboss-as-7.1.1.Final\bin>standalone.bat -b 10.10.1.101
# Calling "C:\jboss-as-7.1.1.Final\bin\standalone.conf.bat"

  JBoss Bootstrap Environment

  JBOSS_HOME: C:\jboss-as-7.1.1.Final

  JAVA: C:\Program Files\Java\jdk1.6.0_29\bin\java

  JAVA_OPTS: -XX:+TieredCompilation -Dprogram.name=standalone.bat -Xms64M -Xmx512M -XX:MaxPermSize=256M -Dsun.rmi.dgc.client.gcInterval=3600000 -Dsun.rmi.dgc.server.gcInterval=3600000 -Djava.net.preferIPv4Stack=true -Dorg.jboss.resolver.warning=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djboss.server.default.config=standalone.xml
# 

14:24:05,734 INFO  [org.jboss.modules] JBoss Modules version 1.1.1.GA
14:24:05,852 INFO  [org.jboss.msc] JBoss MSC version 1.0.2.GA
14:24:05,885 INFO  [org.jboss.as] JBAS015899: JBoss AS 7.1.1.Final "Brontes" starting
14:24:06,467 INFO  [org.xnio] XNIO Version 3.0.3.GA
14:24:06,470 INFO  [org.jboss.as.server] JBAS015888: Creating http management service using socket-binding (management-http)
14:24:06,482 INFO  [org.xnio.nio] XNIO NIO Implementation Version 3.0.3.GA
14:24:06,493 INFO  [org.jboss.remoting] JBoss Remoting version 3.2.3.GA
14:24:06,537 INFO  [org.jboss.as.logging] JBAS011502: Removing bootstrap log handlers
14:24:06,547 INFO  [org.jboss.as.security](ServerService Thread Pool -- 44) JBAS013101: Activating Security Subsystem
14:24:06,590 INFO  [org.jboss.as.connector](MSC service thread 1-5) JBAS010408: Starting JCA Subsystem (JBoss IronJacamar 1.0.9.Final)
14:24:06,607 INFO  [org.jboss.as.naming](ServerService Thread Pool -- 38) JBAS011800: Activating Naming Subsystem
14:24:06,625 INFO  [org.jboss.as.osgi](ServerService Thread Pool -- 39) JBAS011940: Activating OSGi Subsystem
14:24:06,627 INFO  [org.jboss.as.configadmin](ServerService Thread Pool -- 26) JBAS016200: Activating ConfigAdmin Subsystem
14:24:06,635 INFO  [org.jboss.as.clustering.infinispan](ServerService Thread Pool -- 31) JBAS010280: Activating Infinispan subsystem.
14:24:06,643 INFO  [org.jboss.as.security](MSC service thread 1-7) JBAS013100: Current PicketBox version=4.0.7.Final
14:24:06,651 INFO  [org.jboss.as.naming](MSC service thread 1-1) JBAS011802: Starting Naming Service
14:24:06,649 INFO  [org.jboss.as.webservices](ServerService Thread Pool -- 48) JBAS015537: Activating WebServices Extension
14:24:06,745 INFO  [org.jboss.as.mail.extension](MSC service thread 1-1) JBAS015400: Bound mail session [java:jboss/mail/Default]
14:24:06,805 INFO  [org.jboss.as.connector.subsystems.datasources](ServerService Thread Pool -- 27) JBAS010403: Deploying JDBC-compliant driver class org.h2.Driver (version 1.3)
14:24:06,846 INFO  [org.apache.coyote.http11.Http11Protocol](MSC service thread 1-4) Starting Coyote HTTP/1.1 on http--10.10.1.101-8080
14:24:07,051 INFO  [org.jboss.ws.common.management.AbstractServerConfig](MSC service thread 1-2) JBoss Web Services - Stack CXF Server 4.0.2.GA
14:24:07,129 INFO  [org.jboss.as.server.deployment.scanner](MSC service thread 1-5) JBAS015012: Started FileSystemDeploymentService for directory C:\jboss-as-7.1.1.Final\standalone\deployments
14:24:07,148 INFO  [org.jboss.as.remoting](MSC service thread 1-4) JBAS017100: Listening on /127.0.0.1:9999
14:24:07,149 INFO  [org.jboss.as.remoting](MSC service thread 1-7) JBAS017100: Listening on /10.10.1.101:4447
14:24:07,154 INFO  [org.jboss.as.connector.subsystems.datasources](MSC service thread 1-6) JBAS010400: Bound data source [java:jboss/datasources/ExampleDS]
14:24:07,180 INFO  [org.jboss.as.server.deployment](MSC service thread 1-3) JBAS015876: Starting deployment of "ROOT.war"
14:24:10,088 INFO  [org.jboss.as.pojo](MSC service thread 1-4) JBAS017000: Found legacy bean/pojo namespace: urn:jboss:bean-deployer:2.0 - might be missing some xml features (potential exceptions).
14:24:10,240 INFO  [org.jboss.as.connector.deployers.jdbc](MSC service thread 1-6) JBAS010403: Deploying JDBC-compliant driver class org.h2.Driver (version 1.3)
14:24:10,243 INFO  [org.jboss.as.connector.deployers.jdbc](MSC service thread 1-6) JBAS010404: Deploying non-JDBC-compliant driver class org.postgresql.Driver (version 9.0)
14:24:10,330 INFO  [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/]](MSC service thread 1-5) PlayServletWrapper > contextInitialized

**Comment by dlecan** [comment]
Your application seems to be correctly deployed. 

What about http://localhost:8080/? 

Please know that there is an open bug about missing logging traces (even errors) on JBoss (see #54).

**Comment by dlecan** [comment]
@guetomarini Any news on your issue ?

**Comment by dlecan** [comment]
@guetomarini Issue #54 (conflict between JBoss and Play loggers) has been fixed in 0.8-SNAPSHOT.
If you want to try theses snapshots and to see if you have more logs, tell me, I'll explain you how to use them.
