### ISSUE TITLE
uri should include query string

### ISSUE THREAD

**Issue by takezoe** [play2war/play2-war-plugin#72]
In Play2, `request.uri` returns a uri with query string.
Play2CommonServlet should bind servletUri which includes queryString as uri.

See the my commit in the forked repository:
https://github.com/takezoe/play2-war-plugin/commit/8805071eb2fe94cf57606b1db97fc4db36429526

**Comment by dlecan** [comment]
Argg, you're right, I missed this piece of you code. 

I need to write an integration test for this in order to avoid regressions in the future. 

Thx

**Comment by dlecan** [comment]
Play2War v0.7.1 is out, including a fix for this issue.
