### ISSUE TITLE
War file is undeployable

### ISSUE THREAD

**Issue by MaikKlein** [play2war/play2-war-plugin#73]
Hello,

I tried to deploy my app using play2war to amazon with elasticbeanstalk and cloudbees. It didn't really work and I think i made an obvious mistake.

I made a very detailed post on stackoverflow
http://stackoverflow.com/questions/11918820/java-play-2-deployment

Maybe you have an idea what went wrong?

**Comment by dlecan** [comment]
'play package' should result in a war file, not only a jar. Here seems you be the problem. 

Try to package your app with the command 'play war'.

Remember :
- Tomcat 7 : servlet 3.0 
- Tomcat 6 : servlet 2.5

**Comment by dlecan** [comment]
You can find a full simple sample at the end of this post:
http://blog.dlecan.com/play2war-0.7-is-out%21/

**Comment by MaikKlein** [comment]
Ok thank you very much the sample helped me a lot! <3

**Comment by dlecan** [comment]
I would like to be sure there is no issue here: was it a configuration problem? Or does 'play package' command work as expected?
