### ISSUE TITLE
Study Atmosphere framework

### ISSUE THREAD

**Issue by dlecan** [play2war/play2-war-plugin#8]
Cf. https://github.com/Atmosphere/atmosphere

**Comment by dlecan** [comment]
See https://groups.google.com/forum/?fromgroups&hl=fr#!topic/atmosphere-framework/vjJfK2Zo-mE

**Comment by jfarcand** [comment]
Salut, let me know if I can be of any help. I will soon meet with the Play! Core team on the Atmosphere Front so it would be nice to make sure we try to share as much as we can in term of code. 

A+

-- Jeanfrancois
