### ISSUE TITLE
Ebean doesn't work with more than one model class on JBoss 7

### ISSUE THREAD

**Issue by ivinskyi** [play2war/play2-war-plugin#86]
Hi!

I'm trying to deploy my project on cloudbees according to readme. But after deploying war i get 404 errors on every request. 

I use play-2.0.2.
This is how I came to this:
1. Added to plugins.sbt these lines:

``` scala
resolvers += "Play2war plugins release" at "http://repository-play-war.forge.cloudbees.com/release/"
addSbtPlugin("com.github.play2war" % "play2-war-plugin" % "0.7.3")
```
1. Changed Build.scala to have this lines:

``` scala
...
import com.github.play2war.plugin._
...
val projectSettings = Play2WarPlugin.play2WarSettings ++ Seq(
            Play2WarKeys.servletVersion := "3.0"
    )
...
val main = PlayProject(appName, 
                           appVersion, 
                           appDependencies, 
                           mainLang = JAVA,
                           settings = s ++ projectSettings).settings(...)
```

*\* The syntax from readme 

``` scala
      val main = PlayProject(
           appName, appVersion, appDependencies, mainLang = JAVA
      ).settings(projectSettings: _*)
```

*\* does not compile, so I tried somethink similar to syntax in a sample. Maybe I missed something in this configuration?
1. I created `conf/logger.xml` with the lines from the readme.
2. I run `play package` and get <project-name>.war file in target directory.
3. I run two commands from cloudbees SDK which gives no errors:

``` sh
bees app:deploy -a <appid> -t jboss target/<project-name>.war
bees app:update <appid> disableProxyBuffering=true
```

That is all. At this point my app gives only 404-errors.
As you have working demo on cloudbees, I hope you can help.

Thanks!
Anton.

**Comment by dlecan** [comment]
> does not compile, so I tried somethink similar to syntax in a sample. 

It works perfectly for me. Can you give SBT error logs ?

> Maybe I missed something in this configuration?

If you are able to produce WAR file, you can be confident with your configuration :)

> That is all. At this point my app gives only 404-errors.

At Cloudbeed, I remember that Tomcat 6 is the default Servlet container. Which means servlet 2.5.

If you want to use Servlet 3.0 (much better), you need to switch from Tomcat 6 to JBoss 7 (names JavaEE 6 at Cloudbeed).

That should probably solve your issue.

If not, post here your servlet container logs.

**Comment by ivinskyi** [comment]
Hi! 
I use params "-t jboss" with deploy command, so it is JBoss 7.  
Here are servlet container logs:

```
11:31:54,368 INFO  [org.jboss.modules] JBoss Modules version 1.0.2.GA
11:31:55,026 INFO  [org.jboss.msc] JBoss MSC version 1.0.1.GA
11:31:55,247 INFO  [org.jboss.as] JBoss AS 7.0.2.Final "Arc" starting
11:31:56,535 INFO  [org.jboss.as.logging] Removing bootstrap log handlers
11:31:56,547 INFO  [org.jboss.as.connector.subsystems.datasources] (Controller Boot Thread) Deploying non-JDBC-compliant driver class com.mysql.jdbc.Driver (version 5.1)
11:31:56,571 INFO  [org.jboss.as.clustering.infinispan.subsystem] (Controller Boot Thread) Activating Infinispan subsystem.
11:31:56,689 INFO  [org.jboss.as.naming] (Controller Boot Thread) JBAS011800: Activating Naming Subsystem
11:31:56,699 INFO  [org.jboss.as.naming] (MSC service thread 1-2) JBAS011802: Starting Naming Service
11:31:56,705 INFO  [org.jboss.as.security] (Controller Boot Thread) Activating Security Subsystem
11:31:57,068 INFO  [org.apache.catalina.core.AprLifecycleListener] (MSC service thread 1-3) The Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: /opt/java6/jre/lib/amd64/server:/opt/java6/jre/lib/amd64:/opt/java6/jre/../lib/amd64:/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
11:31:57,169 INFO  [org.jboss.as.ee] (Controller Boot Thread) Activating EE subsystem
11:31:57,208 INFO  [org.apache.coyote.http11.Http11Protocol] (MSC service thread 1-2) Starting Coyote HTTP/1.1 on http--0.0.0.0-8873
11:31:57,209 INFO  [com.cloudbees.jboss.stax.extension.StaxService] (MSC service thread 1-2) StaxService start
11:31:57,209 INFO  [com.cloudbees.jboss.stax.extension.StaxService] (MSC service thread 1-2) Registering application valve
11:31:57,374 INFO  [org.jboss.as.connector] (MSC service thread 1-3) Starting JCA Subsystem (JBoss IronJacamar 1.0.3.Final)
11:31:58,127 WARN  [org.jboss.as.deployment] (MSC service thread 1-2) Reliable deployment behaviour is not possible when auto-deployment of exploded content is enabled (i.e. deployment without use of ".dodeploy"' marker files). Configuration of auto-deployment of exploded content is not recommended in any situation where reliability is desired. Configuring the deployment scanner's auto-deploy-exploded setting to "false" is recommended.
11:31:58,131 INFO  [org.jboss.as.deployment] (MSC service thread 1-2) Started FileSystemDeploymentService for directory /var/genapp/apps/a11e7f8b/deployments
11:31:58,179 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-3) Starting deployment of "app.ear"
11:31:58,212 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-1) Starting deployment of "webapp.war"
11:32:08,150 INFO  [org.jboss.as.jpa] (MSC service thread 1-2) added javax.persistence.api dependency to app.ear
11:32:08,160 INFO  [org.jboss.as.jpa] (MSC service thread 1-3) added javax.persistence.api dependency to webapp.war
11:32:10,180 INFO  [org.jboss.as.connector.deployers.jdbc] (MSC service thread 1-2) Deploying JDBC-compliant driver class org.h2.Driver (version 1.3)
11:32:10,957 INFO  [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/]] (MSC service thread 1-2) PlayServletWrapper > contextInitialized
```

**Comment by dlecan** [comment]
Hum, everything seems to be ok.

So you load `http://my_host.cloudbees.net` and you get a 404 error.

What does `routes` file look like ?

**Comment by ivinskyi** [comment]
Hi
My routes file looks like 

```
# Home page
GET     /                           controllers.core.Application.index()


# -------------------------- Users ------------------------------------

# list (default pagination parameters)
GET     /crud/users                 controllers.crud.Users.list(p:Int ?= 0, s ?= "fullname", o ?= "asc", f ?= "")
# Add
GET     /crud/users/new             controllers.crud.Users.create()
POST    /crud/users                 controllers.crud.Users.save()
# Edit
GET     /crud/users/:id             controllers.crud.Users.edit(id:Long)
POST    /crud/users/:id             controllers.crud.Users.update(id:Long)
# Delete
POST    /crud/users/:id/delete      controllers.crud.Users.delete(id:Long)
... routes for other crud classes ...

#----------------------------- Static -----------------------------------------

# Map static resources from the /public folder to the /assets URL path
GET     /assets/*file               controllers.Assets.at(path="/public", file)

#------------------------------ SecureSocial ----------------------------------

# Login page
GET     /login                      securesocial.controllers.LoginPage.login
GET     /logout                     securesocial.controllers.LoginPage.logout

# User Registration
GET     /signup                     securesocial.controllers.Registration.signUp
POST    /signup                     securesocial.controllers.Registration.handleSignUp

GET     /authenticate/:provider     securesocial.controllers.LoginPage.authenticate(provider)
POST    /authenticate/:provider     securesocial.controllers.LoginPage.authenticateByPost(provider)
```

What should be in the generated war file?
I noticed that it doesn't have anything except `META-INF\MANIFEST.MF` and `WEB-INF\lib` directory with all the libraries. Does it generate `web.xml`? or should I write it myself? 
I saw on this post 
http://stackoverflow.com/questions/11957578/app-runs-locally-but-returns-404-running-on-cloudbees
that my problem might be caused by none servlets registered for an application.

**Comment by ivinskyi** [comment]
I've made a new blank application, added war package plugin and it works fine. I'll try to add all my other plugins and functionality one-by-one and figure out what gives the strange behavior.

**Comment by ivinskyi** [comment]
Hi!

I found that this problem is caused by something in ebean ORM integration.
Specifically, if comment this line in application.conf:
ebean.default="models.*"
the application works on cloudbees. But, of course, the database is not reachable.

The last idea about solving it is to generate war with play20 built from source. 
Is there any way to use play2-war-plugin with 2.1-SNAPSHOT?

**Comment by dlecan** [comment]
> ebean.default="models.*

Something may be wrong on JBoss when EBean looks for classes in classpath.

Can you try to register al of your model classes ?
Such as `ebean.default=models.Order,models.OrderItem,...`

> The last idea about solving it is to generate war with play20 built from source.

What do you want to do ?

> Is there any way to use play2-war-plugin with 2.1-SNAPSHOT?

No, 2.1-SNAPSHOT breaks too many apis and is not finished yet. I will wait for alpha or beta release to begin to adapt Play2War for Play 2.1

**Comment by ivinskyi** [comment]
Hi!

If i register only 1 my class, it works well :

```
ebean.default=models.Order
```

But if I add 2 or more classes, it does not work:

```
ebean.default="models.Order,models.OrderItem,..."
```

So I'll wait for Play2War for Play 2.1 (i'll try 2.0.4 too). 
In meantime I will use other cloud application platforms.

**Comment by dlecan** [comment]
Can you test on Tomcat ? Exception is hidden on JBoss, you could see it on Tomcat ...

I will setup a project with EBean database access to see what happens.

**Comment by dlecan** [comment]
Here is the hidden exception linked to `ebean.default="models.*"` :

```
16:53:35,981 ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/]] (MSC service thread 1-4) Exception lors de l'envi de l'ÚvÞnement contexte initialisÚ (context initialized) Ó l'instance de classe d'Úcoute (listener) play.core.server.servlet30.Play2Servlt: java.lang.NoClassDefFoundError: sun/net/www/ParseUtil
        at org.reflections.util.ClasspathHelper.forPackage(ClasspathHelper.java:52) [org.reflections.reflections-0.9.6.jar:]
        at play.api.Application.getTypesAnnotatedWith(Application.scala:264) [play.play_2.9.1-2.0-SNAPSHOT.jar:]
        at play.Application.getTypesAnnotatedWith(Application.java:102) [play.play_2.9.1-2.0-SNAPSHOT.jar:]
        at play.db.ebean.EbeanPlugin.onStart(EbeanPlugin.java:61) [play.play_2.9.1-2.0-SNAPSHOT.jar:]
        at play.api.Play$$anonfun$start$1.apply(Play.scala:60) [play.play_2.9.1-2.0-SNAPSHOT.jar:]
        at play.api.Play$$anonfun$start$1.apply(Play.scala:60) [play.play_2.9.1-2.0-SNAPSHOT.jar:]
        at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59) [org.scala-lang.scala-library-2.9.1.jar:]
        at scala.collection.immutable.List.foreach(List.scala:45) [org.scala-lang.scala-library-2.9.1.jar:]
        at play.api.Play$.start(Play.scala:60) [play.play_2.9.1-2.0-SNAPSHOT.jar:]
        at play.core.server.servlet.WarApplication.<init>(Play2Server.scala:57) [com.github.play2war.play2-war-core-common_2.9.1-0.8-SNAPSHOT.jar:]
        at play.core.server.servlet.Play2Servlet.contextInitialized(Play2CommonServlet.scala:363) [com.github.play2war.play2-war-core-common_2.9.1-0.8-SNAPSHOT.jar:]
        at org.apache.catalina.core.StandardContext.contextListenerStart(StandardContext.java:3368) [jbossweb-7.0.1.Final.jar:7.0.2.Final]
        at org.apache.catalina.core.StandardContext.start(StandardContext.java:3821) [jbossweb-7.0.1.Final.jar:7.0.2.Final]
        at org.jboss.as.web.deployment.WebDeploymentService.start(WebDeploymentService.java:70) [jboss-as-web-7.0.2.Final.jar:7.0.2.Final]
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1824)
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1759)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886) [:1.6.0_29]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908) [:1.6.0_29]
        at java.lang.Thread.run(Thread.java:662) [:1.6.0_29]
Caused by: java.lang.ClassNotFoundException: sun.net.www.ParseUtil from [Module "deployment.ROOT.war:main" from Service Module Loader]
        at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:191)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:361)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:333)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:310)
        at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:103)
        ... 19 more
```

**Comment by dlecan** [comment]
Probably due to http://code.google.com/p/reflections/issues/detail?id=105
An upgrade of `org.reflections` may solve this issue.

Can you replace `WEB-INF-lib/org.reflections.reflections-0.9.6.jar` in your generated war by this one: http://search.maven.org/remotecontent?filepath=org/reflections/reflections/0.9.8/reflections-0.9.8.jar and try to deploy your application in JBoss ?

**Comment by ivinskyi** [comment]
Ok. I'll try.

**Comment by dlecan** [comment]
Don't waste your time with the previous modification, `org.reflections framework` needs an extra configuration when it is embedded in JBoss :-/

See http://code.google.com/p/reflections/wiki/JBossIntegration

**Comment by dlecan** [comment]
I will think about how to integrate this into Play2War.
org.reflections has already been upgraded in Play 2.1-SNAPSHOT. So I have requested a backport in 2.0.x branch.
See https://github.com/playframework/Play20/pull/329

**Comment by dlecan** [comment]
I found a solution for this issue, and it will be available in Play2War 0.8.

See demo with 2 model classes:
http://ebean-demo.play-war.cloudbees.net/

> In meantime I will use other cloud application platforms.

Cloudbees now supports native play deployment model:
https://developer.cloudbees.com/bin/view/RUN/Playframework

**Comment by ivinskyi** [comment]
Great news! Both of them.

**Comment by dlecan** [comment]
Hello guys, here a sum up of the problem and a solution.

### Problem

Play doesn't work on JBoss 7 because of 2 issues :
1. Play depends on `org.reflections` framework v0.9.6 which uses `com.sun` classes (very bad !). This is forbidden by JBoss 7 classloader
2. `org.reflections` framework needs extra configuration to be compatible with JBoss VFS (Virtual File System)

### Solution

**This solution is compatible with all Play2War versions**.

Just embed a new dependency in your WAR package, which should do the job.

In your `MY_PROJECT/project/Build.scala` file, add:

``` scala
val appDependencies = Seq(
  // ... Actual dependencies
  "com.dlecan.reflections" % "jboss7-vfs-integration" % "1.0.1" // add this after your others dependencies
)
```

That's all.

What doest it do ?
1. It upgrades `org.reflection` to 0.9.8 to solve 1st problem
2. It provides an extra configuration for `org.reflection` to handle JBoss 7 VFS to solve 2nd one

**This solution is compatible with all Play2War versions**.

Can you test this with your applications ?
Thanks

**Comment by ivinskyi** [comment]
Looks like it works fine now.
Thanks!

**Comment by dlecan** [comment]
Play2War 0.8 has been released, with a fix for this issue.
