### ISSUE TITLE
Possible response mixup

### ISSUE THREAD

**Issue by sejensen** [play2war/play2-war-plugin#87]
Hi everyone

We have a strange issue in production on jboss.

It seems that responses is being concatinated from ajax calls and action returned rendering and it is not possible to predict when it happens.

Can this perhaps be due to a change in request response in the war plugin or if we configure akka wrong?

I am just asking here, since I cannot figure out why this happens.

We are using "com.github.play2war" % "play2-war-plugin" % "0.7.2"
and have this in our build

 val projectSettings = Play2WarPlugin.play2WarSettings ++ Seq(
    Play2WarKeys.servletVersion := "3.0"//,
  )

Kind regards
Steffen

**Comment by dlecan** [comment]
Which JBoss version ?

Is it possible to see extracts from `routes` and your action controllers which are being concatenated ?

**Comment by dlecan** [comment]
How to you know response are being concatenated ?

**Comment by sejensen** [comment]
Hi Damien

I think
It has something to dó with out chunked response for CSV.

We are running eap 6 og jboss.

And will keep investigating.

/steffen

**Comment by sejensen** [comment]
By using the chrome developer tools and looking at the network traffic with
request response and in the response data see a concatinated result from
two difference controllers

/Steffen

**Comment by dlecan** [comment]
I've made another code review, I don't understand how Servlet provided by Play2War can generate such a trouble.

Servlets are thread-safe (no instance variables) and I can't see how reponses could be mixed-up.

> Can this perhaps be due to a change in request response in the war plugin or if we configure akka wrong?

Do you mean it was working correctly before Play2War 0.7.x ?
Play2War 0.7 is a pretty big refactoring to handle either Servlet 2.5 or Servlet 3.0 containers. Something could be wrong with that ...

**Comment by sejensen** [comment]
Hi Damien

We are not sure where the issue is.

It can be Play it self or just our use of Akka or the jboss-war
constallation.

But our problem occurs when we start som streaming of csv values. Then
other responses get cluttered with these csv data.

We have an controller method with `Ok.stream(header andThen dataContent)`

where `datacontent` is an enumarator callback of a paged query.

``` scala
 def pageEnumerateQuery[T](query: Query[T], dataToBytes: T => Array[Byte],
pageSize: Int): Enumerator[Array[Byte]] = {
    var page = 0

    Enumerator.fromCallback(
      () => {
        val bytes = inTransaction {
          query.page(pageSize * page, pageSize).toList.map(dataToBytes)
        }

        if (bytes.isEmpty) {
          Promise.pure(None)
        } else {
          page += 1
          Promise.pure(Some(bytes.flatten.toArray))
        }
      },
     () => Logger.debug("paging completed")
     ,(msg:String, input: Input[Array[Byte]]) => Logger.error("error
enumerating pages: "+msg)
    )
```

Unless you have an idea of why this happens we will try to solve the
problem our selves.

Thanks for your effort!
/Steffen

**Comment by dlecan** [comment]
Can you try with Play2War 0.6 ?

**Comment by sejensen** [comment]
I am not able to get our project working on jboss with version 0.6 of the plugin. I am not sure why it does not work, but without logging it is very timeconsuming.

Any Ideas what to do?

And does other people have success with using "long-running" streaming using play-war plugin?

Kind regards
Steffen

**Comment by dlecan** [comment]
> And does other people have success with using "long-running" streaming using play-war plugin?

Yes, on Tomcat with APR connector. Big (> 1000Mb) files are downloaded.

> I am not able to get our project working on jboss with version 0.6 of the plugin.

Ok, Play2War 0.6 was only compatible with Play 2.0.2, may be that's the issue.

> but without logging it is very timeconsuming.

Backporting logging workaround on JBoss from Play2War 0.8 to a 0.7.4 version, in order for you to have logs !
This issue #82 could be interesting for you.

> Any Ideas what to do?

Tell me more on :
- your infrastructure : load-balancer, JBoss HTTP connector configuration (which one, socket/async timeout configurations, ...)
- how do you know your datas are mixed up ?
  It is very, very strange that only CSV streams are mixed up. Play2war and Play runtime handle all requests with the same steps : HTTP request decoding, routing (throught `routes`), processing (Akka), sending result to the client.

When I write **all requests**, I mean all assets (css, image, JS files, ...) and dynamic requests.
And I find very strange that css, images or JS files are not corrupted.

**Comment by sejensen** [comment]
Hi Damian

Thank you for your email.

Here is our setup, we were using war plugin 0.7.2 and I have just updated
to 0.7.3. Have tried to look at the code but not sure this have any effect.

nginx -> jboss eap 6.0 on readhat linux supported with encodingFilter utf-8

nginx is configured this way:

server {
    listen       443;
    server_name  ip_of_server;

```
ssl                  on;
ssl_certificate      secret;
ssl_certificate_key  secret;

ssl_session_timeout  5m;

ssl_protocols  SSLv2 SSLv3 TLSv1;
ssl_ciphers  HIGH:!aNULL:!MD5;
ssl_prefer_server_ciphers   on;

location / {
    proxy_pass http://localhost:8080;
```

proxy_redirect off;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header Host $http_host;
    }
}

I am not sure which part of the jboss config you would like to know?

We usally get the error when starting the jboss with the project, opening
our browser and logs in. Starts csv report streaming and then do other
stuff in the system.

When we use the system sometimes a view renders with errors (ajax json
response fails or view consists of csv data + correct view). It may also
happen with assetst and stuff, but the browser caches these when first
logged in.

Our akka conf is:

play {
        akka {
            event-handlers = ["akka.event.slf4j.Slf4jEventHandler"]
            #event-handlers = ["akka.event.Logging$DefaultLogger"]
            loglevel = DEBUG

```
        #log-config-on-start = on

        actor {

            deployment {

                /actions {
                    router = round-robin
                    nr-of-instances = 150
                }

                /promises {
                    router = round-robin
                    nr-of-instances = 150
                }

            }

            retrieveBodyParserTimeout = 20 second

            actions-dispatcher = {
                fork-join-executor {
                    parallelism-factor = 1.0
                    parallelism-max = 150
                }
            }

            promises-dispatcher = {
                fork-join-executor {
                    parallelism-factor = 1.0
                    parallelism-max = 150
                }
            }

            websockets-dispatcher = {
                fork-join-executor {
                    parallelism-factor = 1.0
                    parallelism-max = 150
                }
            }

            default-dispatcher = {
                fork-join-executor {
                    parallelism-factor = 1.0
                    parallelism-max = 150
                }
            }

        }

    }

}
```

**Comment by dlecan** [comment]
> When we use the system sometimes a view renders with errors (ajax json response fails or view consists of csv data + correct view). It may also happen with assetst and stuff, but the browser caches these when first logged in.

Ok, so it happens for every kinds of requests. So something is wrong between the client and Akka : nginx, JBossWeb, Play2War, Play2, Akka

What is the load applied to your infrastructure ? (req/s, number of concurrent users, ...)

**Comment by sejensen** [comment]
The load is minimal and users is still testing but we were planning to go live on friday.

It seems that the issue disappered after upgrading from 0.7.2 to 0.7.3 Can this be true?

Another issue that remains is that when an user cancels the streaming or closes their browser our enumerator fromcallback still carries with the processing. This results in unneccessary db load and a lot of these exceptions in the log. 

```
2012-09-25 08:36:11,287 DEBUG play  - ClientAbortException:  java.net.SocketException: Broken pipe
2012-09-25 08:36:23,567 DEBUG play  - ClientAbortException:  java.net.SocketException: Broken pipe
2012-09-25 08:36:34,718 DEBUG play  - ClientAbortException:  java.net.SocketException: Broken pipe
```

It doesnt look like a problem when using play netty directly.

Kind regards
Steffen

**Comment by dlecan** [comment]
> It seems that the issue disappered after upgrading from 0.7.2 to 0.7.3 Can this be true?

Here is the diff between 0.7.2 and 0.7.3 : https://github.com/dlecan/play2-war-plugin/commit/bb1c10ec24b9e80c2ca64a9ae28467bb6f66cf80
The relevant change is the async timeout set to infinite value (default is about 5s).

This value was already set to infinite in Play2war 0.6 but was set back to default value in 0.7.x series.
0.7.3 reset this value to infinite. It can be also configured in servlet container config files.

> still carries with the processing. This results in unneccessary db load and a lot of these exceptions in the log.
> `2012-09-25 08:36:11,287 DEBUG play  - ClientAbortException:  java.net.SocketException: Broken pipe`
> It doesnt look like a problem when using play netty directly.

Exception seen in your log file is probably this one :
https://github.com/dlecan/play2-war-plugin/blob/develop/project-code/core/common/src/main/scala/Play2CommonServlet.scala#L216

Exception may not be correctly handled and enumerator/iteratee is not stopped.
See #89.

**Comment by dlecan** [comment]
I will close this issue, as #75 has probably fixed it.
Please reopen it if necessary.
