### ISSUE TITLE
UTF-8 problem

### ISSUE THREAD

**Issue by marcosinigaglia** [play2war/play2-war-plugin#88]
Hi, I noted a strange behavior with utf-8 text.
If I save a utf-8 character with a standard form I have a wrong conversion, there is no problem if I use a "multipart" form.

Play2war 0.7.3
Play 2.0.3
Tomcat 7.0.27

**Comment by dlecan** [comment]
See https://github.com/dlecan/play2-war-plugin/wiki/FAQ#wiki-utf-8-encoding
