### ISSUE TITLE
Missing dependencies error

### ISSUE THREAD

**Issue by pooja2909** [play2war/play2-war-plugin#91]
I am trying to install Play2war on my windows 7. I followed the steps from https://github.com/dlecan/play2-war-plugin/wiki/How-to-help . Bit when I am executing "play war" command from the samples directory, I get the following error: 

::::::::::::::::::::::::::::::::::::::::::::::
::          UNRESOLVED DEPENDENCIES         ::
::::::::::::::::::::::::::::::::::::::::::::::
:: play#play_2.9.1;2.0.2: not found
:: play#templates_2.9.1;2.0.2: not found
:: play#console_2.9.1;2.0.2: not found
:: com.github.play2war#play2-war-plugin;0.8-SNAPSHOT: not found
::::::::::::::::::::::::::::::::::::::::::::::

Where to get these from ?

**Comment by dlecan** [comment]
> :: play#play_2.9.1;2.0.2: not found
> :: play#templates_2.9.1;2.0.2: not found
> :: play#console_2.9.1;2.0.2: not found

Very bad, this should be provided by Play repositories themselves.

> :: com.github.play2war#play2-war-plugin;0.8-SNAPSHOT: not found

Did you hit `sbt publish-local` ?

**Comment by pooja2909** [comment]
yeah i did, and it ended without any error

**Comment by dlecan** [comment]
You need to do `sbt publish-local` each time Play2War code has been modified.
Then you need to repackage your war file with `play war`.

**Comment by pooja2909** [comment]
okie , I did but it is not able to find these dependencies, gives warning : module not find in all four of these

**Comment by pooja2909** [comment]
This time the error is :

::::::::::::::::::::::::::::::::::::::::::::::
::          UNRESOLVED DEPENDENCIES         ::
::::::::::::::::::::::::::::::::::::::::::::::
:: play#play_2.9.1;2.0.2: not found
:: play#templates_2.9.1;2.0.2: not found
:: play#console_2.9.1;2.0.2: not found
:: com.typesafe.config#config;0.2.1: not found
:: com.typesafe.akka#akka-actor;2.0: not found
:: com.github.play2war#play2-war-plugin;0.8-SNAPSHOT: not found
::::::::::::::::::::::::::::::::::::::::::::::

**Comment by pooja2909** [comment]
BTW, my problem isn't resolved yet and you closed the issue ??? Am I doing something so stupid that you don't think I deserve a solution ?

**Comment by dlecan** [comment]
Extract from Wiki.
Read carefully, `sbt` or `play` commands must be run either from `project-code` or `sample` folders.

#### Build and publish plugin and core runtime in local repository

Go to `PLAY2WAR-HOME/project-code`. To publish plugin and core runtime, run

```
sbt publish-local
```

Artifacts are now published in your local Ivy2 repository (``~/.ivy2/local`)

#### Build Play2 WAR sample

Go to `PLAY2WAR-HOME/sample`. To build the WAR file, run

```
play war
```

WAR file is built in `PLAY2WAR-HOME/sample/target`
