### ISSUE TITLE
Module not found error while trying to run sbt -publish local

### ISSUE THREAD

**Issue by pooja2909** [play2war/play2-war-plugin#92]
I get the following error when I do Sbt -publish local from my play2war/samples directory :

H:\JavaLibs\dlecan-play2-war-plugin-87dc8e7\sample>sbt publish-local
[info] Loading project definition from H:\JavaLibs\dlecan-play2-war-plugin-87dc8
e7\sample\project
[warn]  module not found: play#play_2.9.1;2.0.2
[warn] ==== typesafe-ivy-releases: tried
[warn]   http://repo.typesafe.com/typesafe/ivy-releases/play/play_2.9.1/2.0.2/iv
ys/ivy.xml
[warn] ==== local: tried
[warn]   C:\Users\Pooja.ivy2/local/play/play_2.9.1/2.0.2/ivys/ivy.xml
[warn] ==== Local Ivy Repository: tried
[warn]   C:/Users/Pooja/.ivy2/local/play/play_2.9.1/2.0.2/ivys/ivy.xml
[warn] ==== Play2war plugins snapshot: tried
[warn]   http://repository-play-war.forge.cloudbees.com/snapshot/play/play_2.9.1/2.0.2/play_2.9.1-2.0.2.pom
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/play/play_2.9.1/2.0.2/play_2.9.1-2.0.2.po
m
[warn]  module not found: play#templates_2.9.1;2.0.2
[warn] ==== typesafe-ivy-releases: tried
[warn]   http://repo.typesafe.com/typesafe/ivy-releases/play/templates_2.9.1/2.0
.2/ivys/ivy.xml
[warn] ==== local: tried
[warn]   C:\Users\Pooja.ivy2/local/play/templates_2.9.1/2.0.2/ivys/ivy.xml
[warn] ==== Local Ivy Repository: tried
[warn]   C:/Users/Pooja/.ivy2/local/play/templates_2.9.1/2.0.2/ivys/ivy.xml
[warn] ==== Play2war plugins snapshot: tried
[warn]   http://repository-play-war.forge.cloudbees.com/snapshot/play/templates_
2.9.1/2.0.2/templates_2.9.1-2.0.2.pom
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/play/templates_2.9.1/2.0.2/templates_2.9.
1-2.0.2.pom
[warn]  module not found: play#console_2.9.1;2.0.2
[warn] ==== typesafe-ivy-releases: tried
[warn]   http://repo.typesafe.com/typesafe/ivy-releases/play/console_2.9.1/2.0.2
/ivys/ivy.xml
[warn] ==== local: tried
[warn]   C:\Users\Pooja.ivy2/local/play/console_2.9.1/2.0.2/ivys/ivy.xml
[warn] ==== Local Ivy Repository: tried
[warn]   C:/Users/Pooja/.ivy2/local/play/console_2.9.1/2.0.2/ivys/ivy.xml
[warn] ==== Play2war plugins snapshot: tried
[warn]   http://repository-play-war.forge.cloudbees.com/snapshot/play/console_2.
9.1/2.0.2/console_2.9.1-2.0.2.pom
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/play/console_2.9.1/2.0.2/console_2.9.1-2.
0.2.pom
[warn]  module not found: com.typesafe.config#config;0.2.1
[warn] ==== typesafe-ivy-releases: tried
[warn]   http://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.config/conf
ig/0.2.1/ivys/ivy.xml
[warn] ==== local: tried
[warn]   C:\Users\Pooja.ivy2/local/com.typesafe.config/config/0.2.1/ivys/ivy.xm
l
[warn] ==== Local Ivy Repository: tried
[warn]   C:/Users/Pooja/.ivy2/local/com.typesafe.config/config/0.2.1/ivys/ivy.xm
l
[warn] ==== Play2war plugins snapshot: tried
[warn]   http://repository-play-war.forge.cloudbees.com/snapshot/com/typesafe/co
nfig/config/0.2.1/config-0.2.1.pom
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/com/typesafe/config/config/0.2.1/config-0
.2.1.pom
[warn]  module not found: com.typesafe.akka#akka-actor;2.0
[warn] ==== typesafe-ivy-releases: tried
[warn]   http://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.akka/akka-a
ctor/2.0/ivys/ivy.xml
[warn] ==== local: tried
[warn]   C:\Users\Pooja.ivy2/local/com.typesafe.akka/akka-actor/2.0/ivys/ivy.xm
l
[warn] ==== Local Ivy Repository: tried
[warn]   C:/Users/Pooja/.ivy2/local/com.typesafe.akka/akka-actor/2.0/ivys/ivy.xm
l
[warn] ==== Play2war plugins snapshot: tried
[warn]   http://repository-play-war.forge.cloudbees.com/snapshot/com/typesafe/ak
ka/akka-actor/2.0/akka-actor-2.0.pom
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/com/typesafe/akka/akka-actor/2.0/akka-act
or-2.0.pom
[warn]  module not found: com.github.play2war#play2-war-plugin;0.8-SNAPSHOT
[warn] ==== typesafe-ivy-releases: tried
[warn]   http://repo.typesafe.com/typesafe/ivy-releases/com.github.play2war/play
2-war-plugin/scala_2.9.1/sbt_0.11.3/0.8-SNAPSHOT/ivys/ivy.xml
[warn] ==== local: tried
[warn]   C:\Users\Pooja.ivy2/local/com.github.play2war/play2-war-plugin/scala_2
.9.1/sbt_0.11.3/0.8-SNAPSHOT/ivys/ivy.xml
[warn] ==== Local Ivy Repository: tried
[warn]   C:/Users/Pooja/.ivy2/local/com.github.play2war/play2-war-plugin/scala_2
.9.1/sbt_0.11.3/0.8-SNAPSHOT/ivys/ivy.xml
[warn] ==== Play2war plugins snapshot: tried
[warn]   http://repository-play-war.forge.cloudbees.com/snapshot/com/github/play
2war/play2-war-plugin_2.9.1_0.11.3/0.8-SNAPSHOT/play2-war-plugin-0.8-SNAPSHOT.po
m
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/com/github/play2war/play2-war-plugin_2.9.
1_0.11.3/0.8-SNAPSHOT/play2-war-plugin-0.8-SNAPSHOT.pom
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: play#play_2.9.1;2.0.2: not found
[warn]  :: play#templates_2.9.1;2.0.2: not found
[warn]  :: play#console_2.9.1;2.0.2: not found
[warn]  :: com.typesafe.config#config;0.2.1: not found
[warn]  :: com.typesafe.akka#akka-actor;2.0: not found
[warn]  :: com.github.play2war#play2-war-plugin;0.8-SNAPSHOT: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that th
ese dependencies exist with the requested attributes.
[warn]          com.github.play2war:play2-war-plugin:0.8-SNAPSHOT (sbtVersion=0.
11.3, scalaVersion=2.9.1)
[warn]
[error] {file:/H:/JavaLibs/dlecan-play2-war-plugin-87dc8e7/sample/project/}defau
lt-5678e3/*:update: sbt.ResolveException: unresolved dependency: play#play_2.9.1
;2.0.2: not found
[error] unresolved dependency: play#templates_2.9.1;2.0.2: not found
[error] unresolved dependency: play#console_2.9.1;2.0.2: not found
[error] unresolved dependency: com.typesafe.config#config;0.2.1: not found
[error] unresolved dependency: com.typesafe.akka#akka-actor;2.0: not found
[error] unresolved dependency: com.github.play2war#play2-war-plugin;0.8-SNAPSHOT
: not found
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?

**Comment by dlecan** [comment]
Running `sbt publish-local` from `sample` folder can't work?
This command has to be run from `project-code` folder.

In `sample`, you can run `play war`.

**Comment by dlecan** [comment]
> H:\JavaLibs\dlecan-play2-war-plugin-87dc8e7>sbt publish-local // I am
> running sbt publish-local from the play2war folder itself

`sbt publish-local` must be run from `project-code` folder.

**Comment by pooja2909** [comment]
Sorry I pasted the wrong trace... take a look at this:

H:\JavaProjects\scalaprojects\dlecan-play2-war-plugin-8692dfb*project-code*>sbt
p
ublish-local
[info] Loading project definition from
H:\JavaProjects\scalaprojects\dlecan-play
2-war-plugin-8692dfb\project-code\project
[info] Set current project to play2-war (in build
file:/H:/JavaProjects/scalapro
jects/dlecan-play2-war-plugin-8692dfb/project-code/)
[info] Wrote
H:\JavaProjects\scalaprojects\dlecan-play2-war-plugin-8692dfb\proje
ct-code\plugin\target\scala-2.9.1\sbt-0.11.3\play2-war-plugin-0.8-SNAPSHOT.pom
[info] Wrote
H:\JavaProjects\scalaprojects\dlecan-play2-war-plugin-8692dfb\proje
ct-code\core\common\target\scala-2.9.1\play2-war-core-common_2.9.1-0.8-SNAPSHOT.
pom
[info] Wrote
H:\JavaProjects\scalaprojects\dlecan-play2-war-plugin-8692dfb\proje
ct-code\target\scala-2.9.1\play2-war_2.9.1-0.8-SNAPSHOT.pom
[info] :: delivering ::
com.github.play2war#play2-war-core-common_2.9.1;0.8-SNAP
SHOT :: 0.8-SNAPSHOT :: release :: Wed Sep 26 13:42:36 IST 2012
[info]  delivering ivy file to
H:\JavaProjects\scalaprojects\dlecan-play2-war-pl
ugin-8692dfb\project-code\core\common\target\scala-2.9.1\ivy-0.8-SNAPSHOT.xml
[info] :: delivering :: com.github.play2war#play2-war-plugin;0.8-SNAPSHOT
:: 0.8
-SNAPSHOT :: release :: Wed Sep 26 13:42:36 IST 2012
[info]  delivering ivy file to
H:\JavaProjects\scalaprojects\dlecan-play2-war-pl
ugin-8692dfb\project-code\plugin\target\scala-2.9.1\sbt-0.11.3\ivy-0.8-SNAPSHOT.
xml
[info] :: delivering :: com.github.play2war#play2-war_2.9.1;0.8-SNAPSHOT ::
0.8-
SNAPSHOT :: release :: Wed Sep 26 13:42:36 IST 2012
[info]  delivering ivy file to
H:\JavaProjects\scalaprojects\dlecan-play2-war-pl
ugin-8692dfb\project-code\target\scala-2.9.1\ivy-0.8-SNAPSHOT.xml
[info] Wrote
H:\JavaProjects\scalaprojects\dlecan-play2-war-plugin-8692dfb\proje
ct-code\integration-tests\target\scala-2.9.1\integration-tests_2.9.1-0.8-SNAPSHO
T.pom
[info] :: delivering ::
com.github.play2war#integration-tests_2.9.1;0.8-SNAPSHOT
 :: 0.8-SNAPSHOT :: release :: Wed Sep 26 13:42:36 IST 2012
[info]  delivering ivy file to
H:\JavaProjects\scalaprojects\dlecan-play2-war-pl
ugin-8692dfb\project-code\integration-tests\target\scala-2.9.1\ivy-0.8-SNAPSHOT.
xml
[info]  published play2-war_2.9.1 to
C:\Users\Pooja.ivy2/local/com.github.play2
war/play2-war_2.9.1/0.8-SNAPSHOT/poms/play2-war_2.9.1.pom
[info]  published ivy to
C:\Users\Pooja.ivy2/local/com.github.play2war/play2-wa
r_2.9.1/0.8-SNAPSHOT/ivys/ivy.xml
[info] Wrote
H:\JavaProjects\scalaprojects\dlecan-play2-war-plugin-8692dfb\proje
ct-code\core\servlet30\target\scala-2.9.1\play2-war-core-servlet30_2.9.1-0.8-SNA
PSHOT.pom
[info] Wrote
H:\JavaProjects\scalaprojects\dlecan-play2-war-plugin-8692dfb\proje
ct-code\core\servlet25\target\scala-2.9.1\play2-war-core-servlet25_2.9.1-0.8-SNA
PSHOT.pom
[info] :: delivering ::
com.github.play2war#play2-war-core-servlet30_2.9.1;0.8-S
NAPSHOT :: 0.8-SNAPSHOT :: release :: Wed Sep 26 13:42:36 IST 2012
[info]  delivering ivy file to
H:\JavaProjects\scalaprojects\dlecan-play2-war-pl
ugin-8692dfb\project-code\core\servlet30\target\scala-2.9.1\ivy-0.8-SNAPSHOT.xml

[info] :: delivering ::
com.github.play2war#play2-war-core-servlet25_2.9.1;0.8-S
NAPSHOT :: 0.8-SNAPSHOT :: release :: Wed Sep 26 13:42:37 IST 2012
[info]  delivering ivy file to
H:\JavaProjects\scalaprojects\dlecan-play2-war-pl
ugin-8692dfb\project-code\core\servlet25\target\scala-2.9.1\ivy-0.8-SNAPSHOT.xml

[info]  published integration-tests_2.9.1 to
C:\Users\Pooja.ivy2/local/com.gith
ub.play2war/integration-tests_2.9.1/0.8-SNAPSHOT/poms/integration-tests_2.9.1.po
m
[info]  published ivy to
C:\Users\Pooja.ivy2/local/com.github.play2war/integrat
ion-tests_2.9.1/0.8-SNAPSHOT/ivys/ivy.xml
[info] Packaging
H:\JavaProjects\scalaprojects\dlecan-play2-war-plugin-8692dfb\p
roject-code\plugin\target\scala-2.9.1\sbt-0.11.3\play2-war-plugin-0.8-SNAPSHOT.j
ar ...
[info] Done packaging.
[info]  published play2-war-core-common_2.9.1 to
C:\Users\Pooja.ivy2/local/com.
github.play2war/play2-war-core-common_2.9.1/0.8-SNAPSHOT/poms/play2-war-core-com
mon_2.9.1.pom
[info]  published play2-war-core-common_2.9.1 to
C:\Users\Pooja.ivy2/local/com.
github.play2war/play2-war-core-common_2.9.1/0.8-SNAPSHOT/jars/play2-war-core-com
mon_2.9.1.jar
[info]  published play2-war-core-common_2.9.1 to
C:\Users\Pooja.ivy2/local/com.
github.play2war/play2-war-core-common_2.9.1/0.8-SNAPSHOT/srcs/play2-war-core-com
mon_2.9.1-sources.jar
[info]  published ivy to
C:\Users\Pooja.ivy2/local/com.github.play2war/play2-wa
r-core-common_2.9.1/0.8-SNAPSHOT/ivys/ivy.xml
[info]  published play2-war-plugin to
C:\Users\Pooja.ivy2/local/com.github.play
2war/play2-war-plugin/scala_2.9.1/sbt_0.11.3/0.8-SNAPSHOT/poms/play2-war-plugin.
pom
[info]  published play2-war-plugin to
C:\Users\Pooja.ivy2/local/com.github.play
2war/play2-war-plugin/scala_2.9.1/sbt_0.11.3/0.8-SNAPSHOT/jars/play2-war-plugin.
jar
[info]  published play2-war-plugin to
C:\Users\Pooja.ivy2/local/com.github.play
2war/play2-war-plugin/scala_2.9.1/sbt_0.11.3/0.8-SNAPSHOT/srcs/play2-war-plugin-
sources.jar
[info]  published ivy to
C:\Users\Pooja.ivy2/local/com.github.play2war/play2-wa
r-plugin/scala_2.9.1/sbt_0.11.3/0.8-SNAPSHOT/ivys/ivy.xml
[info]  published play2-war-core-servlet30_2.9.1 to
C:\Users\Pooja.ivy2/local/c
om.github.play2war/play2-war-core-servlet30_2.9.1/0.8-SNAPSHOT/poms/play2-war-co
re-servlet30_2.9.1.pom
[info]  published play2-war-core-servlet30_2.9.1 to
C:\Users\Pooja.ivy2/local/c
om.github.play2war/play2-war-core-servlet30_2.9.1/0.8-SNAPSHOT/jars/play2-war-co
re-servlet30_2.9.1.jar
[info]  published play2-war-core-servlet30_2.9.1 to
C:\Users\Pooja.ivy2/local/c
om.github.play2war/play2-war-core-servlet30_2.9.1/0.8-SNAPSHOT/srcs/play2-war-co
re-servlet30_2.9.1-sources.jar
[info]  published ivy to
C:\Users\Pooja.ivy2/local/com.github.play2war/play2-wa
r-core-servlet30_2.9.1/0.8-SNAPSHOT/ivys/ivy.xml
[info]  published play2-war-core-servlet25_2.9.1 to
C:\Users\Pooja.ivy2/local/c
om.github.play2war/play2-war-core-servlet25_2.9.1/0.8-SNAPSHOT/poms/play2-war-co
re-servlet25_2.9.1.pom
[info]  published play2-war-core-servlet25_2.9.1 to
C:\Users\Pooja.ivy2/local/c
om.github.play2war/play2-war-core-servlet25_2.9.1/0.8-SNAPSHOT/jars/play2-war-co
re-servlet25_2.9.1.jar
[info]  published play2-war-core-servlet25_2.9.1 to
C:\Users\Pooja.ivy2/local/c
om.github.play2war/play2-war-core-servlet25_2.9.1/0.8-SNAPSHOT/srcs/play2-war-co
re-servlet25_2.9.1-sources.jar
[info]  published ivy to
C:\Users\Pooja.ivy2/local/com.github.play2war/play2-wa
r-core-servlet25_2.9.1/0.8-SNAPSHOT/ivys/ivy.xml
[success] Total time: 3 s, completed 26 Sep, 2012 1:42:38 PM

H:\JavaProjects\scalaprojects\dlecan-play2-war-plugin-8692dfb\project-code>

and then :

H:\JavaProjects\scalaprojects\dlecan-play2-war-plugin-8692dfb*sample_>play
war
[info] Loading project definition from
H:\JavaProjects\scalaprojects\dlecan-play
2-war-plugin-8692dfb\sample\project
[warn]  module not found: play#play_2.9.1;2.0.2
[warn] ==== typesafe-ivy-releases: tried
[warn]
http://repo.typesafe.com/typesafe/ivy-releases/play/play_2.9.1/2.0.2/iv
ys/ivy.xml
[warn] ==== local: tried
[warn]
H:\JavaLibs\play-2.0.3\framework..\repository/local/play/play_2.9.1/2.
0.2/ivys/ivy.xml
[warn] ==== Local Ivy Repository: tried
[warn]   C:/Users/Pooja/.ivy2/local/play/play_2.9.1/2.0.2/ivys/ivy.xml
[warn] ==== Play2war plugins snapshot: tried
[warn]
http://repository-play-war.forge.cloudbees.com/snapshot/play/play_2.9.1
/2.0.2/play_2.9.1-2.0.2.pom
[warn] ==== public: tried
[warn]
http://repo1.maven.org/maven2/play/play_2.9.1/2.0.2/play_2.9.1-2.0.2.po
m
[warn]  module not found: play#templates_2.9.1;2.0.2
[warn] ==== typesafe-ivy-releases: tried
[warn]
http://repo.typesafe.com/typesafe/ivy-releases/play/templates_2.9.1/2.0
.2/ivys/ivy.xml
[warn] ==== local: tried
[warn]
H:\JavaLibs\play-2.0.3\framework..\repository/local/play/templates_2.9
.1/2.0.2/ivys/ivy.xml
[warn] ==== Local Ivy Repository: tried
[warn]   C:/Users/Pooja/.ivy2/local/play/templates_2.9.1/2.0.2/ivys/ivy.xml
[warn] ==== Play2war plugins snapshot: tried
[warn]
http://repository-play-war.forge.cloudbees.com/snapshot/play/templates_
2.9.1/2.0.2/templates_2.9.1-2.0.2.pom
[warn] ==== public: tried
[warn]
http://repo1.maven.org/maven2/play/templates_2.9.1/2.0.2/templates_2.9.
1-2.0.2.pom
[warn]  module not found: play#console_2.9.1;2.0.2
[warn] ==== typesafe-ivy-releases: tried
[warn]
http://repo.typesafe.com/typesafe/ivy-releases/play/console_2.9.1/2.0.2
/ivys/ivy.xml
[warn] ==== local: tried
[warn]
H:\JavaLibs\play-2.0.3\framework..\repository/local/play/console_2.9.1
/2.0.2/ivys/ivy.xml
[warn] ==== Local Ivy Repository: tried
[warn]   C:/Users/Pooja/.ivy2/local/play/console_2.9.1/2.0.2/ivys/ivy.xml
[warn] ==== Play2war plugins snapshot: tried
[warn]
http://repository-play-war.forge.cloudbees.com/snapshot/play/console_2.
9.1/2.0.2/console_2.9.1-2.0.2.pom
[warn] ==== public: tried
[warn]
http://repo1.maven.org/maven2/play/console_2.9.1/2.0.2/console_2.9.1-2.
0.2.pom
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: play#play_2.9.1;2.0.2: not found
[warn]  :: play#templates_2.9.1;2.0.2: not found
[warn]  :: play#console_2.9.1;2.0.2: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[error]
{file:/H:/JavaProjects/scalaprojects/dlecan-play2-war-plugin-8692dfb/sam
ple/project/}default-44dfa6/_:update: sbt.ResolveException: unresolved
dependenc
y: play#play_2.9.1;2.0.2: not found
[error] unresolved dependency: play#templates_2.9.1;2.0.2: not found
[error] unresolved dependency: play#console_2.9.1;2.0.2: not found
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?

Sorry for the inconvenience.

Pooja

**Comment by dlecan** [comment]
> [warn] :: play#play_2.9.1;2.0.2: not found 
> [warn] :: play#templates_2.9.1;2.0.2: not found
> [warn] :: play#console_2.9.1;2.0.2: not found

Notice now Play2War plugin is found.
Your Play 2.0.2 installation seems to be broken.
Or may be you are using Play 2.0.3 ? sample are still sticked to Play 2.0.2.
If you want to run them with Play 2.0.3, you need to update Play version in `sample/project/plugin.sbt`

**Comment by pooja2909** [comment]
Phew.. finally it worked !

I am using Play 2.0.3 . So there was the issue.

Thanks a ton for rescuing me out !

Pooja
