### ISSUE TITLE
Support NIO Servlet 3.1 API

### ISSUE THREAD

**Issue by dlecan** [play2war/play2-war-plugin#95]
ReadListener,WriteListener
AsyncIOInputSource
AsyncIOOutputSink

**Comment by dlecan** [comment]
Done by #204

**Comment by yanns** [comment]
The PL https://github.com/dlecan/play2-war-plugin/pull/204 only provides the asynchron non-blocking consuming of request, but not the NIO output of play result.

I am actually testing an implementation. If everything goes well, I can pull a request in a few days.

**Comment by yanns** [comment]
done by https://github.com/dlecan/play2-war-plugin/pull/204 and https://github.com/dlecan/play2-war-plugin/pull/243
