### ISSUE TITLE
How to deploy on JBoss 5.1 ?

### ISSUE THREAD

**Issue by roopajavali** [play2war/play2-war-plugin#96]
Please detail the steps to deploy the war generated with play2-war-plugin on JBoss 5.1(Servlet API version - 2.5)

The readme file lists steps for deployment on JBoss 7.0.x but the configuration files listed here(standalone.xml) are not present on JBoss 5.1.

**Comment by dlecan** [comment]
Hello,

What did you try ?

**Comment by roopajavali** [comment]
Here is what I did 
1. Used play2-war-plugin to create the war. Renamed the artifact to root.war
2. Logged into JBoss 5.1 admin console
3. Removed the already existing root.war(the one shipped with JBoss)
4. Deployed the root.war created in step 1
5. Tried accessing the play application using http://localhost:8080/
   The server logs shows a warning message - Unable to process deployment descriptor for context ''

**Comment by dlecan** [comment]
Great !
Don't hesitate to copy/paste error logs :)

I think there is an issue this generated web.xml xml namespace (see #97). As a workaround, you can edit inner `web.xml` file and replace xml namespace as shown in the issue #97.

**Comment by roopajavali** [comment]
It works fine after changing the web.xml. Thanks!

**Comment by dlecan** [comment]
If you need a quick version of Play2War with #97, please tell me. I can release a v0.7.5.
Otherwise, you can wait v0.8.

**Comment by roopajavali** [comment]
Yes, that would be great. Please let me know when you release v0.7.5.

**Comment by dlecan** [comment]
Play2War 0.8 (instead of 0.7.5) has been released, with a fix for issue #97.

**Comment by 0ffTopic** [comment]
I'm sorry to dig up this, but I'm trying to do the exact same steps here, but when I add the resource in the admin console it tells me "null pointer exception" when I give in the war location.

I need to put a play 2.2.4 app on a Jboss 5.1 AG server and I can't figure what I need to do.

**Comment by dlecan** [comment]
@0ffTopic if you have an issue with Play2War, please open a new one with a precise procedure to reproduce your problem.

If you need support to deploy your Play app with Play2War, please:
1/ Read the docummentation
2/ Aks questions on Play Google Groups
